import { buildCategory, type Draft } from "@/lib/exercises/catalog/helpers";

const bicepsDrafts: Draft[] = [
  { slug: "uginanie-sztanga-prosta", name: "Uginanie ze sztangą prostą", en: "Barbell Curl", pattern: "isolation",
    primary: ["biceps"], secondary: ["forearms"], compound: false, equipment: ["Sztanga"], level: "Podstawowy", goals: ["Masa mięśniowa"],
    start: "Stoisz ze sztangą w opuszczonych ramionach, chwyt podchwytem na szerokość barków.",
    steps: ["Przyklej łokcie do tułowia.", "Ugnij ramiona do pełnego skurczu.", "Opuść powoli do pełnego wyprostu."],
    breathing: "Wydech przy uginaniu, wdech przy opuszczaniu.",
    mistakes: ["Bujanie tułowiem", "Cofanie łokci do tyłu", "Skracanie zakresu na dole"],
    regression: "uginanie-sztanga-ez", progression: null, substitutions: ["uginanie-hantlami", "uginanie-wyciag"], protocol: "3 × 10" },
  { slug: "uginanie-sztanga-ez", name: "Uginanie ze sztangą łamaną", en: "EZ-Bar Curl", pattern: "isolation",
    primary: ["biceps"], secondary: ["forearms"], compound: false, equipment: ["Sztanga EZ"], level: "Podstawowy",
    start: "Chwyt na załamaniach gryfu, ramiona opuszczone.",
    steps: ["Ugnij ramiona, trzymając łokcie przy tułowiu.", "Zatrzymaj w skurczu.", "Opuść powoli."],
    mistakes: ["Zbyt szeroki chwyt obciążający nadgarstki"],
    precautions: ["Gryf łamany odciąża nadgarstki przy dolegliwościach."],
    regression: null, progression: "uginanie-sztanga-prosta", substitutions: ["uginanie-sztanga-prosta"], protocol: "3 × 10–12" },
  { slug: "uginanie-hantlami", name: "Uginanie hantli", en: "Dumbbell Curl", pattern: "isolation",
    primary: ["biceps"], secondary: ["forearms"], compound: false, equipment: ["Hantle"], level: "Podstawowy",
    start: "Stoisz z hantlami przy udach, dłonie zwrócone do siebie.",
    steps: ["Uginaj ramiona naprzemiennie lub razem.", "Obróć dłoń w supinację w trakcie ruchu.", "Opuść powoli."],
    mistakes: ["Rozkołysanie hantli"], regression: null, progression: "uginanie-ze-skosem", substitutions: ["uginanie-sztanga-prosta"], protocol: "3 × 12" },
  { slug: "hammer-curl", name: "Uginanie młotkowe", en: "Hammer Curl", pattern: "isolation",
    primary: ["biceps"], secondary: ["forearms"], compound: false, equipment: ["Hantle"], level: "Podstawowy",
    start: "Hantle przy udach, chwyt neutralny.",
    steps: ["Utrzymaj chwyt neutralny przez cały ruch.", "Ugnij ramiona przy tułowiu.", "Opuść powoli."],
    mistakes: ["Rotowanie nadgarstków"], regression: null, progression: null, substitutions: ["uginanie-hantlami", "cross-body-hammer"], protocol: "3 × 12" },
  { slug: "uginanie-ze-skosem", name: "Uginanie ze skosem", en: "Incline Dumbbell Curl", pattern: "isolation",
    primary: ["biceps"], secondary: [], compound: false, equipment: ["Hantle", "Ławka regulowana"],
    start: "Siedzisz na ławce odchylonej do tyłu, ramiona swobodnie w dole.",
    steps: ["Nie unoś łokci do przodu.", "Ugnij ramiona do skurczu.", "Opuść do pełnego rozciągnięcia."],
    mistakes: ["Podnoszenie łokci do przodu"], cues: ["Odchylenie wydłuża zakres i mocniej rozciąga biceps"],
    regression: "uginanie-hantlami", progression: null, substitutions: ["bayesian-curl"], protocol: "3 × 12" },
  { slug: "preacher-curl", name: "Uginanie na modlitewniku", en: "Preacher Curl", pattern: "isolation",
    primary: ["biceps"], secondary: [], compound: false, equipment: ["Sztanga EZ", "Ławka regulowana"],
    start: "Ramiona oparte o pulpit, łokcie stabilnie na podparciu.",
    steps: ["Ugnij ramiona do pełnego skurczu.", "Opuszczaj powoli, kontrolując dolną fazę.", "Nie prostuj gwałtownie łokci na dole."],
    mistakes: ["Gwałtowne prostowanie na dole"], precautions: ["Przy dolegliwościach łokcia ogranicz dolny zakres."],
    regression: "uginanie-sztanga-ez", progression: "spider-curl", substitutions: ["machine-curl"], protocol: "3 × 10–12" },
  { slug: "spider-curl", name: "Spider curl", en: "Spider Curl", pattern: "isolation",
    primary: ["biceps"], secondary: [], compound: false, equipment: ["Hantle", "Ławka regulowana"],
    start: "Leżysz klatką na ławce ustawionej na 45 stopni, ramiona zwisają pionowo.",
    steps: ["Ugnij ramiona, nie ruszając łokciami.", "Zatrzymaj w skurczu.", "Opuść powoli."],
    mistakes: ["Odrywanie klatki od ławki"], regression: "preacher-curl", progression: null, substitutions: ["preacher-curl"], protocol: "3 × 12" },
  { slug: "concentration-curl", name: "Uginanie koncentryczne", en: "Concentration Curl", pattern: "isolation",
    primary: ["biceps"], secondary: [], compound: false, equipment: ["Hantel"], level: "Podstawowy", laterality: "jednostronne",
    start: "Siedzisz, łokieć oparty o wewnętrzną stronę uda.",
    steps: ["Ugnij ramię do pełnego skurczu.", "Zatrzymaj na moment.", "Opuść powoli."],
    mistakes: ["Odrywanie łokcia od uda"], regression: null, progression: null, substitutions: ["uginanie-hantlami"], protocol: "3 × 12 na stronę" },
  { slug: "uginanie-wyciag", name: "Uginanie na wyciągu", en: "Cable Curl", pattern: "isolation",
    primary: ["biceps"], secondary: ["forearms"], compound: false, equipment: ["Wyciąg dolny"], level: "Podstawowy",
    start: "Stoisz przodem do dolnego wyciągu, uchwyt w dłoniach.",
    steps: ["Utrzymaj łokcie nieruchomo przy tułowiu.", "Ugnij ramiona przeciw stałemu oporowi.", "Opuść powoli."],
    mistakes: ["Cofanie łokci"], regression: null, progression: "bayesian-curl", substitutions: ["uginanie-sztanga-prosta"], protocol: "3 × 12–15" },
  { slug: "bayesian-curl", name: "Bayesian curl", en: "Bayesian Curl", pattern: "isolation",
    primary: ["biceps"], secondary: [], compound: false, equipment: ["Brama kablowa"], laterality: "jednostronne",
    start: "Stoisz tyłem do wyciągu, ramię odwiedzione do tyłu, linka za tułowiem.",
    steps: ["Utrzymaj ramię za linią tułowia.", "Ugnij przedramię do skurczu.", "Opuść do pełnego rozciągnięcia."],
    mistakes: ["Przesuwanie łokcia do przodu"], cues: ["Pozycja za tułowiem mocno rozciąga długą głowę bicepsa"],
    regression: "uginanie-wyciag", progression: null, substitutions: ["uginanie-ze-skosem"], protocol: "3 × 12 na stronę" },
  { slug: "machine-curl", name: "Uginanie na maszynie", en: "Machine Curl", pattern: "isolation",
    primary: ["biceps"], secondary: [], compound: false, equipment: ["Maszyna stosowa"], level: "Podstawowy",
    start: "Ramiona oparte o pulpit maszyny, uchwyty w dłoniach.",
    steps: ["Ugnij ramiona do skurczu.", "Wróć powoli, nie uderzając stosu."],
    mistakes: ["Uderzanie ciężarem o stos"], regression: null, progression: "preacher-curl", substitutions: ["preacher-curl"], protocol: "3 × 12" },
  { slug: "reverse-curl", name: "Uginanie odwrotnym chwytem", en: "Reverse Curl", pattern: "isolation",
    primary: ["forearms"], secondary: ["biceps"], compound: false, equipment: ["Sztanga EZ"], level: "Podstawowy",
    start: "Chwyt nachwytem, ramiona opuszczone.",
    steps: ["Ugnij ramiona, trzymając nadgarstki proste.", "Zatrzymaj w skurczu.", "Opuść powoli."],
    mistakes: ["Załamywanie nadgarstków"], regression: null, progression: "zottman-curl", substitutions: ["hammer-curl"], protocol: "3 × 12" },
  { slug: "zottman-curl", name: "Zottman curl", en: "Zottman Curl", pattern: "isolation",
    primary: ["biceps", "forearms"], secondary: [], compound: false, equipment: ["Hantle"],
    start: "Hantle przy udach, chwyt podchwytem.",
    steps: ["Ugnij ramiona podchwytem.", "W górze obróć dłonie nachwytem.", "Opuść powoli nachwytem."],
    mistakes: ["Zbyt duży ciężar uniemożliwiający kontrolę w fazie opuszczania"],
    regression: "reverse-curl", progression: null, substitutions: ["hammer-curl"], protocol: "3 × 10" },
  { slug: "drag-curl", name: "Drag curl", en: "Drag Curl", pattern: "isolation",
    primary: ["biceps"], secondary: [], compound: false, equipment: ["Sztanga", "Sztanga EZ"],
    start: "Sztanga przy udach, chwyt podchwytem.",
    steps: ["Prowadź sztangę wzdłuż tułowia, cofając łokcie.", "Zatrzymaj przy dolnych żebrach.", "Opuść powoli."],
    mistakes: ["Odrywanie sztangi od tułowia"], regression: "uginanie-sztanga-ez", progression: null, substitutions: ["uginanie-sztanga-prosta"], protocol: "3 × 12" },
  { slug: "cross-body-hammer", name: "Uginanie młotkowe skośne", en: "Cross-Body Hammer Curl", pattern: "isolation",
    primary: ["biceps", "forearms"], secondary: [], compound: false, equipment: ["Hantle"], level: "Podstawowy", laterality: "naprzemienne",
    start: "Hantle przy udach, chwyt neutralny.",
    steps: ["Prowadź hantel skośnie w stronę przeciwnego barku.", "Zatrzymaj w skurczu.", "Opuść powoli i zmień stronę."],
    mistakes: ["Rotowanie tułowia"], regression: null, progression: null, substitutions: ["hammer-curl"], protocol: "3 × 10 na stronę" },
];

const tricepsDrafts: Draft[] = [
  { slug: "prostowanie-na-wyciagu", name: "Prostowanie ramion na wyciągu", en: "Triceps Pushdown", pattern: "isolation",
    primary: ["triceps"], secondary: [], compound: false, equipment: ["Wyciąg górny"], level: "Podstawowy", goals: ["Masa mięśniowa"],
    start: "Stoisz przodem do wyciągu, uchwyt na wysokości klatki, łokcie przy tułowiu.",
    steps: ["Przyklej łokcie do żeber.", "Wyprostuj ramiona do pełnego wyprostu.", "Wróć powoli do kąta prostego."],
    breathing: "Wydech przy prostowaniu, wdech przy powrocie.",
    mistakes: ["Pomaganie tułowiem", "Odrywanie łokci od tułowia"],
    regression: null, progression: "rope-pushdown", substitutions: ["rope-pushdown", "prostowanie-jednoracz"], protocol: "3 × 12–15" },
  { slug: "rope-pushdown", name: "Prostowanie z liną", en: "Rope Pushdown", pattern: "isolation",
    primary: ["triceps"], secondary: [], compound: false, equipment: ["Wyciąg górny"], level: "Podstawowy",
    start: "Lina na wyciągu górnym, dłonie zwrócone do siebie.",
    steps: ["Wyprostuj ramiona, rozchodząc końce liny.", "Zatrzymaj w pełnym skurczu.", "Wróć powoli."],
    mistakes: ["Brak rozejścia liny w dolnej pozycji"], regression: "prostowanie-na-wyciagu", progression: null,
    substitutions: ["prostowanie-na-wyciagu"], protocol: "3 × 15" },
  { slug: "reverse-grip-pushdown", name: "Prostowanie podchwytem", en: "Reverse-Grip Pushdown", pattern: "isolation",
    primary: ["triceps"], secondary: [], compound: false, equipment: ["Wyciąg górny"], laterality: "jednostronne",
    start: "Chwyt podchwytem, łokieć przy tułowiu.",
    steps: ["Wyprostuj ramię.", "Zatrzymaj w skurczu.", "Wróć powoli."],
    mistakes: ["Rotowanie nadgarstka"], regression: "prostowanie-na-wyciagu", progression: null, substitutions: ["prostowanie-jednoracz"], protocol: "3 × 15 na stronę" },
  { slug: "overhead-cable-extension", name: "Prostowanie nad głowę na wyciągu", en: "Overhead Cable Extension", pattern: "isolation",
    primary: ["triceps"], secondary: ["rectusAbdominis"], compound: false, equipment: ["Brama kablowa"],
    start: "Stoisz tyłem do wyciągu, lina nad głową, łokcie przy uszach.",
    steps: ["Utrzymaj żebra ściągnięte.", "Wyprostuj ramiona nad głową.", "Wróć do rozciągnięcia bez rozchodzenia łokci."],
    mistakes: ["Przeprost lędźwi", "Rozchodzenie łokci"], regression: "prostowanie-na-wyciagu", progression: null,
    substitutions: ["prostowanie-hantla-zza-glowy"], protocol: "3 × 12" },
  { slug: "skull-crusher", name: "Wyciskanie francuskie leżąc", en: "Skull Crusher", pattern: "isolation",
    primary: ["triceps"], secondary: [], compound: false, equipment: ["Sztanga EZ", "Ławka płaska"],
    start: "Leżysz na ławce, ramiona pionowo, gryf nad czołem.",
    steps: ["Zginaj wyłącznie łokcie.", "Opuść gryf nad czoło lub za głowę.", "Wyprostuj ramiona bez przesuwania łokci."],
    mistakes: ["Przesuwanie ramion do tyłu i zamiana ruchu w pull-over"],
    precautions: ["Przy bólu łokci zmniejsz zakres albo przejdź na wyciąg."],
    regression: "prostowanie-na-wyciagu", progression: "jm-press", substitutions: ["tate-press"], protocol: "3 × 10" },
  { slug: "prostowanie-hantla-zza-glowy", name: "Prostowanie hantla zza głowy", en: "Overhead Dumbbell Extension", pattern: "isolation",
    primary: ["triceps"], secondary: [], compound: false, equipment: ["Hantel"], level: "Podstawowy",
    start: "Hantel trzymany oburącz nad głową, łokcie przy uszach.",
    steps: ["Opuść hantel za kark, zginając wyłącznie łokcie.", "Zatrzymaj w rozciągnięciu.", "Wyprostuj ramiona."],
    mistakes: ["Rozchodzenie łokci na boki"], regression: "prostowanie-na-wyciagu", progression: null,
    substitutions: ["overhead-cable-extension"], protocol: "3 × 12" },
  { slug: "prostowanie-jednoracz", name: "Prostowanie jednorącz nad głową", en: "Single-arm Overhead Extension", pattern: "isolation",
    primary: ["triceps"], secondary: [], compound: false, equipment: ["Hantel", "Brama kablowa"], laterality: "jednostronne",
    start: "Jedna ręka nad głową, łokieć przy uchu.",
    steps: ["Opuść ciężar za kark.", "Wyprostuj ramię.", "Zmień stronę po zakończeniu serii."],
    mistakes: ["Odchylanie tułowia w bok"], regression: null, progression: null, substitutions: ["prostowanie-hantla-zza-glowy"], protocol: "3 × 12 na stronę" },
  { slug: "jm-press", name: "JM press", en: "JM Press", pattern: "isolation",
    primary: ["triceps"], secondary: ["pectoralisMajor"], compound: false, equipment: ["Sztanga", "Ławka płaska"], level: "Zaawansowany", goals: ["Siła"],
    start: "Leżysz na ławce, chwyt na szerokość barków.",
    steps: ["Opuść sztangę w stronę szyi, zginając łokcie i cofając ramiona.", "Zatrzymaj tuż nad klatką.", "Wyciśnij łącząc prostowanie łokci z wyciskaniem."],
    mistakes: ["Zbyt duży ciężar przy nauce ruchu"], precautions: ["Wymaga asekuracji."],
    regression: "skull-crusher", progression: null, substitutions: ["wyciskanie-waskim-chwytem"], protocol: "4 × 8" },
  { slug: "dip-triceps", name: "Pompki na poręczach na triceps", en: "Triceps Dip", pattern: "vertical-push",
    primary: ["triceps"], secondary: ["pectoralisMajor", "anteriorDeltoid"], equipment: ["Poręcze"], level: "Zaawansowany",
    start: "Podpór na poręczach, tułów pionowo.",
    steps: ["Utrzymaj tułów pionowo.", "Zejdź do kąta prostego w łokciu.", "Wypchnij się do pełnego wyprostu."],
    mistakes: ["Pochylanie tułowia, co przenosi pracę na klatkę"], precautions: ["Przy dolegliwościach barku ogranicz głębokość."],
    regression: "pompki-na-lawce", progression: null, substitutions: ["maszyna-dip"], protocol: "3 × 10" },
  { slug: "maszyna-dip", name: "Dip na maszynie", en: "Machine Dip", pattern: "vertical-push",
    primary: ["triceps"], secondary: ["pectoralisMajor"], equipment: ["Maszyna dip"], level: "Podstawowy",
    start: "Siedzisz z uchwytami przy tułowiu.",
    steps: ["Wypchnij uchwyty w dół do wyprostu.", "Wróć powoli."],
    mistakes: ["Unoszenie barków"], regression: null, progression: "dip-triceps", substitutions: ["prostowanie-na-wyciagu"], protocol: "3 × 12" },
  { slug: "kickback", name: "Kickback z hantlem", en: "Triceps Kickback", pattern: "isolation",
    primary: ["triceps"], secondary: [], compound: false, equipment: ["Hantel"], level: "Podstawowy", laterality: "jednostronne",
    start: "Tułów w opadzie, ramię przy tułowiu, przedramię w dół.",
    steps: ["Unieś ramię do linii tułowia.", "Prostuj wyłącznie przedramię.", "Wróć powoli."],
    mistakes: ["Opuszczanie ramienia w trakcie serii"], regression: null, progression: null, substitutions: ["prostowanie-na-wyciagu"], protocol: "3 × 15 na stronę" },
  { slug: "tate-press", name: "Tate press", en: "Tate Press", pattern: "isolation",
    primary: ["triceps"], secondary: [], compound: false, equipment: ["Hantle", "Ławka płaska"],
    start: "Leżysz na ławce, hantle nad klatką, dłonie zwrócone do przodu.",
    steps: ["Opuść hantle łukiem do klatki, kierując łokcie na boki.", "Dotknij hantli klatki.", "Wyciśnij prostując ramiona."],
    mistakes: ["Zbyt duży ciężar"], regression: "skull-crusher", progression: null, substitutions: ["skull-crusher"], protocol: "3 × 12" },
  { slug: "pompki-diamentowe", name: "Pompki diamentowe", en: "Diamond Push-up", pattern: "horizontal-push",
    primary: ["triceps"], secondary: ["pectoralisMajor"], equipment: ["Masa ciała"],
    start: "Podpór przodem, dłonie blisko siebie pod klatką.",
    steps: ["Opuść tułów w jednej linii.", "Prowadź łokcie blisko żeber.", "Odepchnij się do wyprostu."],
    mistakes: ["Rozchodzenie łokci"], regression: "pompki-waskie", progression: null, substitutions: ["wyciskanie-waskim-chwytem"],
    parameters: ["serie", "powtorzenia", "tempo", "przerwa"], protocol: "3 × 10–15" },
  { slug: "pompki-na-lawce", name: "Pompki na ławce", en: "Bench Dip", pattern: "vertical-push",
    primary: ["triceps"], secondary: ["anteriorDeltoid"], equipment: ["Ławka płaska"], level: "Podstawowy",
    start: "Dłonie na ławce za sobą, nogi wyprostowane przed sobą.",
    steps: ["Opuszczaj biodra blisko ławki.", "Zejdź do kąta prostego.", "Wypchnij się do wyprostu."],
    mistakes: ["Zbyt głębokie schodzenie drażniące bark"], regression: null, progression: "dip-triceps",
    substitutions: ["maszyna-dip"], parameters: ["serie", "powtorzenia", "tempo", "przerwa"], protocol: "3 × 12" },
];

const forearmDrafts: Draft[] = [
  { slug: "wrist-curl", name: "Uginanie nadgarstków", en: "Wrist Curl", pattern: "isolation",
    primary: ["forearms"], secondary: [], compound: false, equipment: ["Sztanga EZ", "Hantle"], level: "Podstawowy",
    start: "Przedramiona oparte o uda lub ławkę, dłonie zwrócone w górę.",
    steps: ["Opuść ciężar, otwierając dłonie.", "Zwiń nadgarstki do pełnego zgięcia.", "Wróć powoli."],
    mistakes: ["Unoszenie przedramion"], regression: null, progression: null, substitutions: ["wrist-roller"], protocol: "3 × 15–20" },
  { slug: "reverse-wrist-curl", name: "Prostowanie nadgarstków", en: "Reverse Wrist Curl", pattern: "isolation",
    primary: ["forearms"], secondary: [], compound: false, equipment: ["Sztanga EZ"], level: "Podstawowy",
    start: "Przedramiona oparte, dłonie zwrócone w dół.",
    steps: ["Unieś grzbiety dłoni.", "Zatrzymaj w skurczu.", "Opuść powoli."],
    mistakes: ["Zbyt duży ciężar"], regression: null, progression: null, substitutions: ["reverse-curl"], protocol: "3 × 15" },
  { slug: "wrist-roller", name: "Rolowanie liny", en: "Wrist Roller", pattern: "isolation",
    primary: ["forearms"], secondary: ["anteriorDeltoid"], compound: false, equipment: ["Maszyna plate-loaded"],
    start: "Ramiona wyciągnięte przed sobą, wałek z linką i obciążeniem.",
    steps: ["Nawijaj linkę naprzemiennymi ruchami nadgarstków.", "Opuść ciężar w kontrolowany sposób.", "Utrzymuj ramiona w linii barków."],
    mistakes: ["Opuszczanie ramion w trakcie serii"], regression: null, progression: null, substitutions: ["wrist-curl"],
    parameters: ["serie", "powtorzenia", "ciezar", "czas", "przerwa"], protocol: "3 × 2 przejścia" },
  { slug: "plate-pinch", name: "Ściskanie talerzy", en: "Plate Pinch", pattern: "carry",
    primary: ["forearms"], secondary: [], compound: false, equipment: ["Talerze"], level: "Podstawowy",
    start: "Dwa talerze złączone gładkimi stronami, chwyt palcami.",
    steps: ["Ściśnij talerze palcami.", "Utrzymaj chwyt przez zadany czas.", "Odłóż kontrolowanie."],
    mistakes: ["Upuszczanie talerzy na stopy"], precautions: ["Ćwicz nad matą."],
    regression: null, progression: null, substitutions: ["dead-hang"], parameters: ["serie", "czas", "ciezar", "przerwa"], protocol: "3 × 30 s" },
  { slug: "dead-hang", name: "Zwis na drążku", en: "Dead Hang", pattern: "carry",
    primary: ["forearms"], secondary: ["latissimusDorsi", "anteriorDeltoid"], compound: false, equipment: ["Drążek"], level: "Podstawowy", goals: ["Sprawność", "Mobilność"],
    start: "Zwis na drążku, barki aktywne, ciało rozluźnione.",
    steps: ["Chwyć drążek na szerokość barków.", "Utrzymaj aktywne barki.", "Wisz przez zadany czas, oddychając spokojnie."],
    mistakes: ["Całkowite rozluźnienie barków"], regression: null, progression: "towel-hang", substitutions: ["plate-pinch"],
    parameters: ["serie", "czas", "przerwa"], protocol: "3 × 30–45 s" },
  { slug: "towel-hang", name: "Zwis na ręczniku", en: "Towel Hang", pattern: "carry",
    primary: ["forearms"], secondary: [], compound: false, equipment: ["Drążek"], level: "Zaawansowany",
    start: "Ręczniki przerzucone przez drążek, chwyt za końce.",
    steps: ["Chwyć końce ręczników.", "Utrzymaj zwis mimo utrudnionego chwytu.", "Zejdź kontrolowanie."],
    mistakes: ["Zbyt długi czas kosztem techniki"], regression: "dead-hang", progression: null, substitutions: ["dead-hang"],
    parameters: ["serie", "czas", "przerwa"], protocol: "3 × 20 s" },
];

export const bicepsExercises = buildCategory("Biceps", bicepsDrafts);
export const tricepsExercises = buildCategory("Triceps", tricepsDrafts);
export const forearmExercises = buildCategory("Przedramiona", forearmDrafts);
