import { buildCategory, type Draft } from "@/lib/exercises/catalog/helpers";

const drafts: Draft[] = [
  { slug: "martwy-ciag-klasyczny", name: "Martwy ciąg klasyczny", en: "Conventional Deadlift", pattern: "hinge",
    primary: ["erectorSpinae", "gluteusMaximus"], secondary: ["hamstrings", "latissimusDorsi", "forearms"],
    equipment: ["Sztanga"], level: "Zaawansowany", goals: ["Siła", "Masa mięśniowa"], aliases: ["deadlift", "martwy"],
    start: "Sztanga nad środkiem stopy, stopy na szerokość bioder, chwyt tuż za nogami, plecy neutralne.",
    steps: ["Napnij grzbiet i wypełnij brzuch powietrzem.", "Wypchnij podłoże nogami, prowadząc sztangę blisko goleni.", "Domknij ruch wyprostem bioder, bez odchylania tułowia do tyłu.", "Odłóż ciężar zawiasem biodrowym, nie przysiadem."],
    breathing: "Wdech przed oderwaniem ciężaru, napięcie utrzymane przez całe powtórzenie, wydech po jego zakończeniu.",
    mistakes: ["Oddalanie sztangi od nóg", "Zaokrąglanie odcinka piersiowego i lędźwiowego", "Szarpanie startu"],
    cues: ["Wypchnij podłogę zamiast ciągnąć sztangę"], precautions: ["Przy przebytych urazach kręgosłupa zacznij od rack pull albo martwego ciągu z trap barem."],
    regression: "rack-pull", progression: null, substitutions: ["martwy-ciag-sumo", "rack-pull", "rumunski-martwy-ciag"], protocol: "4 × 3–5" },
  { slug: "martwy-ciag-sumo", name: "Martwy ciąg sumo", en: "Sumo Deadlift", pattern: "hinge",
    primary: ["gluteusMaximus", "quadriceps"], secondary: ["adductors", "erectorSpinae", "trapezius"],
    equipment: ["Sztanga"], level: "Zaawansowany", goals: ["Siła"],
    start: "Stopy szeroko, palce na zewnątrz, chwyt wewnątrz kolan, klatka wysoko.",
    steps: ["Ustaw biodra niżej niż w wersji klasycznej.", "Rozepchnij kolana na boki i napnij grzbiet.", "Wypchnij podłoże, prowadząc sztangę pionowo.", "Domknij biodra na końcu ruchu."],
    mistakes: ["Zbyt wysokie biodra na starcie", "Zapadanie kolan do środka"],
    regression: "martwy-ciag-klasyczny", progression: null, substitutions: ["martwy-ciag-klasyczny", "przysiad-sumo"], protocol: "4 × 3–5" },
  { slug: "rack-pull", name: "Rack pull", en: "Rack Pull", pattern: "hinge",
    primary: ["erectorSpinae", "trapezius"], secondary: ["gluteusMaximus", "forearms"],
    equipment: ["Sztanga", "Klatka treningowa"], goals: ["Siła"],
    start: "Sztanga oparta na pinach na wysokości kolan lub nieco niżej.",
    steps: ["Ustaw piny na wybranej wysokości.", "Napnij grzbiet i oderwij sztangę z pinów.", "Domknij biodra i wróć kontrolowanie."],
    mistakes: ["Odbijanie sztangi od pinów", "Praca samym grzbietem bez udziału bioder"],
    regression: "rumunski-martwy-ciag", progression: "martwy-ciag-klasyczny", substitutions: ["martwy-ciag-klasyczny"], protocol: "4 × 5" },
  { slug: "podciaganie-nachwytem", name: "Podciąganie nachwytem", en: "Pull-up", pattern: "vertical-pull",
    primary: ["latissimusDorsi"], secondary: ["biceps", "forearms", "trapezius"],
    equipment: ["Drążek"], level: "Zaawansowany", goals: ["Siła", "Sprawność"], aliases: ["pullup", "podciąganie"],
    start: "Zwis na drążku, chwyt nachwytem szerszy niż barki, barki aktywne.",
    steps: ["Rozpocznij ruch ściągnięciem łopatek w dół.", "Prowadź klatkę w stronę drążka, łokcie w dół.", "Zejdź do pełnego zwisu pod kontrolą."],
    breathing: "Wydech przy podciąganiu, wdech przy schodzeniu.",
    mistakes: ["Kołysanie tułowiem", "Skracanie zakresu w dolnej fazie", "Wysuwanie głowy do przodu"],
    regression: "podciaganie-z-guma", progression: "podciaganie-z-obciazeniem",
    substitutions: ["sciaganie-drazka-szeroko", "podciaganie-podchwytem"], parameters: ["serie", "powtorzenia", "ciezar", "tempo", "przerwa"], protocol: "4 × maks" },
  { slug: "podciaganie-podchwytem", name: "Podciąganie podchwytem", en: "Chin-up", pattern: "vertical-pull",
    primary: ["latissimusDorsi", "biceps"], secondary: ["forearms"], equipment: ["Drążek"],
    start: "Zwis, chwyt podchwytem na szerokość barków.",
    steps: ["Ściągnij łopatki.", "Podciągnij się, prowadząc łokcie wzdłuż tułowia.", "Zejdź do pełnego zwisu."],
    mistakes: ["Zatrzymywanie ruchu w połowie zakresu"],
    regression: "podciaganie-z-guma", progression: "podciaganie-z-obciazeniem", substitutions: ["podciaganie-nachwytem", "sciaganie-drazka-szeroko"], protocol: "4 × 6–10" },
  { slug: "podciaganie-neutralne", name: "Podciąganie chwytem neutralnym", en: "Neutral-Grip Pull-up", pattern: "vertical-pull",
    primary: ["latissimusDorsi"], secondary: ["biceps"], equipment: ["Drążek"],
    start: "Zwis na uchwytach równoległych, dłonie zwrócone do siebie.",
    steps: ["Ściągnij łopatki.", "Podciągnij się do wysokości klatki.", "Zejdź kontrolowanie."],
    mistakes: ["Bujanie ciałem"], precautions: ["Chwyt neutralny bywa lepiej tolerowany przy dolegliwościach barku i łokcia."],
    regression: "podciaganie-z-guma", progression: "podciaganie-z-obciazeniem", substitutions: ["podciaganie-podchwytem"], protocol: "4 × 8" },
  { slug: "podciaganie-z-guma", name: "Podciąganie z gumą", en: "Band-Assisted Pull-up", pattern: "vertical-pull",
    primary: ["latissimusDorsi"], secondary: ["biceps"], equipment: ["Drążek", "Guma oporowa"], level: "Podstawowy", goals: ["Technika", "Sprawność"],
    start: "Guma zaczepiona o drążek, stopa lub kolano w pętli.",
    steps: ["Dobierz gumę tak, aby wykonać od sześciu do dziesięciu powtórzeń.", "Podciągnij się w pełnym zakresie.", "Zejdź powoli."],
    mistakes: ["Zbyt mocna guma, która wyręcza mięśnie"],
    regression: null, progression: "podciaganie-nachwytem", substitutions: ["sciaganie-drazka-szeroko"], protocol: "3 × 8–10" },
  { slug: "podciaganie-z-obciazeniem", name: "Podciąganie z obciążeniem", en: "Weighted Pull-up", pattern: "vertical-pull",
    primary: ["latissimusDorsi"], secondary: ["biceps"], equipment: ["Drążek", "Talerze"], level: "Zaawansowany", goals: ["Siła"],
    start: "Obciążenie na pasie lub między stopami, zwis na drążku.",
    steps: ["Podciągnij się w pełnym zakresie mimo obciążenia.", "Zejdź kontrolowanie, nie rozluźniając barków."],
    mistakes: ["Skracanie zakresu pod ciężarem"], precautions: ["Zacznij od małego obciążenia, żeby nie przeciążyć łokci."],
    regression: "podciaganie-nachwytem", progression: null, substitutions: ["sciaganie-drazka-szeroko"], protocol: "4 × 5" },
  { slug: "sciaganie-drazka-szeroko", name: "Ściąganie drążka szerokim chwytem", en: "Wide-Grip Lat Pulldown", pattern: "vertical-pull",
    primary: ["latissimusDorsi"], secondary: ["biceps", "trapezius"], equipment: ["Lat pulldown"], level: "Podstawowy",
    aliases: ["lat pulldown", "wyciąg górny"],
    start: "Siedzisz z udami pod wałkami, chwyt szerszy niż barki.",
    steps: ["Utrzymaj wysoki tułów z minimalnym odchyleniem.", "Prowadź łokcie w dół do klatki.", "Wróć do pełnego rozciągnięcia bez unoszenia bioder."],
    mistakes: ["Nadmierne odchylanie tułowia", "Ciągnięcie samymi dłońmi"],
    regression: null, progression: "podciaganie-nachwytem", substitutions: ["podciaganie-nachwytem", "sciaganie-drazka-jednoracz"],
    parameters: ["serie", "powtorzenia", "ciezar", "tempo", "przerwa", "chwyt"], protocol: "3 × 10–12" },
  { slug: "sciaganie-drazka-jednoracz", name: "Ściąganie wyciągu jednorącz", en: "Single-arm Lat Pulldown", pattern: "vertical-pull",
    primary: ["latissimusDorsi"], secondary: ["biceps"], equipment: ["Lat pulldown"], laterality: "jednostronne",
    start: "Siedzisz lub klęczysz, uchwyt jednorącz nad głową.",
    steps: ["Ściągnij łopatkę w dół.", "Przyciągnij uchwyt do boku klatki.", "Wróć do pełnego rozciągnięcia."],
    mistakes: ["Rotowanie tułowia za ciężarem"],
    regression: "sciaganie-drazka-szeroko", progression: null, substitutions: ["sciaganie-drazka-szeroko"], protocol: "3 × 12 na stronę" },
  { slug: "przyciaganie-prostymi-rekami", name: "Przyciąganie wyciągu prostymi rękami", en: "Straight-Arm Pulldown", pattern: "isolation",
    primary: ["latissimusDorsi"], secondary: ["triceps", "rectusAbdominis"], compound: false, equipment: ["Wyciąg górny"],
    start: "Stoisz przodem do wyciągu, ramiona wyprostowane, lekkie pochylenie tułowia.",
    steps: ["Utrzymaj stały, lekki kąt w łokciach.", "Sprowadź drążek łukiem do ud.", "Wróć powoli do rozciągnięcia."],
    mistakes: ["Uginanie łokci i zamiana ruchu w prostowanie tricepsa"],
    regression: null, progression: null, substitutions: ["pullover-hantlem"], parameters: ["serie", "powtorzenia", "ciezar", "tempo", "przerwa"], protocol: "3 × 12–15" },
  { slug: "pullover-hantlem", name: "Pullover z hantlem", en: "Dumbbell Pull-over", pattern: "isolation",
    primary: ["latissimusDorsi"], secondary: ["pectoralisMajor", "triceps"], compound: false, equipment: ["Hantel", "Ławka płaska"],
    start: "Leżysz na ławce, hantel trzymany oburącz nad klatką.",
    steps: ["Opuść hantel łukiem za głowę przy lekko ugiętych łokciach.", "Zatrzymaj w rozciągnięciu bez odrywania lędźwi.", "Wróć nad klatkę."],
    mistakes: ["Przeprost odcinka lędźwiowego"], precautions: ["Przy ograniczonej ruchomości barku zmniejsz zakres."],
    regression: "przyciaganie-prostymi-rekami", progression: null, substitutions: ["przyciaganie-prostymi-rekami"], protocol: "3 × 12" },
  { slug: "wioslowanie-sztanga", name: "Wiosłowanie sztangą", en: "Barbell Row", pattern: "horizontal-pull",
    primary: ["latissimusDorsi", "trapezius"], secondary: ["biceps", "erectorSpinae"], equipment: ["Sztanga"],
    start: "Tułów w opadzie około 45 stopni, plecy neutralne, sztanga pod barkami.",
    steps: ["Napnij grzbiet i brzuch.", "Przyciągnij sztangę do dolnych żeber.", "Opuść ją kontrolowanie do pełnego rozciągnięcia."],
    mistakes: ["Prostowanie tułowia w trakcie ciągnięcia", "Zaokrąglanie pleców"],
    regression: "wioslowanie-hantlem", progression: "pendlay-row", substitutions: ["wioslowanie-hantlem", "t-bar-row"], protocol: "4 × 8" },
  { slug: "pendlay-row", name: "Pendlay row", en: "Pendlay Row", pattern: "horizontal-pull",
    primary: ["latissimusDorsi", "trapezius"], secondary: ["biceps"], equipment: ["Sztanga"], level: "Zaawansowany", goals: ["Siła"],
    start: "Tułów równolegle do podłoża, sztanga na ziemi przed każdym powtórzeniem.",
    steps: ["Z każdego powtórzenia startuj z podłogi.", "Przyciągnij sztangę do dolnych żeber, nie unosząc tułowia.", "Odłóż ją na podłogę i zresetuj pozycję."],
    mistakes: ["Unoszenie tułowia przy ciągnięciu"],
    regression: "wioslowanie-sztanga", progression: null, substitutions: ["wioslowanie-sztanga"], protocol: "5 × 5" },
  { slug: "yates-row", name: "Yates row", en: "Yates Row", pattern: "horizontal-pull",
    primary: ["latissimusDorsi"], secondary: ["biceps", "trapezius"], equipment: ["Sztanga"],
    start: "Tułów w opadzie około 60 stopni, chwyt podchwytem.",
    steps: ["Przyciągnij sztangę do dolnej części brzucha.", "Prowadź łokcie blisko tułowia.", "Opuść kontrolowanie."],
    mistakes: ["Zbyt duże odchylenie tułowia"], regression: "wioslowanie-hantlem", progression: null,
    substitutions: ["wioslowanie-sztanga"], protocol: "4 × 8–10" },
  { slug: "t-bar-row", name: "Wiosłowanie T-bar", en: "T-Bar Row", pattern: "horizontal-pull",
    primary: ["latissimusDorsi", "trapezius"], secondary: ["biceps"], equipment: ["Landmine", "Sztanga"],
    start: "Stoisz okrakiem nad gryfem, uchwyt pod klatką, tułów w opadzie.",
    steps: ["Utrzymaj neutralny kręgosłup.", "Przyciągnij uchwyt do brzucha.", "Opuść do pełnego rozciągnięcia."],
    mistakes: ["Zaokrąglanie pleców przy zbyt dużym ciężarze"], regression: "wioslowanie-siedzac", progression: null,
    substitutions: ["wioslowanie-sztanga", "wioslowanie-siedzac"], protocol: "4 × 10" },
  { slug: "seal-row", name: "Seal row", en: "Seal Row", pattern: "horizontal-pull",
    primary: ["latissimusDorsi", "trapezius"], secondary: ["biceps"], equipment: ["Sztanga", "Ławka płaska"],
    start: "Leżysz twarzą w dół na wysokiej ławce, sztanga pod ławką.",
    steps: ["Przyciągnij sztangę do ławki.", "Ściągnij łopatki na końcu ruchu.", "Opuść do pełnego rozciągnięcia."],
    mistakes: ["Odrywanie klatki od ławki"], cues: ["Podparcie usuwa udział bioder i grzbietu"],
    regression: "wioslowanie-siedzac", progression: null, substitutions: ["wioslowanie-podparte"], protocol: "3 × 12" },
  { slug: "wioslowanie-podparte", name: "Wiosłowanie w podparciu", en: "Chest-Supported Row", pattern: "horizontal-pull",
    primary: ["latissimusDorsi", "trapezius"], secondary: ["biceps", "posteriorDeltoid"], equipment: ["Hantle", "Ławka regulowana"], level: "Podstawowy",
    start: "Klatka oparta o ławkę ustawioną na 30–45 stopni, hantle w dłoniach.",
    steps: ["Przyciągnij hantle do bioder.", "Ściągnij łopatki na końcu ruchu.", "Opuść powoli."],
    mistakes: ["Odrywanie klatki od oparcia"], regression: null, progression: "wioslowanie-sztanga",
    substitutions: ["seal-row", "wioslowanie-siedzac"], protocol: "3 × 12" },
  { slug: "wioslowanie-hantlem", name: "Wiosłowanie hantlem jednorącz", en: "One-arm Dumbbell Row", pattern: "horizontal-pull",
    primary: ["latissimusDorsi"], secondary: ["biceps", "forearms"], equipment: ["Hantel", "Ławka płaska"], level: "Podstawowy", laterality: "jednostronne",
    start: "Kolano i dłoń na ławce, plecy równolegle do podłoża, hantel w dłoni.",
    steps: ["Utrzymaj biodra nieruchomo.", "Prowadź łokieć w kierunku biodra.", "Opuść hantel do pełnego rozciągnięcia."],
    mistakes: ["Rotowanie tułowia na końcu ruchu"], regression: null, progression: "wioslowanie-sztanga",
    substitutions: ["wioslowanie-podparte"], parameters: ["serie", "powtorzenia", "ciezar", "strona", "tempo", "przerwa"], protocol: "3 × 10 na stronę" },
  { slug: "meadows-row", name: "Meadows row", en: "Meadows Row", pattern: "horizontal-pull",
    primary: ["latissimusDorsi"], secondary: ["biceps", "posteriorDeltoid"], equipment: ["Landmine", "Sztanga"], laterality: "jednostronne", level: "Zaawansowany",
    start: "Stoisz bokiem do landmine, chwyt za koniec gryfu, tułów w opadzie.",
    steps: ["Oprzyj wolną rękę o kolano.", "Przyciągnij gryf do biodra.", "Opuść do pełnego rozciągnięcia."],
    mistakes: ["Rotowanie tułowia"], regression: "wioslowanie-hantlem", progression: null,
    substitutions: ["wioslowanie-hantlem"], protocol: "3 × 10 na stronę" },
  { slug: "landmine-row", name: "Wiosłowanie landmine", en: "Landmine Row", pattern: "horizontal-pull",
    primary: ["latissimusDorsi", "trapezius"], secondary: ["biceps"], equipment: ["Landmine", "Sztanga"],
    start: "Stoisz okrakiem nad gryfem, uchwyt oburącz, tułów w opadzie.",
    steps: ["Przyciągnij gryf do klatki.", "Ściągnij łopatki.", "Opuść kontrolowanie."],
    mistakes: ["Prostowanie tułowia"], regression: "wioslowanie-siedzac", progression: null,
    substitutions: ["t-bar-row"], protocol: "4 × 10" },
  { slug: "wioslowanie-siedzac", name: "Wiosłowanie na wyciągu siedząc", en: "Seated Cable Row", pattern: "horizontal-pull",
    primary: ["latissimusDorsi", "trapezius"], secondary: ["biceps", "posteriorDeltoid"], equipment: ["Seated row"], level: "Podstawowy",
    start: "Siedzisz z lekko ugiętymi kolanami, tułów wysoki, uchwyt w dłoniach.",
    steps: ["Zachowaj pionowy tułów.", "Przyciągnij uchwyt do brzucha, cofając łopatki.", "Wróć bez zaokrąglania pleców."],
    mistakes: ["Kołysanie tułowiem zamiast pracy łopatek"], regression: null, progression: "wioslowanie-sztanga",
    substitutions: ["maszyna-low-row", "wioslowanie-podparte"], parameters: ["serie", "powtorzenia", "ciezar", "tempo", "przerwa", "chwyt"], protocol: "3 × 12" },
  { slug: "maszyna-high-row", name: "Wiosłowanie górne na maszynie", en: "Machine High Row", pattern: "horizontal-pull",
    primary: ["latissimusDorsi"], secondary: ["posteriorDeltoid", "biceps"], equipment: ["Maszyna plate-loaded"], level: "Podstawowy",
    start: "Klatka przy oparciu, uchwyty powyżej linii barków.",
    steps: ["Przyciągnij uchwyty po skosie w dół do klatki.", "Zatrzymaj w skurczu.", "Wróć do rozciągnięcia."],
    mistakes: ["Odrywanie klatki od oparcia"], regression: null, progression: null,
    substitutions: ["sciaganie-drazka-szeroko"], protocol: "3 × 12" },
  { slug: "maszyna-low-row", name: "Wiosłowanie dolne na maszynie", en: "Machine Low Row", pattern: "horizontal-pull",
    primary: ["latissimusDorsi", "trapezius"], secondary: ["biceps"], equipment: ["Maszyna stosowa"], level: "Podstawowy",
    start: "Klatka przy oparciu, uchwyty na wysokości brzucha.",
    steps: ["Przyciągnij uchwyty do brzucha.", "Ściągnij łopatki.", "Wróć powoli."],
    mistakes: ["Szarpanie ciężaru"], regression: null, progression: null, substitutions: ["wioslowanie-siedzac"], protocol: "3 × 12" },
  { slug: "wioslowanie-smith", name: "Wiosłowanie na Smithie", en: "Smith Machine Row", pattern: "horizontal-pull",
    primary: ["latissimusDorsi"], secondary: ["biceps", "trapezius"], equipment: ["Smith machine"],
    start: "Tułów w opadzie, gryf na prowadnicy pod barkami.",
    steps: ["Odblokuj gryf.", "Przyciągnij go do brzucha.", "Opuść kontrolowanie i zablokuj po serii."],
    mistakes: ["Ustawienie stóp zbyt daleko od prowadnicy"], regression: "wioslowanie-siedzac", progression: "wioslowanie-sztanga",
    substitutions: ["wioslowanie-sztanga"], protocol: "3 × 10" },
  { slug: "inverted-row", name: "Wiosłowanie w zwisie poziomym", en: "Inverted Row", pattern: "horizontal-pull",
    primary: ["latissimusDorsi", "trapezius"], secondary: ["biceps", "rectusAbdominis"], equipment: ["Masa ciała", "Sztanga", "TRX"], level: "Podstawowy", goals: ["Sprawność", "Technika"],
    start: "Zwis pod gryfem lub TRX, ciało w jednej linii, pięty na podłożu.",
    steps: ["Napnij pośladki i brzuch.", "Przyciągnij klatkę do gryfu.", "Opuść się do pełnego wyprostu ramion."],
    mistakes: ["Opadanie bioder", "Skracanie zakresu"], regression: null, progression: "podciaganie-nachwytem",
    substitutions: ["wioslowanie-siedzac"], parameters: ["serie", "powtorzenia", "tempo", "przerwa"], protocol: "3 × 10–15" },
  { slug: "face-pull", name: "Face pull", en: "Face Pull", pattern: "horizontal-pull",
    primary: ["posteriorDeltoid"], secondary: ["trapezius", "latissimusDorsi"], equipment: ["Brama kablowa"], level: "Podstawowy", goals: ["Technika", "Sprawność"],
    start: "Wyciąg na wysokości twarzy, linka z liną w dłoniach, krok w tył dla napięcia.",
    steps: ["Przyciągnij linę do czoła, rozwodząc łokcie na boki.", "Zatrzymaj w rotacji zewnętrznej.", "Wróć powoli."],
    mistakes: ["Ciągnięcie zbyt nisko", "Praca samymi ramionami"], cues: ["Łokcie wyżej niż nadgarstki przez cały ruch"],
    regression: null, progression: null, substitutions: ["odwodzenie-w-opadzie"], parameters: ["serie", "powtorzenia", "ciezar", "tempo", "przerwa"], protocol: "3 × 15" },
  { slug: "shrug", name: "Unoszenie barków", en: "Barbell Shrug", pattern: "isolation",
    primary: ["trapezius"], secondary: ["forearms"], compound: false, equipment: ["Sztanga", "Hantle"], level: "Podstawowy",
    start: "Stoisz z ciężarem w opuszczonych ramionach, plecy neutralne.",
    steps: ["Unieś barki pionowo w stronę uszu.", "Zatrzymaj na moment w górze.", "Opuść powoli do pełnego rozciągnięcia."],
    mistakes: ["Rotowanie barkami w kółko", "Pomaganie sobie odchyleniem tułowia"],
    regression: null, progression: null, substitutions: ["farmer-walk"], parameters: ["serie", "powtorzenia", "ciezar", "tempo", "przerwa"], protocol: "3 × 12–15" },
];

export const backExercises = buildCategory("Plecy", drafts);
