import { buildCategory, type Draft } from "@/lib/exercises/catalog/helpers";

const drafts: Draft[] = [
  {
    slug: "wyciskanie-sztangi-lawka-plaska", name: "Wyciskanie sztangi na ławce poziomej", en: "Barbell Bench Press",
    pattern: "horizontal-push", primary: ["pectoralisMajor"], secondary: ["triceps", "anteriorDeltoid"],
    equipment: ["Sztanga", "Ławka płaska", "Stojaki"], level: "Średni", goals: ["Siła", "Masa mięśniowa"],
    aliases: ["bench", "bench press", "wyciskanie leżąc"],
    start: "Leżysz na ławce, stopy płasko na podłodze, łopatki ściągnięte i dociśnięte, sztanga nad stawami barkowymi.",
    steps: [
      "Zdejmij sztangę ze stojaków i ustaw ją nad środkiem klatki.",
      "Opuść sztangę do dolnej części klatki, prowadząc łokcie pod kątem około 45 stopni do tułowia.",
      "Dotknij klatki bez odbijania i zatrzymaj ruch na moment.",
      "Wyciśnij sztangę po lekkim łuku z powrotem nad stawy barkowe.",
    ],
    mistakes: ["Odrywanie łopatek i bioder od ławki", "Rozchodzenie łokci na boki do linii barków", "Odbijanie sztangi od klatki"],
    cues: ["Ściągnij łopatki i trzymaj je ściągnięte przez całą serię", "Wyobraź sobie, że rozpychasz ławkę na boki"],
    rom: "Od pełnego wyprostu ramion do kontaktu sztangi z klatką.",
    precautions: ["Przy bólu przedniej części barku zmniejsz zakres lub przejdź na wyciskanie hantli."],
    regression: "wyciskanie-hantli-lawka-plaska", progression: "wyciskanie-sztangi-pauza",
    substitutions: ["wyciskanie-hantli-lawka-plaska", "wyciskanie-maszyna-chest-press", "wyciskanie-smith-lawka-plaska"],
    protocol: "4 × 6–8",
  },
  {
    slug: "wyciskanie-sztangi-skos-dodatni", name: "Wyciskanie sztangi na ławce dodatniej", en: "Incline Barbell Bench Press",
    pattern: "horizontal-push", primary: ["upperChest"], secondary: ["anteriorDeltoid", "triceps"],
    equipment: ["Sztanga", "Ławka regulowana", "Stojaki"],
    aliases: ["incline bench", "skos dodatni"],
    start: "Ławka ustawiona na 30 stopni, łopatki ściągnięte, sztanga nad obojczykami.",
    steps: [
      "Zdejmij sztangę i ustabilizuj ją nad górną częścią klatki.",
      "Opuszczaj sztangę do okolic obojczyków, trzymając nadgarstki nad łokciami.",
      "Zatrzymaj ruch przy klatce i wyciśnij po skosie w górę.",
    ],
    mistakes: ["Zbyt duży kąt ławki, który przenosi pracę na barki", "Opuszczanie sztangi zbyt nisko, do mostka"],
    cues: ["Trzydzieści stopni wystarczy — wyżej to już wyciskanie barków"],
    regression: "wyciskanie-hantli-skos-dodatni", progression: "wyciskanie-sztangi-lawka-plaska",
    substitutions: ["wyciskanie-hantli-skos-dodatni", "maszyna-incline-chest-press"],
    protocol: "4 × 8",
  },
  {
    slug: "wyciskanie-sztangi-skos-ujemny", name: "Wyciskanie sztangi na ławce ujemnej", en: "Decline Barbell Bench Press",
    pattern: "horizontal-push", primary: ["pectoralisMajor"], secondary: ["triceps"],
    equipment: ["Sztanga", "Ławka regulowana", "Stojaki"],
    start: "Ławka pochylona w dół, nogi zablokowane, łopatki ściągnięte.",
    steps: ["Zdejmij sztangę nad dolną częścią klatki.", "Opuść ją do dolnych żeber.", "Wyciśnij pionowo w górę."],
    mistakes: ["Wchodzenie i schodzenie z ławki bez asekuracji", "Zbyt szeroki chwyt"],
    precautions: ["Pozycja głową w dół nie jest wskazana przy nadciśnieniu i refluksie."],
    regression: "wyciskanie-hantli-lawka-plaska", progression: null,
    substitutions: ["pompki-na-porczach-klatka", "wyciskanie-maszyna-chest-press"],
    protocol: "3 × 8–10",
  },
  {
    slug: "wyciskanie-hantli-lawka-plaska", name: "Wyciskanie hantli na ławce poziomej", en: "Dumbbell Bench Press",
    pattern: "horizontal-push", primary: ["pectoralisMajor"], secondary: ["triceps", "anteriorDeltoid"],
    equipment: ["Hantle", "Ławka płaska"], level: "Podstawowy",
    aliases: ["dumbbell press", "wyciskanie hantli"],
    start: "Hantle na udach, kładziesz się kolejno wypychając je nad klatkę, łopatki ściągnięte.",
    steps: [
      "Ustaw hantle nad stawami barkowymi, dłonie zwrócone do siebie lub do przodu.",
      "Opuszczaj hantle do wysokości klatki, kontrolując tor ruchu.",
      "Wyciśnij je w górę, nie zderzając ich ze sobą.",
    ],
    mistakes: ["Zderzanie hantli u góry", "Zbyt głębokie schodzenie kosztem stabilności barku"],
    cues: ["Zatrzymaj hantle kilka centymetrów od siebie w górnej pozycji"],
    regression: "pompki-klasyczne", progression: "wyciskanie-sztangi-lawka-plaska",
    substitutions: ["wyciskanie-sztangi-lawka-plaska", "wyciskanie-maszyna-chest-press"],
    protocol: "3 × 8–12",
  },
  {
    slug: "wyciskanie-hantli-skos-dodatni", name: "Wyciskanie hantli na ławce dodatniej", en: "Incline Dumbbell Press",
    pattern: "horizontal-push", primary: ["upperChest"], secondary: ["anteriorDeltoid", "triceps"],
    equipment: ["Hantle", "Ławka regulowana"], level: "Podstawowy",
    start: "Ławka na 30 stopni, hantle nad górną częścią klatki.",
    steps: ["Opuszczaj hantle do wysokości obojczyków.", "Zatrzymaj się w rozciągnięciu bez bólu.", "Wyciśnij po skosie w górę."],
    mistakes: ["Unoszenie bioder z ławki", "Zbyt szybkie opuszczanie"],
    regression: "pompki-na-podwyzszeniu", progression: "wyciskanie-sztangi-skos-dodatni",
    substitutions: ["wyciskanie-sztangi-skos-dodatni", "maszyna-incline-chest-press"],
    protocol: "3 × 10",
  },
  {
    slug: "wyciskanie-hantli-neutralnie", name: "Wyciskanie hantli chwytem neutralnym", en: "Neutral-Grip Dumbbell Press",
    pattern: "horizontal-push", primary: ["pectoralisMajor"], secondary: ["triceps"],
    equipment: ["Hantle", "Ławka płaska"], level: "Podstawowy",
    aliases: ["chwyt młotkowy", "neutral grip press"],
    start: "Leżysz na ławce, dłonie zwrócone do siebie przez cały ruch.",
    steps: ["Opuszczaj hantle wzdłuż tułowia.", "Trzymaj łokcie blisko ciała.", "Wyciśnij nad klatkę."],
    mistakes: ["Rotowanie nadgarstków w trakcie ruchu"],
    precautions: ["Chwyt neutralny bywa lepiej tolerowany przy dolegliwościach barku."],
    regression: "pompki-klasyczne", progression: "wyciskanie-hantli-lawka-plaska",
    substitutions: ["wyciskanie-hantli-lawka-plaska", "floor-press"],
    protocol: "3 × 10–12",
  },
  {
    slug: "floor-press", name: "Wyciskanie leżąc na podłodze", en: "Floor Press",
    pattern: "horizontal-push", primary: ["pectoralisMajor"], secondary: ["triceps"],
    equipment: ["Sztanga", "Hantle"],
    start: "Leżysz na podłodze, kolana ugięte lub nogi wyprostowane, ramiona nad klatką.",
    steps: ["Opuszczaj ciężar, aż tricepsy dotkną podłogi.", "Zatrzymaj się na moment.", "Wyciśnij w górę bez odbijania od podłoża."],
    mistakes: ["Odbijanie łokci od podłogi", "Unoszenie bioder"],
    cues: ["Zatrzymanie na podłodze usuwa odbicie i uczy startu z martwego punktu"],
    regression: "wyciskanie-hantli-lawka-plaska", progression: "wyciskanie-sztangi-lawka-plaska",
    substitutions: ["pin-press", "wyciskanie-hantli-neutralnie"],
    protocol: "4 × 6",
  },
  {
    slug: "pin-press", name: "Wyciskanie z pinów", en: "Pin Press",
    pattern: "horizontal-push", primary: ["pectoralisMajor"], secondary: ["triceps"], level: "Zaawansowany",
    equipment: ["Sztanga", "Klatka treningowa", "Ławka płaska"], goals: ["Siła", "Technika"],
    start: "Sztanga oparta na pinach ustawionych na wysokości wybranego punktu ruchu.",
    steps: ["Ustaw piny tam, gdzie tracisz siłę.", "Wyciśnij sztangę z pinów bez rozpędu.", "Odłóż ją kontrolowanie na piny i zrób pauzę."],
    mistakes: ["Odbijanie sztangi od pinów", "Ustawienie pinów zbyt wysoko, przez co ćwiczenie traci sens"],
    precautions: ["Wymaga poprawnie ustawionej klatki treningowej."],
    regression: "floor-press", progression: null,
    substitutions: ["floor-press", "wyciskanie-sztangi-pauza"],
    protocol: "5 × 3",
  },
  {
    slug: "spoto-press", name: "Spoto press", en: "Spoto Press",
    pattern: "horizontal-push", primary: ["pectoralisMajor"], secondary: ["triceps"], level: "Zaawansowany",
    equipment: ["Sztanga", "Ławka płaska", "Stojaki"], goals: ["Siła", "Technika"],
    start: "Jak w wyciskaniu klasycznym, łopatki ściągnięte.",
    steps: ["Opuść sztangę do dwóch centymetrów nad klatką.", "Zatrzymaj ją tam na jedną do dwóch sekund.", "Wyciśnij bez dotykania klatki."],
    mistakes: ["Dotknięcie klatki, które niweczy cel ćwiczenia", "Utrata napięcia w pauzie"],
    regression: "wyciskanie-sztangi-lawka-plaska", progression: null,
    substitutions: ["wyciskanie-sztangi-pauza", "pin-press"],
    protocol: "4 × 5",
  },
  {
    slug: "wyciskanie-waskim-chwytem", name: "Wyciskanie wąskim chwytem", en: "Close-Grip Bench Press",
    pattern: "horizontal-push", primary: ["triceps"], secondary: ["pectoralisMajor", "anteriorDeltoid"],
    equipment: ["Sztanga", "Ławka płaska", "Stojaki"],
    start: "Chwyt na szerokość barków, łokcie blisko tułowia.",
    steps: ["Opuść sztangę do dolnej części klatki.", "Prowadź łokcie wzdłuż tułowia.", "Wyciśnij do pełnego wyprostu."],
    mistakes: ["Zbyt wąski chwyt obciążający nadgarstki", "Rozchodzenie łokci"],
    regression: "pompki-waskie", progression: "wyciskanie-sztangi-lawka-plaska",
    substitutions: ["pompki-diamentowe", "jm-press"],
    protocol: "4 × 8",
  },
  {
    slug: "wyciskanie-maszyna-chest-press", name: "Wyciskanie na maszynie", en: "Machine Chest Press",
    pattern: "horizontal-push", primary: ["pectoralisMajor"], secondary: ["triceps", "anteriorDeltoid"],
    equipment: ["Chest press"], level: "Podstawowy", goals: ["Masa mięśniowa", "Technika"],
    start: "Siedzisz z plecami przy oparciu, uchwyty na wysokości środka klatki.",
    steps: ["Ustaw siedzisko tak, aby uchwyty były na wysokości środka klatki.", "Wypchnij uchwyty do wyprostu bez blokowania łokci.", "Wróć kontrolowanie, nie uderzając stosu."],
    mistakes: ["Zbyt wysokie siedzisko", "Uderzanie ciężarem o stos"],
    regression: "pompki-na-podwyzszeniu", progression: "wyciskanie-hantli-lawka-plaska",
    substitutions: ["wyciskanie-hantli-lawka-plaska", "pec-deck"],
    protocol: "3 × 10–12",
  },
  {
    slug: "maszyna-incline-chest-press", name: "Wyciskanie skos na maszynie", en: "Incline Machine Press",
    pattern: "horizontal-push", primary: ["upperChest"], secondary: ["anteriorDeltoid", "triceps"],
    equipment: ["Chest press"], level: "Podstawowy",
    start: "Siedzisko ustawione tak, aby uchwyty znalazły się na wysokości obojczyków.",
    steps: ["Wypchnij uchwyty po skosie w górę.", "Zatrzymaj tuż przed pełnym wyprostem.", "Wróć powoli do rozciągnięcia."],
    mistakes: ["Odrywanie pleców od oparcia"],
    regression: "wyciskanie-maszyna-chest-press", progression: "wyciskanie-hantli-skos-dodatni",
    substitutions: ["wyciskanie-hantli-skos-dodatni"],
    protocol: "3 × 12",
  },
  {
    slug: "wyciskanie-smith-lawka-plaska", name: "Wyciskanie na Smithie", en: "Smith Machine Bench Press",
    pattern: "horizontal-push", primary: ["pectoralisMajor"], secondary: ["triceps"],
    equipment: ["Smith machine", "Ławka płaska"], level: "Podstawowy",
    start: "Ławka ustawiona tak, aby gryf opadał na dolną część klatki.",
    steps: ["Odblokuj gryf obrotem nadgarstków.", "Opuść go do klatki po prowadnicy.", "Wyciśnij i zablokuj po ostatnim powtórzeniu."],
    mistakes: ["Ustawienie ławki zbyt daleko, przez co gryf opada na szyję"],
    precautions: ["Sprawdź blokadę przed pierwszym powtórzeniem."],
    regression: "wyciskanie-maszyna-chest-press", progression: "wyciskanie-sztangi-lawka-plaska",
    substitutions: ["wyciskanie-sztangi-lawka-plaska"],
    protocol: "3 × 10",
  },
  {
    slug: "rozpietki-hantle", name: "Rozpiętki z hantlami", en: "Dumbbell Fly",
    pattern: "isolation", primary: ["pectoralisMajor"], secondary: [], compound: false,
    equipment: ["Hantle", "Ławka płaska"], goals: ["Masa mięśniowa"],
    start: "Leżysz na ławce, hantle nad klatką, łokcie lekko ugięte.",
    steps: ["Rozwiedź ramiona łukiem na boki, utrzymując stały kąt w łokciach.", "Zatrzymaj w rozciągnięciu bez bólu barku.", "Zbliż hantle nad klatką ruchem obejmowania."],
    mistakes: ["Prostowanie łokci i zamiana ruchu w wyciskanie", "Schodzenie zbyt nisko"],
    precautions: ["Przy dolegliwościach przedniej części barku ogranicz zakres."],
    regression: "pec-deck", progression: "rozpietki-brama",
    substitutions: ["rozpietki-brama", "pec-deck"],
    parameters: ["serie", "powtorzenia", "ciezar", "tempo", "przerwa"],
    protocol: "3 × 12–15",
  },
  {
    slug: "rozpietki-brama", name: "Rozpiętki na bramie", en: "Cable Fly",
    pattern: "isolation", primary: ["pectoralisMajor"], secondary: [], compound: false,
    equipment: ["Brama kablowa"], goals: ["Masa mięśniowa"],
    aliases: ["crossover", "brama"],
    start: "Stoisz w rozkroku między wyciągami, krok w przód dla napięcia linek.",
    steps: ["Ustaw wysokość bloczków zależnie od akcentu: górne dla dolnej części klatki, dolne dla górnej.", "Zbliż dłonie przed tułowiem po łuku.", "Wróć powoli do rozciągnięcia."],
    mistakes: ["Praca samymi ramionami bez napięcia klatki", "Zbyt duży ciężar i pomaganie tułowiem"],
    cues: ["Zmiana wysokości bloczków zmienia akcent w obrębie klatki"],
    regression: "pec-deck", progression: null,
    substitutions: ["rozpietki-hantle", "pec-deck"],
    parameters: ["serie", "powtorzenia", "ciezar", "tempo", "przerwa", "ustawienie"],
    protocol: "3 × 12–15",
  },
  {
    slug: "pec-deck", name: "Pec deck", en: "Pec Deck",
    pattern: "isolation", primary: ["pectoralisMajor"], secondary: [], compound: false,
    equipment: ["Pec deck"], level: "Podstawowy", goals: ["Masa mięśniowa", "Technika"],
    start: "Siedzisz z plecami przy oparciu, ramiona na wysokości barków.",
    steps: ["Zbliż uchwyty przed klatką.", "Zatrzymaj na moment w skurczu.", "Wróć powoli do rozciągnięcia."],
    mistakes: ["Odrywanie pleców od oparcia", "Zbyt szybki powrót"],
    regression: null, progression: "rozpietki-brama",
    substitutions: ["rozpietki-brama", "rozpietki-hantle"],
    parameters: ["serie", "powtorzenia", "ciezar", "tempo", "przerwa"],
    protocol: "3 × 12–15",
  },
  {
    slug: "pompki-klasyczne", name: "Pompki klasyczne", en: "Push-up",
    pattern: "horizontal-push", primary: ["pectoralisMajor"], secondary: ["triceps", "anteriorDeltoid", "rectusAbdominis"],
    equipment: ["Masa ciała"], level: "Podstawowy", goals: ["Sprawność", "Masa mięśniowa"],
    aliases: ["push up", "pompki"],
    start: "Podpór przodem, dłonie nieco szerzej niż barki, ciało w jednej linii.",
    steps: ["Napnij pośladki i brzuch.", "Opuść klatkę między dłonie, prowadząc łokcie pod kątem 45 stopni.", "Odepchnij podłoże do pełnego wyprostu."],
    breathing: "Wdech przy opuszczaniu, wydech przy odpychaniu.",
    mistakes: ["Opadanie bioder", "Wysuwanie głowy do przodu", "Skracanie zakresu"],
    cues: ["Ciało ma być sztywne jak deska od pięt po głowę"],
    regression: "pompki-na-podwyzszeniu", progression: "pompki-nogi-na-podwyzszeniu",
    substitutions: ["wyciskanie-maszyna-chest-press", "wyciskanie-hantli-lawka-plaska"],
    parameters: ["serie", "powtorzenia", "tempo", "przerwa", "czas"],
    protocol: "3 × maks",
  },
  {
    slug: "pompki-na-podwyzszeniu", name: "Pompki na podwyższeniu", en: "Incline Push-up",
    pattern: "horizontal-push", primary: ["pectoralisMajor"], secondary: ["triceps"],
    equipment: ["Masa ciała", "Ławka płaska"], level: "Podstawowy", goals: ["Technika", "Sprawność"],
    start: "Dłonie na ławce lub skrzyni, ciało w jednej linii.",
    steps: ["Im wyższe podparcie, tym łatwiej.", "Opuść klatkę do krawędzi podparcia.", "Odepchnij się do wyprostu."],
    mistakes: ["Opadanie bioder"],
    regression: null, progression: "pompki-klasyczne",
    substitutions: ["pompki-klasyczne"],
    parameters: ["serie", "powtorzenia", "tempo", "przerwa"],
    protocol: "3 × 12–15",
  },
  {
    slug: "pompki-nogi-na-podwyzszeniu", name: "Pompki z nogami na podwyższeniu", en: "Decline Push-up",
    pattern: "horizontal-push", primary: ["upperChest"], secondary: ["anteriorDeltoid", "triceps"],
    equipment: ["Masa ciała", "Ławka płaska"], goals: ["Sprawność", "Masa mięśniowa"],
    start: "Stopy na ławce, dłonie na podłodze, ciało w jednej linii.",
    steps: ["Napnij brzuch, żeby biodra nie opadały.", "Opuść klatkę do podłogi.", "Odepchnij się do wyprostu."],
    mistakes: ["Zapadanie w odcinku lędźwiowym"],
    regression: "pompki-klasyczne", progression: "pompki-z-obciazeniem",
    substitutions: ["wyciskanie-hantli-skos-dodatni"],
    parameters: ["serie", "powtorzenia", "tempo", "przerwa"],
    protocol: "3 × 10–15",
  },
  {
    slug: "pompki-waskie", name: "Pompki wąskie", en: "Close-Grip Push-up",
    pattern: "horizontal-push", primary: ["triceps"], secondary: ["pectoralisMajor"],
    equipment: ["Masa ciała"], level: "Podstawowy",
    start: "Podpór przodem, dłonie na szerokość barków lub węziej.",
    steps: ["Prowadź łokcie blisko tułowia.", "Opuść klatkę nisko.", "Odepchnij się do wyprostu."],
    mistakes: ["Rozchodzenie łokci na boki"],
    regression: "pompki-na-podwyzszeniu", progression: "pompki-diamentowe",
    substitutions: ["wyciskanie-waskim-chwytem"],
    parameters: ["serie", "powtorzenia", "tempo", "przerwa"],
    protocol: "3 × 10–15",
  },
  {
    slug: "pompki-z-obciazeniem", name: "Pompki z obciążeniem", en: "Weighted Push-up",
    pattern: "horizontal-push", primary: ["pectoralisMajor"], secondary: ["triceps"], level: "Zaawansowany",
    equipment: ["Masa ciała", "Talerze"],
    start: "Podpór przodem, talerz ułożony na środku pleców przez partnera.",
    steps: ["Poproś o ułożenie obciążenia między łopatkami.", "Wykonaj pompkę w pełnym zakresie.", "Utrzymuj sztywny tułów przez całą serię."],
    mistakes: ["Zbyt duże obciążenie kosztem zakresu"],
    precautions: ["Wymaga asekuracji przy zakładaniu i zdejmowaniu obciążenia."],
    regression: "pompki-klasyczne", progression: null,
    substitutions: ["wyciskanie-sztangi-lawka-plaska"],
    parameters: ["serie", "powtorzenia", "ciezar", "tempo", "przerwa"],
    protocol: "4 × 6–10",
  },
  {
    slug: "pompki-na-porczach-klatka", name: "Pompki na poręczach na klatkę", en: "Chest Dip",
    pattern: "horizontal-push", primary: ["pectoralisMajor"], secondary: ["triceps", "anteriorDeltoid"], level: "Zaawansowany",
    equipment: ["Poręcze"],
    aliases: ["dipy", "dips"],
    start: "Podpór na poręczach, ramiona wyprostowane, tułów lekko pochylony do przodu.",
    steps: ["Pochyl tułów, żeby przenieść pracę na klatkę.", "Zejdź do kąta prostego w łokciu.", "Wypchnij się w górę bez bujania."],
    mistakes: ["Zbyt głębokie schodzenie obciążające przedni akton barku", "Bujanie nogami"],
    precautions: ["Przy dolegliwościach barku ogranicz głębokość."],
    regression: "pompki-nogi-na-podwyzszeniu", progression: null,
    substitutions: ["wyciskanie-sztangi-skos-ujemny"],
    parameters: ["serie", "powtorzenia", "ciezar", "tempo", "przerwa"],
    protocol: "3 × 8–12",
  },
  {
    slug: "landmine-press-klatka", name: "Wyciskanie landmine", en: "Landmine Press",
    pattern: "horizontal-push", primary: ["upperChest"], secondary: ["anteriorDeltoid", "triceps", "rectusAbdominis"],
    equipment: ["Landmine", "Sztanga"], laterality: "jednostronne",
    start: "Klęk jednonóż lub stanie, koniec gryfu w dłoni na wysokości barku.",
    steps: ["Napnij brzuch i pośladki.", "Wypchnij gryf po skosie w górę i do przodu.", "Wróć kontrolowanie do barku."],
    mistakes: ["Rotowanie tułowia za ciężarem", "Przeprost lędźwi"],
    cues: ["Skos landmine bywa łagodniejszy dla barku niż wyciskanie nad głowę"],
    regression: "wyciskanie-maszyna-chest-press", progression: null,
    substitutions: ["wyciskanie-hantli-skos-dodatni"],
    parameters: ["serie", "powtorzenia", "ciezar", "strona", "tempo", "przerwa"],
    protocol: "3 × 10 na stronę",
  },
  {
    slug: "wyciskanie-jednoracz-brama", name: "Wyciskanie jednorącz na bramie", en: "Single-arm Cable Chest Press",
    pattern: "horizontal-push", primary: ["pectoralisMajor"], secondary: ["obliques", "triceps"], laterality: "jednostronne",
    equipment: ["Brama kablowa"],
    start: "Stoisz bokiem do wyciągu w wykroku, uchwyt na wysokości klatki.",
    steps: ["Wypchnij uchwyt przed siebie, nie pozwalając tułowiu się obrócić.", "Zatrzymaj w pełnym wyproście.", "Wróć powoli do rozciągnięcia."],
    mistakes: ["Rotacja tułowia pod wpływem oporu"],
    regression: "wyciskanie-maszyna-chest-press", progression: null,
    substitutions: ["landmine-press-klatka"],
    parameters: ["serie", "powtorzenia", "ciezar", "strona", "tempo", "przerwa"],
    protocol: "3 × 12 na stronę",
  },
];

export const chestExercises = buildCategory("Klatka", drafts);
