import { buildCategory, type Draft } from "@/lib/exercises/catalog/helpers";

const mobilityParams = ["serie", "powtorzenia", "czas", "strona", "przerwa"] as const;

const mobilityDrafts: Draft[] = [
  { slug: "mobilizacja-skokowego", name: "Mobilizacja stawu skokowego", en: "Ankle Mobilisation", pattern: "mobility",
    primary: ["calves"], secondary: [], compound: false, equipment: ["Mata"], level: "Podstawowy", goals: ["Mobilność"], laterality: "jednostronne",
    start: "Wykrok przy ścianie, stopa przednia kilka centymetrów od niej.",
    steps: ["Przesuwaj kolano nad palcami w stronę ściany.", "Nie odrywaj pięty od podłoża.", "Wróć i powtórz."],
    breathing: "Oddychaj swobodnie, nie wstrzymuj powietrza.",
    mistakes: ["Odrywanie pięty", "Skręcanie stopy do wewnątrz"], regression: null, progression: null,
    substitutions: ["rozciaganie-lydek"], parameters: [...mobilityParams], protocol: "2 × 10 na stronę" },
  { slug: "mobilizacja-bioder-90-90", name: "Mobilizacja bioder 90/90", en: "90/90 Hip Switch", pattern: "mobility",
    primary: ["adductors", "abductors"], secondary: ["gluteusMaximus"], compound: false, equipment: ["Mata"], level: "Podstawowy", goals: ["Mobilność"],
    start: "Siad z jedną nogą zgiętą przed sobą i drugą z boku, obie pod kątem prostym.",
    steps: ["Przenoś kolana z jednej strony na drugą.", "Nie wymuszaj zakresu.", "Utrzymuj wyprostowany tułów."],
    mistakes: ["Szybkie ruchy", "Dociskanie stawu przez ból"], regression: null, progression: "couch-stretch",
    substitutions: ["worlds-greatest-stretch"], parameters: [...mobilityParams], protocol: "2 × 10" },
  { slug: "couch-stretch", name: "Couch stretch", en: "Couch Stretch", pattern: "mobility",
    primary: ["quadriceps"], secondary: ["gluteusMaximus"], compound: false, equipment: ["Mata"], level: "Zaawansowany", laterality: "jednostronne", goals: ["Mobilność"],
    start: "Klęk jednonóż, goleń tylnej nogi oparta o ścianę.",
    steps: ["Podwiń miednicę.", "Napnij pośladek nogi zakrocznej.", "Utrzymaj pozycję, oddychając spokojnie."],
    mistakes: ["Wyginanie lędźwi dla większego zakresu"], precautions: ["Przy bólu kolana podłóż matę pod rzepkę."],
    regression: "rozciaganie-zginaczy-biodra", progression: null, substitutions: ["rozciaganie-zginaczy-biodra"],
    parameters: [...mobilityParams], protocol: "2 × 45 s na stronę" },
  { slug: "rozciaganie-zginaczy-biodra", name: "Rozciąganie zginaczy biodra", en: "Hip Flexor Stretch", pattern: "mobility",
    primary: ["quadriceps"], secondary: ["gluteusMaximus"], compound: false, equipment: ["Mata"], level: "Podstawowy", laterality: "jednostronne", goals: ["Mobilność"],
    start: "Klęk jednonóż, tułów wyprostowany.",
    steps: ["Podwiń miednicę pod siebie.", "Napnij pośladek nogi zakrocznej.", "Utrzymaj pozycję."],
    mistakes: ["Przeprost lędźwi zamiast wydłużenia biodra"], regression: null, progression: "couch-stretch",
    substitutions: ["worlds-greatest-stretch"], parameters: [...mobilityParams], protocol: "2 × 30 s na stronę" },
  { slug: "worlds-greatest-stretch", name: "World's greatest stretch", en: "World's Greatest Stretch", pattern: "mobility",
    primary: ["adductors"], secondary: ["erectorSpinae", "gluteusMaximus"], equipment: ["Mata"], laterality: "jednostronne", goals: ["Mobilność"],
    start: "Wykrok głęboki, dłonie po wewnętrznej stronie przedniej stopy.",
    steps: ["Oprzyj przedramię o podłoże przy przedniej stopie.", "Rotuj klatkę w stronę przedniej nogi, sięgając ręką w górę.", "Wróć i zmień stronę."],
    mistakes: ["Zapadanie bioder", "Utrata pozycji wykroku"], regression: "mobilizacja-bioder-90-90", progression: null,
    substitutions: ["rotacja-piersiowa"], parameters: [...mobilityParams], protocol: "2 × 6 na stronę" },
  { slug: "rotacja-piersiowa", name: "Rotacja odcinka piersiowego", en: "Thoracic Rotation", pattern: "mobility",
    primary: ["erectorSpinae"], secondary: ["posteriorDeltoid"], compound: false, equipment: ["Mata"], level: "Podstawowy", laterality: "jednostronne", goals: ["Mobilność"],
    start: "Klęk podparty, jedna dłoń na karku.",
    steps: ["Rotuj klatkę, prowadząc ruch łokciem w górę.", "Wróć, kierując łokieć pod tułów.", "Utrzymuj nieruchomą miednicę."],
    mistakes: ["Rotowanie z lędźwi zamiast z klatki"], regression: null, progression: null,
    substitutions: ["kot-krowa"], parameters: [...mobilityParams], protocol: "2 × 8 na stronę" },
  { slug: "kot-krowa", name: "Kot-krowa", en: "Cat-Cow", pattern: "mobility",
    primary: ["erectorSpinae"], secondary: ["rectusAbdominis"], compound: false, equipment: ["Mata"], level: "Podstawowy", goals: ["Mobilność", "Regeneracja"],
    start: "Klęk podparty, dłonie pod barkami, kolana pod biodrami.",
    steps: ["Na wydechu zaokrąglij kręgosłup.", "Na wdechu wydłuż go i otwórz klatkę.", "Zachowaj płynne tempo."],
    breathing: "Wydech przy zaokrąglaniu, wdech przy wydłużaniu.",
    mistakes: ["Ruch wyłącznie z odcinka lędźwiowego"], regression: null, progression: null,
    substitutions: ["rotacja-piersiowa"], parameters: [...mobilityParams], protocol: "2 × 10" },
  { slug: "shoulder-dislocates", name: "Krążenia barków z kijem", en: "Shoulder Dislocates", pattern: "mobility",
    primary: ["anteriorDeltoid"], secondary: ["pectoralisMajor"], compound: false, equipment: ["Kij", "Guma oporowa"], level: "Podstawowy", goals: ["Mobilność"],
    start: "Kij trzymany szeroko przed sobą.",
    steps: ["Prowadź kij łukiem nad głową do pleców.", "Nie wyginaj lędźwi.", "Wróć tą samą drogą."],
    mistakes: ["Zbyt wąski chwyt wymuszający kompensację"], regression: null, progression: null,
    substitutions: ["wall-slides"], parameters: [...mobilityParams], protocol: "2 × 10" },
  { slug: "wall-slides", name: "Ślizgi po ścianie", en: "Wall Slides", pattern: "mobility",
    primary: ["trapezius"], secondary: ["posteriorDeltoid"], compound: false, equipment: ["Masa ciała"], level: "Podstawowy", goals: ["Mobilność", "Technika"],
    start: "Plecy i ramiona przy ścianie, łokcie zgięte.",
    steps: ["Przesuwaj ramiona w górę, nie odrywając ich od ściany.", "Zatrzymaj w skrajnej pozycji.", "Wróć powoli."],
    mistakes: ["Odrywanie lędźwi od ściany"], regression: null, progression: "shoulder-dislocates",
    substitutions: ["band-pull-apart"], parameters: [...mobilityParams], protocol: "2 × 10" },
  { slug: "scapular-push-up", name: "Pompka łopatkowa", en: "Scapular Push-up", pattern: "mobility",
    primary: ["trapezius"], secondary: ["pectoralisMajor"], compound: false, equipment: ["Masa ciała"], level: "Podstawowy", goals: ["Technika"],
    start: "Podpór przodem, ramiona wyprostowane.",
    steps: ["Zsuń łopatki, nie zginając łokci.", "Rozsuń je maksymalnie.", "Powtarzaj płynnie."],
    mistakes: ["Zginanie łokci"], regression: null, progression: null, substitutions: ["scapular-pull-up"],
    parameters: [...mobilityParams], protocol: "2 × 12" },
  { slug: "scapular-pull-up", name: "Podciąganie łopatkowe", en: "Scapular Pull-up", pattern: "mobility",
    primary: ["trapezius"], secondary: ["latissimusDorsi"], compound: false, equipment: ["Drążek"], goals: ["Technika"],
    start: "Zwis na drążku, ramiona wyprostowane.",
    steps: ["Ściągnij łopatki w dół, nie zginając łokci.", "Zatrzymaj na moment.", "Wróć do pełnego zwisu."],
    mistakes: ["Zginanie łokci"], regression: "scapular-push-up", progression: null, substitutions: ["scapular-push-up"],
    parameters: [...mobilityParams], protocol: "3 × 8" },
  { slug: "band-pull-apart", name: "Rozciąganie gumy przed sobą", en: "Band Pull-Apart", pattern: "mobility",
    primary: ["posteriorDeltoid"], secondary: ["trapezius"], compound: false, equipment: ["Guma oporowa"], level: "Podstawowy", goals: ["Technika", "Sprawność"],
    start: "Guma trzymana przed sobą na wysokości barków.",
    steps: ["Rozciągnij gumę, rozwodząc ramiona.", "Zatrzymaj w skurczu.", "Wróć powoli."],
    mistakes: ["Unoszenie barków"], regression: null, progression: null, substitutions: ["face-pull"],
    parameters: [...mobilityParams], protocol: "3 × 15" },
  { slug: "rozciaganie-lydek", name: "Rozciąganie łydek o ścianę", en: "Wall Calf Stretch", pattern: "mobility",
    primary: ["calves"], secondary: [], compound: false, equipment: ["Masa ciała"], level: "Podstawowy", laterality: "jednostronne", goals: ["Mobilność", "Regeneracja"],
    start: "Śródstopie oparte o ścianę, pięta na podłodze.",
    steps: ["Przenieś ciężar do przodu.", "Utrzymaj piętę na podłodze.", "Wytrzymaj i zmień stronę."],
    mistakes: ["Odrywanie pięty"], regression: null, progression: null, substitutions: ["mobilizacja-skokowego"],
    parameters: [...mobilityParams], protocol: "2 × 30 s na stronę" },
  { slug: "aktywacja-posladkow", name: "Aktywacja pośladków z gumą", en: "Glute Activation", pattern: "mobility",
    primary: ["gluteusMaximus"], secondary: ["abductors"], equipment: ["Miniband", "Mata"], level: "Podstawowy", goals: ["Technika"],
    start: "Leżysz na plecach z gumą nad kolanami, stopy przy pośladkach.",
    steps: ["Unieś biodra do mostka.", "Rozepchnij kolana przeciw gumie.", "Opuść powoli."],
    mistakes: ["Praca lędźwiami"], regression: null, progression: "glute-bridge", substitutions: ["glute-bridge"],
    parameters: [...mobilityParams], protocol: "2 × 15" },
];

const functionalDrafts: Draft[] = [
  { slug: "farmer-walk", name: "Spacer farmera", en: "Farmer's Walk", pattern: "carry",
    primary: ["forearms", "trapezius"], secondary: ["rectusAbdominis", "gluteusMaximus"], equipment: ["Hantle", "Kettlebell"], level: "Podstawowy", goals: ["Siła", "Sprawność"],
    start: "Ciężary w obu dłoniach przy udach, tułów wyprostowany.",
    steps: ["Napnij brzuch i ustaw barki.", "Idź krótkimi, kontrolowanymi krokami.", "Odłóż ciężary zawiasem biodrowym."],
    breathing: "Oddychaj rytmicznie do kroku, nie wstrzymuj powietrza.",
    mistakes: ["Pochylanie tułowia", "Opadanie barków"], regression: null, progression: "suitcase-carry",
    substitutions: ["suitcase-carry"], parameters: ["serie", "dystans", "czas", "ciezar", "przerwa"], protocol: "4 × 30 m" },
  { slug: "suitcase-carry", name: "Przenoszenie walizkowe", en: "Suitcase Carry", pattern: "carry",
    primary: ["obliques"], secondary: ["forearms", "trapezius"], equipment: ["Hantel", "Kettlebell"], laterality: "jednostronne", goals: ["Sprawność"],
    start: "Ciężar w jednej dłoni, tułów wyprostowany.",
    steps: ["Napnij brzuch, żeby nie odchylać się w bok.", "Idź, utrzymując równe barki.", "Zmień stronę."],
    mistakes: ["Odchylanie tułowia w stronę przeciwną do ciężaru"], regression: "farmer-walk", progression: null,
    substitutions: ["farmer-walk"], parameters: ["serie", "dystans", "czas", "ciezar", "strona", "przerwa"], protocol: "3 × 20 m na stronę" },
  { slug: "overhead-carry", name: "Przenoszenie nad głową", en: "Overhead Carry", pattern: "carry",
    primary: ["anteriorDeltoid"], secondary: ["rectusAbdominis", "trapezius"], equipment: ["Kettlebell", "Hantle"], goals: ["Sprawność", "Technika"],
    start: "Ciężar wyciśnięty nad głową, łokieć wyprostowany.",
    steps: ["Ustaw ciężar nad barkiem.", "Idź, utrzymując żebra ściągnięte.", "Opuść ciężar kontrolowanie."],
    mistakes: ["Przeprost lędźwi"], precautions: ["Wymaga swobodnego wyprostu nad głową."],
    regression: "front-rack-carry", progression: null, substitutions: ["front-rack-carry"],
    parameters: ["serie", "dystans", "czas", "ciezar", "strona", "przerwa"], protocol: "3 × 20 m" },
  { slug: "front-rack-carry", name: "Przenoszenie przed sobą", en: "Front Rack Carry", pattern: "carry",
    primary: ["rectusAbdominis"], secondary: ["trapezius", "anteriorDeltoid"], equipment: ["Kettlebell"], level: "Podstawowy", goals: ["Sprawność"],
    start: "Kettlebelle w pozycji przedniej przy barkach.",
    steps: ["Ustaw łokcie blisko żeber.", "Idź z wyprostowanym tułowiem.", "Oddychaj równomiernie."],
    mistakes: ["Odchylanie tułowia do tyłu"], regression: "farmer-walk", progression: "overhead-carry",
    substitutions: ["farmer-walk"], parameters: ["serie", "dystans", "czas", "ciezar", "przerwa"], protocol: "3 × 30 m" },
  { slug: "sled-push", name: "Pchanie sań", en: "Sled Push", pattern: "locomotion",
    primary: ["quadriceps", "gluteusMaximus"], secondary: ["calves", "rectusAbdominis"], equipment: ["Sled"], goals: ["Wytrzymałość", "Sprawność"],
    start: "Dłonie na uchwytach, tułów pochylony, ramiona wyprostowane.",
    steps: ["Napnij brzuch i pochyl tułów.", "Wykonuj krótkie, mocne kroki.", "Utrzymuj stałe tempo do końca odcinka."],
    mistakes: ["Zbyt wysokie ustawienie tułowia", "Zbyt duże obciążenie kosztem tempa"],
    regression: null, progression: "prowler-sprint", substitutions: ["sled-pull"],
    parameters: ["serie", "dystans", "czas", "ciezar", "przerwa"], protocol: "6 × 20 m" },
  { slug: "sled-pull", name: "Ciągnięcie sań", en: "Sled Pull", pattern: "locomotion",
    primary: ["hamstrings", "gluteusMaximus"], secondary: ["latissimusDorsi"], equipment: ["Sled"], goals: ["Wytrzymałość"],
    start: "Uprząż lub uchwyty w dłoniach, tułów lekko odchylony.",
    steps: ["Idź do tyłu lub do przodu, ciągnąc sanie.", "Utrzymuj napięcie liny.", "Zachowaj równe tempo."],
    mistakes: ["Szarpanie liny"], regression: null, progression: null, substitutions: ["sled-push"],
    parameters: ["serie", "dystans", "czas", "ciezar", "przerwa"], protocol: "6 × 20 m" },
  { slug: "prowler-sprint", name: "Sprint z saniami", en: "Prowler Sprint", pattern: "locomotion",
    primary: ["quadriceps"], secondary: ["gluteusMaximus", "calves"], equipment: ["Sled"], level: "Zaawansowany", goals: ["Wytrzymałość"],
    start: "Lekkie obciążenie, pozycja startowa niska.",
    steps: ["Ruszaj dynamicznie.", "Utrzymaj maksymalne tempo na krótkim odcinku.", "Odpocznij do pełnej regeneracji."],
    mistakes: ["Zbyt duże obciążenie uniemożliwiające prędkość"], regression: "sled-push", progression: null,
    substitutions: ["sled-push"], parameters: ["serie", "dystans", "czas", "przerwa"], protocol: "8 × 15 m" },
  { slug: "battle-ropes", name: "Battle ropes", en: "Battle Ropes", pattern: "cardio",
    primary: ["anteriorDeltoid"], secondary: ["rectusAbdominis", "forearms"], equipment: ["Battle ropes"], goals: ["Wytrzymałość"],
    start: "Półprzysiad, końce lin w dłoniach.",
    steps: ["Wykonuj naprzemienne fale ramionami.", "Utrzymuj stabilny tułów.", "Zachowaj tempo przez cały interwał."],
    mistakes: ["Prostowanie nóg i praca samymi ramionami"], regression: null, progression: null,
    substitutions: ["air-bike"], parameters: ["serie", "czas", "przerwa", "rundy"], protocol: "8 × 20 s" },
  { slug: "medicine-ball-slam", name: "Rzut piłką o podłoże", en: "Medicine Ball Slam", pattern: "throw",
    primary: ["rectusAbdominis"], secondary: ["latissimusDorsi", "anteriorDeltoid"], equipment: ["Piłka lekarska"], goals: ["Sprawność", "Wytrzymałość"],
    start: "Stoisz z piłką nad głową.",
    steps: ["Unieś piłkę nad głowę z pełnym wyprostem.", "Rzuć ją dynamicznie o podłoże.", "Podnieś zawiasem biodrowym."],
    mistakes: ["Zaokrąglanie pleców przy podnoszeniu piłki"], regression: null, progression: null,
    substitutions: ["kettlebell-swing"], parameters: ["serie", "powtorzenia", "ciezar", "przerwa"], protocol: "5 × 8" },
  { slug: "rotational-ball-throw", name: "Rzut rotacyjny piłką", en: "Rotational Medicine Ball Throw", pattern: "throw",
    primary: ["obliques"], secondary: ["gluteusMaximus"], equipment: ["Piłka lekarska"], laterality: "jednostronne", goals: ["Sprawność"],
    start: "Stoisz bokiem do ściany, piłka przy biodrze.",
    steps: ["Zrotuj biodra i tułów.", "Rzuć piłkę w ścianę.", "Złap odbicie i powtórz."],
    mistakes: ["Rotowanie samym tułowiem bez udziału bioder"], regression: null, progression: null,
    substitutions: ["landmine-rotation"], parameters: ["serie", "powtorzenia", "ciezar", "strona", "przerwa"], protocol: "4 × 6 na stronę" },
  { slug: "box-jump", name: "Wskok na skrzynię", en: "Box Jump", pattern: "jump",
    primary: ["quadriceps", "gluteusMaximus"], secondary: ["calves"], equipment: ["Skrzynia plyometryczna"], goals: ["Sprawność"],
    start: "Stoisz przed skrzynią w lekkim rozkroku.",
    steps: ["Zamachnij ramionami i odbij się obiema nogami.", "Wyląduj miękko całą stopą na skrzyni.", "Zejdź krokiem, nie zeskakuj."],
    mistakes: ["Zeskakiwanie w dół, co obciąża ścięgna", "Lądowanie na palcach"],
    precautions: ["Dobierz wysokość, przy której lądujesz w półprzysiadzie, nie w pełnym przysiadzie."],
    regression: "broad-jump", progression: "depth-jump", substitutions: ["broad-jump"],
    parameters: ["serie", "powtorzenia", "przerwa"], protocol: "5 × 3" },
  { slug: "broad-jump", name: "Skok w dal z miejsca", en: "Broad Jump", pattern: "jump",
    primary: ["gluteusMaximus", "quadriceps"], secondary: ["calves"], equipment: ["Masa ciała"], goals: ["Sprawność"],
    start: "Stoisz w lekkim rozkroku.",
    steps: ["Zamachnij ramionami i odbij się w przód.", "Wyląduj miękko na obu stopach.", "Ustabilizuj pozycję przed kolejnym skokiem."],
    mistakes: ["Sztywne lądowanie"], regression: null, progression: "box-jump", substitutions: ["box-jump"],
    parameters: ["serie", "powtorzenia", "dystans", "przerwa"], protocol: "5 × 3" },
  { slug: "lateral-jump", name: "Skok boczny", en: "Lateral Jump", pattern: "jump",
    primary: ["abductors", "quadriceps"], secondary: ["calves"], equipment: ["Masa ciała"], laterality: "naprzemienne", goals: ["Sprawność"],
    start: "Stoisz na jednej lub obu nogach.",
    steps: ["Odbij się w bok.", "Wyląduj miękko, amortyzując biodrem i kolanem.", "Ustabilizuj i powtórz."],
    mistakes: ["Zapadanie kolana do środka przy lądowaniu"], regression: "broad-jump", progression: null,
    substitutions: ["broad-jump"], parameters: ["serie", "powtorzenia", "strona", "przerwa"], protocol: "4 × 6 na stronę" },
  { slug: "depth-jump", name: "Zeskok z wyskokiem", en: "Depth Jump", pattern: "jump",
    primary: ["quadriceps", "gluteusMaximus"], secondary: ["calves"], equipment: ["Skrzynia plyometryczna"], level: "Zaawansowany", goals: ["Sprawność"], supervision: true,
    start: "Stoisz na skrzyni o wysokości do czterdziestu centymetrów.",
    steps: ["Zejdź ze skrzyni, nie zeskakuj.", "Po kontakcie z podłożem odbij się natychmiast w górę.", "Wyląduj miękko."],
    mistakes: ["Zbyt długi kontakt z podłożem", "Zbyt wysoka skrzynia"],
    precautions: ["Wymaga przygotowania siłowego; nie dla początkujących."],
    regression: "box-jump", progression: null, substitutions: ["box-jump"], parameters: ["serie", "powtorzenia", "przerwa"], protocol: "5 × 3" },
  { slug: "kettlebell-clean", name: "Zarzut kettlebell", en: "Kettlebell Clean", pattern: "hinge",
    primary: ["gluteusMaximus"], secondary: ["trapezius", "forearms"], equipment: ["Kettlebell"], laterality: "jednostronne", goals: ["Sprawność", "Technika"],
    start: "Kettlebell na podłożu między stopami.",
    steps: ["Zahaczaj kettlebell zawiasem biodrowym.", "Prowadź go blisko ciała do pozycji przedniej.", "Zamortyzuj przyjęcie przedramieniem, nie nadgarstkiem."],
    mistakes: ["Uderzanie kettlebell o przedramię"], regression: "kettlebell-swing", progression: "kettlebell-snatch",
    substitutions: ["kettlebell-swing"], protocol: "5 × 5 na stronę" },
  { slug: "kettlebell-snatch", name: "Rwanie kettlebell", en: "Kettlebell Snatch", pattern: "hinge",
    primary: ["gluteusMaximus"], secondary: ["anteriorDeltoid", "trapezius"], equipment: ["Kettlebell"], level: "Zaawansowany", laterality: "jednostronne", supervision: true,
    start: "Kettlebell na podłożu przed sobą.",
    steps: ["Zahaczaj kettlebell zawiasem biodrowym.", "Wypchnij biodra i prowadź ciężar blisko ciała.", "Domknij ruch wyprostem ramienia nad głową."],
    mistakes: ["Uderzanie kettlebell o przedramię", "Ciągnięcie ramieniem zamiast pracy bioder"],
    precautions: ["Wymaga opanowanego swinga i zarzutu."],
    regression: "kettlebell-clean", progression: null, substitutions: ["kettlebell-clean"], protocol: "5 × 5 na stronę" },
  { slug: "bear-crawl", name: "Chód niedźwiedzia", en: "Bear Crawl", pattern: "locomotion",
    primary: ["rectusAbdominis"], secondary: ["anteriorDeltoid", "quadriceps"], equipment: ["Masa ciała"], level: "Podstawowy", goals: ["Sprawność"],
    start: "Podpór na dłoniach i palcach stóp, kolana kilka centymetrów nad podłożem.",
    steps: ["Przesuwaj naprzemiennie dłoń i przeciwną stopę.", "Utrzymuj biodra nisko i nieruchomo.", "Zachowaj równe tempo."],
    mistakes: ["Kołysanie biodrami"], regression: null, progression: null, substitutions: ["mountain-climber"],
    parameters: ["serie", "dystans", "czas", "przerwa"], protocol: "4 × 15 m" },
  { slug: "drabinka-koordynacyjna", name: "Drabinka koordynacyjna", en: "Agility Ladder", pattern: "locomotion",
    primary: ["calves"], secondary: ["quadriceps"], equipment: ["Drabinka koordynacyjna"], level: "Podstawowy", goals: ["Sprawność"],
    start: "Stoisz przed drabinką w lekkim napięciu.",
    steps: ["Wykonuj wybrany wzorzec kroków.", "Utrzymuj krótki kontakt z podłożem.", "Patrz przed siebie, nie na stopy."],
    mistakes: ["Zbyt długi kontakt z podłożem"], regression: null, progression: null, substitutions: ["skakanka"],
    parameters: ["serie", "czas", "rundy", "przerwa"], protocol: "6 × 20 s" },
];

const powerliftingDrafts: Draft[] = [
  { slug: "przysiad-tempo", name: "Przysiad w tempie", en: "Tempo Squat", pattern: "squat",
    primary: ["quadriceps"], secondary: ["gluteusMaximus"], equipment: ["Sztanga", "Stojaki"], level: "Zaawansowany", goals: ["Technika", "Siła"],
    start: "Jak w przysiadzie klasycznym.",
    steps: ["Schodź przez trzy do pięciu sekund.", "Zatrzymaj się na dole.", "Wstań w normalnym tempie."],
    mistakes: ["Przyspieszanie fazy schodzenia"], regression: "przysiad-high-bar", progression: null,
    substitutions: ["przysiad-z-pauza"], parameters: ["serie", "powtorzenia", "ciezar", "tempo", "rpe", "przerwa"], protocol: "4 × 4 tempo 4-1-1" },
  { slug: "wyciskanie-sztangi-pauza", name: "Wyciskanie z pauzą", en: "Paused Bench Press", pattern: "horizontal-push",
    primary: ["pectoralisMajor"], secondary: ["triceps"], equipment: ["Sztanga", "Ławka płaska", "Stojaki"], level: "Zaawansowany", goals: ["Siła", "Technika"],
    start: "Jak w wyciskaniu klasycznym.",
    steps: ["Opuść sztangę na klatkę.", "Zatrzymaj ją na jedną do trzech sekund bez rozluźnienia.", "Wyciśnij dynamicznie."],
    mistakes: ["Rozluźnienie w pauzie", "Zapadanie klatki"], regression: "wyciskanie-sztangi-lawka-plaska", progression: null,
    substitutions: ["spoto-press", "pin-press"], parameters: ["serie", "powtorzenia", "ciezar", "tempo", "rpe", "przerwa"], protocol: "5 × 3" },
  { slug: "deficit-deadlift", name: "Martwy ciąg z deficytu", en: "Deficit Deadlift", pattern: "hinge",
    primary: ["hamstrings", "erectorSpinae"], secondary: ["gluteusMaximus"], equipment: ["Sztanga", "Talerze"], level: "Zaawansowany", goals: ["Siła"],
    start: "Stoisz na podwyższeniu od dwóch do pięciu centymetrów.",
    steps: ["Ustaw się jak w martwym ciągu klasycznym.", "Oderwij sztangę z wydłużonego zakresu.", "Domknij biodra na górze."],
    mistakes: ["Zbyt wysoki deficyt kosztem pozycji pleców"], precautions: ["Wymaga opanowanego martwego ciągu klasycznego."],
    regression: "martwy-ciag-klasyczny", progression: null, substitutions: ["martwy-ciag-klasyczny"], protocol: "4 × 3" },
  { slug: "martwy-ciag-tempo", name: "Martwy ciąg w tempie", en: "Tempo Deadlift", pattern: "hinge",
    primary: ["erectorSpinae"], secondary: ["gluteusMaximus", "hamstrings"], equipment: ["Sztanga"], level: "Zaawansowany", goals: ["Technika"],
    start: "Jak w martwym ciągu klasycznym.",
    steps: ["Oderwij sztangę w normalnym tempie.", "Opuszczaj ją przez trzy do czterech sekund.", "Zresetuj pozycję przed kolejnym powtórzeniem."],
    mistakes: ["Utrata napięcia w fazie opuszczania"], regression: "martwy-ciag-klasyczny", progression: null,
    substitutions: ["rumunski-martwy-ciag"], parameters: ["serie", "powtorzenia", "ciezar", "tempo", "przerwa"], protocol: "4 × 3" },
  { slug: "board-press", name: "Wyciskanie z deską", en: "Board Press", pattern: "horizontal-push",
    primary: ["triceps"], secondary: ["pectoralisMajor"], equipment: ["Sztanga", "Ławka płaska"], level: "Zaawansowany", goals: ["Siła"],
    start: "Deska ułożona na klatce przez partnera.",
    steps: ["Opuść sztangę do deski.", "Zatrzymaj kontakt bez rozluźnienia.", "Wyciśnij dynamicznie."],
    mistakes: ["Odbijanie od deski"], precautions: ["Wymaga asekuracji."],
    regression: "pin-press", progression: null, substitutions: ["pin-press"], protocol: "5 × 3" },
];

const olympicDrafts: Draft[] = [
  { slug: "power-clean", name: "Zarzut do półprzysiadu", en: "Power Clean", pattern: "hinge",
    primary: ["gluteusMaximus", "trapezius"], secondary: ["quadriceps", "erectorSpinae"], equipment: ["Sztanga"], level: "Zaawansowany", goals: ["Siła", "Sprawność"], supervision: true,
    start: "Sztanga na podłożu, chwyt na szerokość barków, biodra wyżej niż w martwym ciągu.",
    steps: ["Oderwij sztangę, prowadząc ją blisko goleni.", "Wyprostuj dynamicznie biodra i kolana.", "Podciągnij łokcie i przyjmij sztangę na barkach w półprzysiadzie.", "Wstań do pozycji stojącej."],
    breathing: "Wdech przed startem, wydech po przyjęciu sztangi.",
    mistakes: ["Ciągnięcie ramionami zamiast wyprostu bioder", "Oddalanie sztangi od ciała"],
    precautions: ["Naucz się ruchu z pustym gryfem pod okiem trenera."],
    regression: "clean-pull", progression: "hang-clean", substitutions: ["kettlebell-clean"], protocol: "5 × 3" },
  { slug: "hang-clean", name: "Zarzut z wysokości", en: "Hang Clean", pattern: "hinge",
    primary: ["gluteusMaximus", "trapezius"], secondary: ["quadriceps"], equipment: ["Sztanga"], level: "Zaawansowany", supervision: true,
    start: "Sztanga w dłoniach na wysokości ud lub kolan.",
    steps: ["Cofnij biodra do pozycji zawiasu.", "Wyprostuj dynamicznie biodra.", "Przyjmij sztangę na barkach."],
    mistakes: ["Zbyt wczesne zginanie ramion"], regression: "power-clean", progression: null,
    substitutions: ["power-clean"], protocol: "5 × 3" },
  { slug: "clean-pull", name: "Ciąg zarzutowy", en: "Clean Pull", pattern: "hinge",
    primary: ["trapezius", "gluteusMaximus"], secondary: ["erectorSpinae"], equipment: ["Sztanga"], level: "Zaawansowany", goals: ["Siła", "Technika"],
    start: "Jak w zarzucie, chwyt na szerokość barków.",
    steps: ["Oderwij sztangę i przyspiesz w drugiej fazie ciągu.", "Domknij wyprost bioder i wspięcie na palce.", "Nie przechodź do przyjęcia."],
    mistakes: ["Zginanie ramion"], regression: "martwy-ciag-klasyczny", progression: "power-clean",
    substitutions: ["martwy-ciag-klasyczny"], protocol: "5 × 3" },
  { slug: "power-snatch", name: "Rwanie do półprzysiadu", en: "Power Snatch", pattern: "hinge",
    primary: ["gluteusMaximus", "trapezius"], secondary: ["anteriorDeltoid", "quadriceps"], equipment: ["Sztanga"], level: "Zaawansowany", supervision: true,
    start: "Sztanga na podłożu, chwyt bardzo szeroki.",
    steps: ["Oderwij sztangę blisko ciała.", "Wyprostuj dynamicznie biodra.", "Przyjmij sztangę nad głową w półprzysiadzie.", "Wstań do pozycji stojącej."],
    mistakes: ["Oddalanie sztangi od ciała", "Przyjęcie z ugiętymi ramionami"],
    precautions: ["Wymaga bardzo dobrej ruchomości barków i odcinka piersiowego."],
    regression: "snatch-pull", progression: "hang-snatch", substitutions: ["kettlebell-snatch"], protocol: "5 × 2" },
  { slug: "hang-snatch", name: "Rwanie z wysokości", en: "Hang Snatch", pattern: "hinge",
    primary: ["gluteusMaximus"], secondary: ["trapezius", "anteriorDeltoid"], equipment: ["Sztanga"], level: "Zaawansowany", supervision: true,
    start: "Sztanga w dłoniach na wysokości ud, chwyt szeroki.",
    steps: ["Cofnij biodra.", "Wyprostuj je dynamicznie.", "Przyjmij sztangę nad głową."],
    mistakes: ["Zbyt wczesne zginanie ramion"], regression: "power-snatch", progression: null,
    substitutions: ["power-snatch"], protocol: "5 × 2" },
  { slug: "snatch-pull", name: "Ciąg rwaniowy", en: "Snatch Pull", pattern: "hinge",
    primary: ["trapezius"], secondary: ["gluteusMaximus", "erectorSpinae"], equipment: ["Sztanga"], level: "Zaawansowany", goals: ["Siła", "Technika"],
    start: "Chwyt rwaniowy, sztanga na podłożu.",
    steps: ["Oderwij sztangę i przyspiesz w drugiej fazie.", "Domknij wyprost bioder.", "Nie przechodź do przyjęcia."],
    mistakes: ["Zginanie ramion"], regression: "martwy-ciag-klasyczny", progression: "power-snatch",
    substitutions: ["clean-pull"], protocol: "5 × 3" },
  { slug: "push-jerk", name: "Push jerk", en: "Push Jerk", pattern: "vertical-push",
    primary: ["anteriorDeltoid"], secondary: ["quadriceps", "triceps"], equipment: ["Sztanga", "Stojaki"], level: "Zaawansowany", supervision: true,
    start: "Sztanga na przedniej części barków.",
    steps: ["Wykonaj krótkie ugięcie kolan.", "Wypchnij sztangę dynamicznie w górę.", "Podejdź pod nią w półprzysiadzie i wstań."],
    mistakes: ["Zbyt głębokie ugięcie", "Wypychanie bioder do przodu"],
    regression: "push-press", progression: "split-jerk", substitutions: ["push-press"], protocol: "5 × 2" },
  { slug: "split-jerk", name: "Split jerk", en: "Split Jerk", pattern: "vertical-push",
    primary: ["anteriorDeltoid"], secondary: ["quadriceps", "gluteusMaximus"], equipment: ["Sztanga", "Stojaki"], level: "Zaawansowany", supervision: true,
    start: "Sztanga na barkach, stopy pod biodrami.",
    steps: ["Ugnij kolana i wypchnij sztangę.", "Przejdź do wykroku, przyjmując ciężar nad głową.", "Zbierz stopy do linii."],
    mistakes: ["Zbyt płytki wykrok", "Przyjęcie sztangi przed linią barków"],
    regression: "push-jerk", progression: null, substitutions: ["push-jerk"], protocol: "5 × 2" },
  { slug: "overhead-squat", name: "Przysiad z ciężarem nad głową", en: "Overhead Squat", pattern: "squat",
    primary: ["quadriceps"], secondary: ["anteriorDeltoid", "rectusAbdominis"], equipment: ["Sztanga"], level: "Zaawansowany", goals: ["Technika", "Mobilność"], supervision: true,
    start: "Sztanga nad głową na wyprostowanych ramionach, chwyt szeroki.",
    steps: ["Ustabilizuj sztangę nad środkiem stóp.", "Zejdź do pełnego przysiadu.", "Wstań, utrzymując sztangę nad głową."],
    mistakes: ["Wysuwanie sztangi przed linię ciała"], precautions: ["Wymaga bardzo dobrej ruchomości barków, bioder i skokowych."],
    regression: "przysiad-przedni", progression: null, substitutions: ["przysiad-przedni"], protocol: "4 × 3" },
  { slug: "muscle-clean", name: "Muscle clean", en: "Muscle Clean", pattern: "hinge",
    primary: ["trapezius"], secondary: ["gluteusMaximus", "biceps"], equipment: ["Sztanga"], level: "Zaawansowany", goals: ["Technika"],
    start: "Sztanga na wysokości ud, chwyt zarzutowy.",
    steps: ["Wyprostuj biodra dynamicznie.", "Podciągnij sztangę do barków bez uginania nóg.", "Przyjmij ją w pozycji stojącej."],
    mistakes: ["Uginanie nóg przy przyjęciu"], regression: "clean-pull", progression: "power-clean",
    substitutions: ["power-clean"], protocol: "4 × 3" },
];

const cardioDrafts: Draft[] = [
  { slug: "bieznia-marsz", name: "Marsz na bieżni", en: "Treadmill Walk", pattern: "cardio",
    primary: ["quadriceps"], secondary: ["calves", "gluteusMaximus"], equipment: ["Bieżnia"], level: "Podstawowy", goals: ["Redukcja", "Regeneracja"],
    start: "Ustawiasz prędkość marszową i wybrane nachylenie.",
    steps: ["Rozpocznij od kilku minut w spokojnym tempie.", "Utrzymuj wyprostowaną sylwetkę bez trzymania się poręczy.", "Zakończ stopniowym zwolnieniem."],
    breathing: "Oddychaj swobodnie, tempo pozwala na rozmowę.",
    mistakes: ["Trzymanie się poręczy, co zaniża wysiłek"], regression: null, progression: "bieznia-marsz-pod-gore",
    substitutions: ["orbitrek"], parameters: ["czas", "dystans", "rundy", "przerwa"], protocol: "30–45 min" },
  { slug: "bieznia-marsz-pod-gore", name: "Marsz pod górę", en: "Incline Walk", pattern: "cardio",
    primary: ["gluteusMaximus"], secondary: ["hamstrings", "calves"], equipment: ["Bieżnia"], level: "Podstawowy", goals: ["Redukcja", "Wytrzymałość"],
    start: "Nachylenie od dziesięciu do piętnastu procent, prędkość marszowa.",
    steps: ["Ustaw nachylenie i prędkość.", "Idź bez trzymania poręczy.", "Zakończ zmniejszając nachylenie."],
    mistakes: ["Trzymanie się poręczy"], regression: "bieznia-marsz", progression: "bieg-ciagly",
    substitutions: ["schody-treningowe"], parameters: ["czas", "dystans", "rundy", "przerwa"], protocol: "25–40 min" },
  { slug: "bieg-ciagly", name: "Bieg ciągły", en: "Steady-State Run", pattern: "cardio",
    primary: ["quadriceps", "hamstrings"], secondary: ["calves"], equipment: ["Bieżnia", "Masa ciała"], goals: ["Wytrzymałość", "Redukcja"],
    start: "Rozgrzewka marszowa przez pięć minut.",
    steps: ["Przejdź do tempa, w którym utrzymasz rozmowę.", "Utrzymaj je przez zaplanowany czas.", "Zakończ marszem."],
    mistakes: ["Zbyt szybki start"], precautions: ["Przy dolegliwościach stawów wybierz orbitrek albo rower."],
    regression: "bieznia-marsz", progression: "interwaly", substitutions: ["ergometr-wioslarski"],
    parameters: ["czas", "dystans", "rpe", "przerwa"], protocol: "30 min" },
  { slug: "interwaly", name: "Interwały", en: "Interval Training", pattern: "cardio",
    primary: ["quadriceps"], secondary: ["gluteusMaximus"], equipment: ["Bieżnia", "Air bike", "Rower stacjonarny"], goals: ["Wytrzymałość", "Redukcja"],
    start: "Rozgrzewka przez osiem do dziesięciu minut.",
    steps: ["Wykonaj odcinek pracy w wysokiej intensywności.", "Przejdź do aktywnej przerwy.", "Powtórz zaplanowaną liczbę rund.", "Zakończ schłodzeniem."],
    mistakes: ["Zbyt krótkie przerwy", "Zbyt wysoka intensywność w pierwszych rundach"],
    regression: "bieg-ciagly", progression: null, substitutions: ["air-bike"],
    parameters: ["czas", "rundy", "przerwa", "rpe"], protocol: "8 × 30 s / 90 s" },
  { slug: "rower-stacjonarny", name: "Rower stacjonarny", en: "Stationary Bike", pattern: "cardio",
    primary: ["quadriceps"], secondary: ["gluteusMaximus", "calves"], equipment: ["Rower stacjonarny"], level: "Podstawowy", goals: ["Redukcja", "Regeneracja"],
    start: "Siodełko na wysokości bioder, kolano lekko ugięte w dolnym położeniu.",
    steps: ["Ustaw wysokość siodełka.", "Utrzymuj równą kadencję.", "Zakończ kilkoma minutami lekkiego pedałowania."],
    mistakes: ["Zbyt niskie siodełko obciążające kolana"], regression: null, progression: "air-bike",
    substitutions: ["orbitrek"], parameters: ["czas", "dystans", "rpe", "przerwa"], protocol: "30 min" },
  { slug: "air-bike", name: "Rower powietrzny", en: "Air Bike", pattern: "cardio",
    primary: ["quadriceps"], secondary: ["latissimusDorsi", "anteriorDeltoid"], equipment: ["Air bike"], goals: ["Wytrzymałość"],
    start: "Siedzisz z dłońmi na uchwytach, stopy na pedałach.",
    steps: ["Pracuj jednocześnie ramionami i nogami.", "Utrzymaj równe tempo w odcinku pracy.", "Zwolnij w przerwie."],
    mistakes: ["Praca wyłącznie nogami"], regression: "rower-stacjonarny", progression: null,
    substitutions: ["ergometr-wioslarski"], parameters: ["czas", "rundy", "przerwa", "rpe"], protocol: "10 × 20 s / 40 s" },
  { slug: "ergometr-wioslarski", name: "Ergometr wioślarski", en: "Rowing Ergometer", pattern: "cardio",
    primary: ["latissimusDorsi"], secondary: ["quadriceps", "gluteusMaximus"], equipment: ["Ergometr wioślarski"], goals: ["Wytrzymałość"],
    start: "Stopy zapięte, chwyt na drążku, kolana ugięte.",
    steps: ["Rozpocznij ruch od wyprostu nóg.", "Następnie odchyl tułów i przyciągnij drążek.", "Wróć w odwrotnej kolejności."],
    mistakes: ["Ciągnięcie ramionami przed wyprostem nóg"], regression: null, progression: null,
    substitutions: ["skierg"], parameters: ["czas", "dystans", "rundy", "rpe", "przerwa"], protocol: "20 min" },
  { slug: "skierg", name: "SkiErg", en: "SkiErg", pattern: "cardio",
    primary: ["latissimusDorsi"], secondary: ["rectusAbdominis", "triceps"], equipment: ["SkiErg"], goals: ["Wytrzymałość"],
    start: "Stoisz przodem do urządzenia, uchwyty nad głową.",
    steps: ["Pociągnij uchwyty w dół, zginając tułów.", "Domknij ruch przy biodrach.", "Wróć płynnie do pozycji wyjściowej."],
    mistakes: ["Praca wyłącznie ramionami"], regression: "ergometr-wioslarski", progression: null,
    substitutions: ["ergometr-wioslarski"], parameters: ["czas", "dystans", "rundy", "przerwa"], protocol: "15 min" },
  { slug: "orbitrek", name: "Orbitrek", en: "Elliptical Trainer", pattern: "cardio",
    primary: ["quadriceps"], secondary: ["gluteusMaximus", "latissimusDorsi"], equipment: ["Orbitrek"], level: "Podstawowy", goals: ["Redukcja", "Regeneracja"],
    start: "Stopy na podnóżkach, dłonie na ruchomych uchwytach.",
    steps: ["Utrzymuj równe tempo.", "Pracuj także ramionami.", "Zakończ stopniowym zwolnieniem."],
    mistakes: ["Opieranie się o uchwyty"], regression: null, progression: null, substitutions: ["rower-stacjonarny"],
    parameters: ["czas", "dystans", "rpe", "przerwa"], protocol: "30 min" },
  { slug: "schody-treningowe", name: "Schody treningowe", en: "Stair Climber", pattern: "cardio",
    primary: ["gluteusMaximus", "quadriceps"], secondary: ["calves"], equipment: ["Schody treningowe"], goals: ["Redukcja", "Wytrzymałość"],
    start: "Stoisz na stopniach, dłonie luźno przy poręczach.",
    steps: ["Utrzymuj wyprostowaną sylwetkę.", "Stawiaj całą stopę na stopniu.", "Nie opieraj ciężaru ciała na poręczach."],
    mistakes: ["Podpieranie się poręczami"], regression: "bieznia-marsz-pod-gore", progression: null,
    substitutions: ["stepper"], parameters: ["czas", "rundy", "rpe", "przerwa"], protocol: "20 min" },
  { slug: "stepper", name: "Stepper", en: "Stepper", pattern: "cardio",
    primary: ["quadriceps", "gluteusMaximus"], secondary: ["calves"], equipment: ["Stepper"], level: "Podstawowy", goals: ["Redukcja"],
    start: "Stopy na podnóżkach, sylwetka wyprostowana.",
    steps: ["Utrzymuj równe tempo.", "Nie podpieraj się mocno rękami.", "Zakończ stopniowym zwolnieniem."],
    mistakes: ["Opieranie ciężaru na uchwytach"], regression: null, progression: "schody-treningowe",
    substitutions: ["schody-treningowe"], parameters: ["czas", "rpe", "przerwa"], protocol: "20 min" },
  { slug: "skakanka", name: "Skakanka", en: "Jump Rope", pattern: "cardio",
    primary: ["calves"], secondary: ["forearms", "quadriceps"], equipment: ["Skakanka"], level: "Podstawowy", goals: ["Wytrzymałość", "Sprawność"],
    start: "Skakanka za piętami, łokcie przy tułowiu.",
    steps: ["Obracaj skakankę nadgarstkami.", "Odbijaj się nisko ze śródstopia.", "Utrzymuj równy rytm."],
    mistakes: ["Zbyt wysokie podskoki", "Praca całymi ramionami"], regression: null, progression: null,
    substitutions: ["pogo-jump"], parameters: ["serie", "czas", "rundy", "przerwa"], protocol: "6 × 60 s" },
  { slug: "spacer", name: "Spacer", en: "Walking", pattern: "cardio",
    primary: ["quadriceps"], secondary: ["calves"], equipment: ["Masa ciała"], level: "Podstawowy", goals: ["Regeneracja", "Redukcja"],
    start: "Wygodne obuwie, spokojne tempo.",
    steps: ["Idź w tempie pozwalającym na rozmowę.", "Utrzymuj wyprostowaną sylwetkę.", "Zakończ swobodnie."],
    mistakes: ["Traktowanie spaceru jako treningu o wysokiej intensywności"], regression: null, progression: "bieznia-marsz-pod-gore",
    substitutions: ["bieznia-marsz"], parameters: ["czas", "dystans"], protocol: "30–60 min" },
];

const recoveryDrafts: Draft[] = [
  { slug: "oddech-przeponowy", name: "Oddech przeponowy", en: "Diaphragmatic Breathing", pattern: "recovery",
    primary: ["rectusAbdominis"], secondary: [], compound: false, equipment: ["Mata"], level: "Podstawowy", goals: ["Regeneracja"],
    start: "Leżysz na plecach, jedna dłoń na klatce, druga na brzuchu.",
    steps: ["Wdychaj nosem tak, aby unosiła się dłoń na brzuchu.", "Wydychaj powoli ustami.", "Utrzymuj spokojny rytm."],
    breathing: "Wdech przez nos przez cztery sekundy, wydech przez sześć.",
    mistakes: ["Unoszenie klatki zamiast brzucha"], regression: null, progression: "box-breathing",
    substitutions: ["box-breathing"], parameters: ["serie", "czas", "rundy"], protocol: "5 min" },
  { slug: "box-breathing", name: "Oddech kwadratowy", en: "Box Breathing", pattern: "recovery",
    primary: ["rectusAbdominis"], secondary: [], compound: false, equipment: ["Mata"], level: "Podstawowy", goals: ["Regeneracja"],
    start: "Siedzisz lub leżysz w wygodnej pozycji.",
    steps: ["Wdech przez cztery sekundy.", "Zatrzymanie przez cztery.", "Wydech przez cztery.", "Zatrzymanie przez cztery i powtórz."],
    breathing: "Rytm cztery–cztery–cztery–cztery.",
    mistakes: ["Wymuszanie zbyt długich faz"], precautions: ["Przy zawrotach głowy skróć fazy zatrzymania."],
    regression: "oddech-przeponowy", progression: null, substitutions: ["oddech-przeponowy"],
    parameters: ["serie", "czas", "rundy"], protocol: "4 min" },
  { slug: "rolowanie-czworoglowych", name: "Rolowanie czworogłowych", en: "Quad Foam Rolling", pattern: "recovery",
    primary: ["quadriceps"], secondary: [], compound: false, equipment: ["Wałek", "Mata"], level: "Podstawowy", goals: ["Regeneracja", "Mobilność"],
    start: "Leżysz przodem, wałek pod udami.",
    steps: ["Przetaczaj wałek wzdłuż uda.", "Zatrzymaj się na bolesnych punktach na kilkanaście sekund.", "Oddychaj spokojnie."],
    mistakes: ["Zbyt szybkie przetaczanie", "Rolowanie po stawach"],
    precautions: ["Nie roluj bezpośrednio po urazach ani po stronie wewnętrznej kolana."],
    regression: null, progression: null, substitutions: ["rolowanie-plecow"], parameters: ["serie", "czas", "strona"], protocol: "2 × 60 s na stronę" },
  { slug: "rolowanie-plecow", name: "Rolowanie odcinka piersiowego", en: "Thoracic Foam Rolling", pattern: "recovery",
    primary: ["erectorSpinae"], secondary: [], compound: false, equipment: ["Wałek", "Mata"], level: "Podstawowy", goals: ["Regeneracja", "Mobilność"],
    start: "Leżysz na plecach, wałek pod odcinkiem piersiowym.",
    steps: ["Przetaczaj wałek między łopatkami.", "Nie roluj odcinka lędźwiowego.", "Oddychaj spokojnie."],
    mistakes: ["Rolowanie lędźwi"], precautions: ["Odcinek lędźwiowy pomijamy."],
    regression: null, progression: null, substitutions: ["kot-krowa"], parameters: ["serie", "czas"], protocol: "2 × 60 s" },
  { slug: "pozycja-dziecka", name: "Pozycja dziecka", en: "Child's Pose", pattern: "recovery",
    primary: ["erectorSpinae"], secondary: ["latissimusDorsi"], compound: false, equipment: ["Mata"], level: "Podstawowy", goals: ["Regeneracja", "Mobilność"],
    start: "Klęk, pośladki na piętach, ramiona wyciągnięte przed siebie.",
    steps: ["Usiądź na piętach i wydłuż ramiona.", "Oddychaj w plecy.", "Utrzymaj pozycję przez zadany czas."],
    mistakes: ["Napinanie barków"], regression: null, progression: null, substitutions: ["rolowanie-plecow"],
    parameters: ["serie", "czas"], protocol: "3 × 60 s" },
  { slug: "cardio-regeneracyjne", name: "Cardio regeneracyjne", en: "Recovery Cardio", pattern: "recovery",
    primary: ["quadriceps"], secondary: [], equipment: ["Rower stacjonarny", "Orbitrek", "Masa ciała"], level: "Podstawowy", goals: ["Regeneracja"],
    start: "Bardzo lekkie tempo, opór minimalny.",
    steps: ["Utrzymuj tętno w strefie spokojnej.", "Pracuj przez dziesięć do dwudziestu minut.", "Zakończ rozciąganiem."],
    mistakes: ["Podnoszenie intensywności"], regression: null, progression: null, substitutions: ["spacer"],
    parameters: ["czas", "rpe"], protocol: "15 min" },
];

export const mobilityExercises = buildCategory("Mobilność", mobilityDrafts);
export const functionalExercises = buildCategory("Funkcjonalne", functionalDrafts);
export const powerliftingExercises = buildCategory("Trójbój", powerliftingDrafts);
export const olympicExercises = buildCategory("Ciężary olimpijskie", olympicDrafts);
export const cardioExercises = buildCategory("Cardio", cardioDrafts);
export const recoveryExercises = buildCategory("Regeneracja", recoveryDrafts);
