import { buildCategory, type Draft } from "@/lib/exercises/catalog/helpers";

const coreDrafts: Draft[] = [
  { slug: "plank", name: "Deska", en: "Plank", pattern: "anti-extension",
    primary: ["rectusAbdominis"], secondary: ["obliques", "gluteusMaximus"], equipment: ["Mata"], level: "Podstawowy", goals: ["Technika", "Sprawność"],
    start: "Podpór na przedramionach, łokcie pod barkami, ciało w jednej linii.",
    steps: ["Ustaw żebra nad miednicą.", "Napnij pośladki i brzuch.", "Utrzymaj długą linię ciała przez zadany czas."],
    breathing: "Oddychaj spokojnie i płytko, nie wstrzymuj powietrza.",
    mistakes: ["Opadanie bioder", "Unoszenie pośladków", "Wstrzymywanie oddechu"],
    regression: "plank-na-kolanach", progression: "rkc-plank", substitutions: ["dead-bug"],
    parameters: ["serie", "czas", "przerwa"], protocol: "3 × 45 s" },
  { slug: "plank-na-kolanach", name: "Deska na kolanach", en: "Kneeling Plank", pattern: "anti-extension",
    primary: ["rectusAbdominis"], secondary: [], equipment: ["Mata"], level: "Podstawowy", goals: ["Technika"],
    start: "Podpór na przedramionach i kolanach.",
    steps: ["Ustaw kolana pod biodrami.", "Napnij brzuch i pośladki.", "Utrzymaj linię od kolan po głowę."],
    mistakes: ["Zapadanie w lędźwiach"], regression: null, progression: "plank", substitutions: ["dead-bug"],
    parameters: ["serie", "czas", "przerwa"], protocol: "3 × 30 s" },
  { slug: "rkc-plank", name: "RKC plank", en: "RKC Plank", pattern: "anti-extension",
    primary: ["rectusAbdominis"], secondary: ["gluteusMaximus"], equipment: ["Mata"], level: "Zaawansowany",
    start: "Deska na przedramionach z maksymalnym napięciem całego ciała.",
    steps: ["Zaciśnij pięści i przyciągnij łokcie w stronę stóp.", "Napnij pośladki i czworogłowe do maksimum.", "Utrzymaj od dziesięciu do dwudziestu sekund."],
    mistakes: ["Utrzymywanie pozycji zbyt długo kosztem napięcia"], regression: "plank", progression: null,
    substitutions: ["ab-wheel"], parameters: ["serie", "czas", "przerwa"], protocol: "3 × 15 s" },
  { slug: "side-plank", name: "Deska bokiem", en: "Side Plank", pattern: "lateral-flexion",
    primary: ["obliques"], secondary: ["gluteusMaximus", "anteriorDeltoid"], equipment: ["Mata"], laterality: "jednostronne", level: "Podstawowy",
    start: "Podpór bokiem na przedramieniu, łokieć pod barkiem.",
    steps: ["Unieś biodra do prostej linii od kostki po głowę.", "Utrzymaj pozycję bez rotacji.", "Zejdź kontrolowanie."],
    mistakes: ["Opadanie bioder", "Rotacja tułowia"], regression: "plank-na-kolanach", progression: "copenhagen-plank",
    substitutions: ["pallof-press"], parameters: ["serie", "czas", "strona", "przerwa"], protocol: "3 × 30 s na stronę" },
  { slug: "dead-bug", name: "Dead bug", en: "Dead Bug", pattern: "anti-extension",
    primary: ["rectusAbdominis"], secondary: [], equipment: ["Mata"], level: "Podstawowy", laterality: "naprzemienne", goals: ["Technika"],
    start: "Leżysz na plecach, ramiona nad barkami, biodra i kolana zgięte do kąta prostego.",
    steps: ["Dociśnij odcinek lędźwiowy do maty.", "Wydłużaj przeciwległą rękę i nogę.", "Wróć, nie tracąc kontaktu lędźwi z podłożem."],
    mistakes: ["Odrywanie lędźwi od maty"], regression: null, progression: "hollow-body-hold",
    substitutions: ["bird-dog"], parameters: ["serie", "powtorzenia", "tempo", "przerwa"], protocol: "3 × 10 na stronę" },
  { slug: "bird-dog", name: "Bird dog", en: "Bird Dog", pattern: "anti-rotation",
    primary: ["rectusAbdominis"], secondary: ["erectorSpinae", "gluteusMaximus"], equipment: ["Mata"], level: "Podstawowy", laterality: "naprzemienne",
    start: "Klęk podparty, plecy neutralne.",
    steps: ["Wydłuż przeciwległą rękę i nogę.", "Utrzymaj miednicę równolegle do podłoża.", "Wróć i zmień stronę."],
    mistakes: ["Rotowanie bioder", "Unoszenie nogi zbyt wysoko"], regression: null, progression: "dead-bug",
    substitutions: ["dead-bug"], parameters: ["serie", "powtorzenia", "tempo", "przerwa"], protocol: "3 × 10 na stronę" },
  { slug: "hollow-body-hold", name: "Hollow body hold", en: "Hollow Body Hold", pattern: "anti-extension",
    primary: ["rectusAbdominis"], secondary: [], equipment: ["Mata"], level: "Zaawansowany",
    start: "Leżysz na plecach, lędźwie dociśnięte do maty.",
    steps: ["Unieś łopatki i nogi nad matę.", "Utrzymaj lędźwie w kontakcie z podłożem.", "Wytrzymaj zadany czas."],
    mistakes: ["Odrywanie lędźwi"], regression: "dead-bug", progression: null, substitutions: ["ab-wheel"],
    parameters: ["serie", "czas", "przerwa"], protocol: "3 × 20 s" },
  { slug: "crunch", name: "Brzuszki", en: "Crunch", pattern: "flexion",
    primary: ["rectusAbdominis"], secondary: [], compound: false, equipment: ["Mata"], level: "Podstawowy",
    start: "Leżysz na plecach, kolana ugięte, dłonie przy skroniach.",
    steps: ["Unieś łopatki ruchem zwijania.", "Zatrzymaj w skurczu.", "Opuść powoli."],
    mistakes: ["Pociąganie karku dłońmi", "Praca zamachem"], regression: null, progression: "cable-crunch",
    substitutions: ["cable-crunch"], parameters: ["serie", "powtorzenia", "tempo", "przerwa"], protocol: "3 × 15–20" },
  { slug: "cable-crunch", name: "Spięcia na wyciągu", en: "Cable Crunch", pattern: "flexion",
    primary: ["rectusAbdominis"], secondary: [], compound: false, equipment: ["Wyciąg górny"],
    start: "Klęk przodem do wyciągu, lina przy głowie.",
    steps: ["Zegnij tułów, prowadząc łokcie do ud.", "Zatrzymaj w skurczu.", "Wróć powoli, nie prostując bioder."],
    mistakes: ["Praca biodrami zamiast tułowiem"], regression: "crunch", progression: null, substitutions: ["crunch"], protocol: "3 × 15" },
  { slug: "reverse-crunch", name: "Spięcia odwrotne", en: "Reverse Crunch", pattern: "flexion",
    primary: ["rectusAbdominis"], secondary: [], compound: false, equipment: ["Mata"], level: "Podstawowy",
    start: "Leżysz na plecach, kolana zgięte nad biodrami.",
    steps: ["Zwiń miednicę w stronę klatki.", "Unieś biodra nad matę.", "Opuść powoli."],
    mistakes: ["Rozpęd nogami"], regression: null, progression: "hanging-knee-raise", substitutions: ["hanging-knee-raise"], protocol: "3 × 15" },
  { slug: "hanging-knee-raise", name: "Unoszenie kolan w zwisie", en: "Hanging Knee Raise", pattern: "flexion",
    primary: ["rectusAbdominis"], secondary: ["forearms"], equipment: ["Drążek"],
    start: "Zwis na drążku, barki aktywne.",
    steps: ["Zwiń miednicę i unieś kolana do klatki.", "Zatrzymaj na moment.", "Opuść powoli bez bujania."],
    mistakes: ["Bujanie ciałem", "Praca samymi zginaczami biodra"], regression: "reverse-crunch", progression: "hanging-leg-raise",
    substitutions: ["captains-chair-raise"], protocol: "3 × 12" },
  { slug: "hanging-leg-raise", name: "Unoszenie nóg w zwisie", en: "Hanging Leg Raise", pattern: "flexion",
    primary: ["rectusAbdominis"], secondary: ["forearms"], equipment: ["Drążek"], level: "Zaawansowany",
    start: "Zwis na drążku, nogi wyprostowane.",
    steps: ["Unieś proste nogi do poziomu bioder lub wyżej.", "Zwiń miednicę na końcu ruchu.", "Opuść powoli."],
    mistakes: ["Rozpęd", "Skracanie zakresu"], regression: "hanging-knee-raise", progression: null,
    substitutions: ["captains-chair-raise"], protocol: "3 × 10" },
  { slug: "captains-chair-raise", name: "Unoszenie nóg w drabinkach", en: "Captain's Chair Raise", pattern: "flexion",
    primary: ["rectusAbdominis"], secondary: [], equipment: ["Maszyna plate-loaded"], level: "Podstawowy",
    start: "Przedramiona na podparciu, plecy przy oparciu.",
    steps: ["Unieś kolana do klatki.", "Zwiń miednicę.", "Opuść powoli."],
    mistakes: ["Odchylanie pleców od oparcia"], regression: null, progression: "hanging-leg-raise",
    substitutions: ["hanging-knee-raise"], protocol: "3 × 15" },
  { slug: "ab-wheel", name: "Ab wheel", en: "Ab Wheel Rollout", pattern: "anti-extension",
    primary: ["rectusAbdominis"], secondary: ["latissimusDorsi", "anteriorDeltoid"], equipment: ["Maszyna plate-loaded", "Mata"], level: "Zaawansowany",
    start: "Klęk, kółko pod barkami, żebra ściągnięte.",
    steps: ["Wyjeżdżaj kółkiem tak daleko, jak utrzymasz lędźwie bez przeprostu.", "Zatrzymaj w skrajnej pozycji.", "Wróć, zwijając miednicę."],
    mistakes: ["Wypadanie lędźwi w przeprost"], precautions: ["Przy bólu lędźwi zacznij od bardzo krótkiego zakresu."],
    regression: "plank", progression: null, substitutions: ["body-saw"], parameters: ["serie", "powtorzenia", "tempo", "przerwa"], protocol: "3 × 8" },
  { slug: "body-saw", name: "Body saw", en: "Body Saw", pattern: "anti-extension",
    primary: ["rectusAbdominis"], secondary: [], equipment: ["Mata"], level: "Zaawansowany",
    start: "Deska na przedramionach, stopy na ślizgach lub ręczniku.",
    steps: ["Przesuń ciało do tyłu, prostując linię.", "Wróć do wyjściowej pozycji.", "Utrzymuj napięcie brzucha."],
    mistakes: ["Opadanie bioder"], regression: "plank", progression: "ab-wheel", substitutions: ["ab-wheel"],
    parameters: ["serie", "powtorzenia", "tempo", "przerwa"], protocol: "3 × 10" },
  { slug: "pallof-press", name: "Pallof press", en: "Pallof Press", pattern: "anti-rotation",
    primary: ["obliques"], secondary: ["rectusAbdominis"], equipment: ["Brama kablowa", "Guma oporowa"], laterality: "jednostronne", level: "Podstawowy", goals: ["Technika", "Sprawność"],
    start: "Stoisz bokiem do wyciągu, uchwyt przy mostku.",
    steps: ["Ustaw stopy stabilnie.", "Wyprostuj ramiona przed siebie.", "Nie pozwól tułowiowi obrócić się w stronę wyciągu."],
    mistakes: ["Rotacja tułowia pod wpływem oporu"], regression: null, progression: "woodchopper",
    substitutions: ["side-plank"], parameters: ["serie", "powtorzenia", "czas", "strona", "przerwa"], protocol: "3 × 12 na stronę" },
  { slug: "woodchopper", name: "Wyrąb drewna", en: "Woodchopper", pattern: "rotation",
    primary: ["obliques"], secondary: ["rectusAbdominis", "gluteusMaximus"], equipment: ["Brama kablowa"], laterality: "jednostronne",
    start: "Stoisz bokiem do wyciągu ustawionego wysoko lub nisko.",
    steps: ["Prowadź uchwyt skośnie przez tułów.", "Rotuj z klatki, nie z lędźwi.", "Wróć kontrolowanie."],
    mistakes: ["Rotowanie z odcinka lędźwiowego"], regression: "pallof-press", progression: null,
    substitutions: ["landmine-rotation"], protocol: "3 × 12 na stronę" },
  { slug: "landmine-rotation", name: "Rotacja landmine", en: "Landmine Rotation", pattern: "rotation",
    primary: ["obliques"], secondary: ["anteriorDeltoid"], equipment: ["Landmine", "Sztanga"],
    start: "Stoisz przodem do landmine, gryf trzymany oburącz przed sobą.",
    steps: ["Prowadź gryf łukiem na bok.", "Rotuj biodrami razem z tułowiem.", "Wróć i zmień stronę."],
    mistakes: ["Blokowanie bioder i rotowanie samym kręgosłupem"], regression: "pallof-press", progression: null,
    substitutions: ["woodchopper"], protocol: "3 × 10 na stronę" },
  { slug: "russian-twist", name: "Skrętoskłony", en: "Russian Twist", pattern: "rotation",
    primary: ["obliques"], secondary: ["rectusAbdominis"], equipment: ["Piłka lekarska", "Talerze"], level: "Podstawowy",
    start: "Siedzisz z uniesionymi stopami, tułów odchylony do tyłu.",
    steps: ["Rotuj tułów, prowadząc ruch klatką.", "Dotknij ciężarem podłoża po obu stronach.", "Utrzymuj proste plecy."],
    mistakes: ["Rotowanie samymi ramionami", "Zaokrąglanie pleców"], regression: "bicycle-crunch", progression: null,
    substitutions: ["landmine-rotation"], protocol: "3 × 20" },
  { slug: "bicycle-crunch", name: "Rowerek", en: "Bicycle Crunch", pattern: "rotation",
    primary: ["obliques"], secondary: ["rectusAbdominis"], equipment: ["Mata"], level: "Podstawowy", laterality: "naprzemienne",
    start: "Leżysz na plecach, łopatki uniesione, kolana nad biodrami.",
    steps: ["Prowadź łokieć do przeciwnego kolana.", "Wyprostuj drugą nogę.", "Zmieniaj strony w kontrolowanym tempie."],
    mistakes: ["Pociąganie karku", "Zbyt szybkie tempo"], regression: "crunch", progression: "russian-twist",
    substitutions: ["russian-twist"], parameters: ["serie", "powtorzenia", "czas", "tempo", "przerwa"], protocol: "3 × 20" },
  { slug: "mountain-climber", name: "Wspinaczka", en: "Mountain Climber", pattern: "locomotion",
    primary: ["rectusAbdominis"], secondary: ["anteriorDeltoid", "quadriceps"], equipment: ["Masa ciała"], level: "Podstawowy", goals: ["Wytrzymałość", "Sprawność"],
    start: "Podpór przodem, ciało w jednej linii.",
    steps: ["Przyciągaj kolana naprzemiennie do klatki.", "Utrzymuj biodra nisko.", "Zachowaj równe tempo."],
    mistakes: ["Unoszenie bioder", "Skracanie zakresu"], regression: "plank", progression: null,
    substitutions: ["bicycle-crunch"], parameters: ["serie", "czas", "powtorzenia", "przerwa"], protocol: "4 × 30 s" },
  { slug: "stir-the-pot", name: "Mieszanie w garnku", en: "Stir the Pot", pattern: "anti-extension",
    primary: ["rectusAbdominis"], secondary: ["obliques"], equipment: ["Piłka fitness"], level: "Zaawansowany",
    start: "Przedramiona na piłce, ciało w linii deski.",
    steps: ["Zataczaj przedramionami małe okręgi.", "Utrzymuj nieruchomą miednicę.", "Zmień kierunek po połowie serii."],
    mistakes: ["Ruch bioder zamiast ramion"], regression: "plank", progression: null, substitutions: ["ab-wheel"],
    parameters: ["serie", "powtorzenia", "czas", "przerwa"], protocol: "3 × 10 w każdą stronę" },
  { slug: "turkish-get-up", name: "Turkish get-up", en: "Turkish Get-Up", pattern: "locomotion",
    primary: ["obliques"], secondary: ["anteriorDeltoid", "gluteusMaximus", "quadriceps"], equipment: ["Kettlebell"], level: "Zaawansowany", laterality: "jednostronne",
    goals: ["Sprawność", "Technika"], supervision: true,
    start: "Leżysz na plecach, kettlebell wyciśnięty nad barkiem, jedno kolano ugięte.",
    steps: ["Unieś się na przedramię, potem na dłoń.", "Wypchnij biodra i przełóż nogę do klęku.", "Wstań, utrzymując ciężar nad barkiem.", "Wróć tą samą drogą."],
    mistakes: ["Utrata pionu ciężaru nad barkiem", "Pośpiech między fazami"],
    precautions: ["Naucz się ruchu bez obciążenia, następnie z lekkim ciężarem."],
    regression: "pallof-press", progression: null, substitutions: ["farmer-walk"],
    parameters: ["serie", "powtorzenia", "ciezar", "strona", "przerwa"], protocol: "3 × 3 na stronę" },
];

const extensorDrafts: Draft[] = [
  { slug: "back-extension-45", name: "Prostowanie tułowia 45 stopni", en: "45° Back Extension", pattern: "hinge",
    primary: ["erectorSpinae"], secondary: ["gluteusMaximus", "hamstrings"], equipment: ["Maszyna plate-loaded"], level: "Podstawowy",
    start: "Biodra na podparciu, stopy zablokowane, tułów wyprostowany.",
    steps: ["Opuść tułów zawiasem biodrowym.", "Wróć do linii ciała, nie przeprostowując pleców.", "Zatrzymaj na moment w górze."],
    mistakes: ["Przeprost na końcu ruchu"], precautions: ["Nie odchylaj tułowia powyżej linii ciała."],
    regression: "superman", progression: "back-extension-90", substitutions: ["reverse-hyperextension"],
    parameters: ["serie", "powtorzenia", "ciezar", "tempo", "przerwa"], protocol: "3 × 12" },
  { slug: "back-extension-90", name: "Prostowanie tułowia 90 stopni", en: "90° Back Extension", pattern: "hinge",
    primary: ["erectorSpinae"], secondary: ["gluteusMaximus"], equipment: ["Maszyna plate-loaded"],
    start: "Ustawienie pionowe, biodra na podparciu.",
    steps: ["Opuść tułów do pionu.", "Wróć do linii ciała.", "Kontroluj tempo."],
    mistakes: ["Przeprost"], regression: "back-extension-45", progression: null, substitutions: ["back-extension-45"], protocol: "3 × 12" },
  { slug: "superman", name: "Superman", en: "Superman", pattern: "anti-extension",
    primary: ["erectorSpinae"], secondary: ["gluteusMaximus"], equipment: ["Mata"], level: "Podstawowy", goals: ["Technika", "Sprawność"],
    start: "Leżysz na brzuchu, ramiona wyciągnięte przed siebie.",
    steps: ["Unieś jednocześnie ramiona i nogi.", "Zatrzymaj na moment.", "Opuść powoli."],
    mistakes: ["Odchylanie głowy do tyłu"], regression: null, progression: "back-extension-45",
    substitutions: ["bird-dog"], parameters: ["serie", "powtorzenia", "czas", "przerwa"], protocol: "3 × 12" },
  { slug: "sorensen-hold", name: "Test Sorensena", en: "Sorensen Hold", pattern: "anti-extension",
    primary: ["erectorSpinae"], secondary: ["gluteusMaximus"], equipment: ["Maszyna plate-loaded"], goals: ["Wytrzymałość", "Technika"],
    start: "Biodra na podparciu, tułów w poziomie, ramiona skrzyżowane na klatce.",
    steps: ["Utrzymaj tułów w linii ciała.", "Oddychaj spokojnie.", "Zakończ, gdy tracisz pozycję."],
    mistakes: ["Przeprost lędźwi w trakcie utrzymania"], regression: "superman", progression: null,
    substitutions: ["back-extension-45"], parameters: ["serie", "czas", "przerwa"], protocol: "3 × 45 s" },
];

export const coreExercises = buildCategory("Brzuch", coreDrafts);
export const extensorExercises = buildCategory("Prostowniki", extensorDrafts);
