import { buildCategory, type Draft } from "@/lib/exercises/catalog/helpers";

const quadDrafts: Draft[] = [
  { slug: "przysiad-high-bar", name: "Przysiad ze sztangą wysoko", en: "High-Bar Back Squat", pattern: "squat",
    primary: ["quadriceps"], secondary: ["gluteusMaximus", "erectorSpinae"], equipment: ["Sztanga", "Stojaki"], level: "Zaawansowany", goals: ["Siła", "Masa mięśniowa"],
    start: "Sztanga na czworobocznych, stopy na szerokość barków, palce lekko na zewnątrz.",
    steps: ["Napnij brzuch i ustaw łuk stopy.", "Zejdź, prowadząc kolana nad stopami i utrzymując pionowy tułów.", "Zejdź do głębokości, w której utrzymujesz pozycję miednicy.", "Wstań wypychając podłoże całą stopą."],
    breathing: "Wdech na górze, napięcie utrzymane przez całe powtórzenie, wydech po wyjściu z dołu.",
    mistakes: ["Zapadanie kolan do środka", "Odrywanie pięt", "Utrata napięcia tułowia na dole"],
    cues: ["Rozepchnij podłogę stopami na boki"], precautions: ["Przy bólu kolan zacznij od przysiadu do skrzyni albo goblet."],
    regression: "przysiad-goblet", progression: "przysiad-z-pauza", substitutions: ["przysiad-przedni", "hack-squat", "przysiad-smith"], protocol: "4 × 5–8" },
  { slug: "przysiad-low-bar", name: "Przysiad ze sztangą nisko", en: "Low-Bar Back Squat", pattern: "squat",
    primary: ["gluteusMaximus", "quadriceps"], secondary: ["hamstrings", "erectorSpinae"], equipment: ["Sztanga", "Stojaki"], level: "Zaawansowany", goals: ["Siła"],
    start: "Sztanga niżej, na tylnym aktonie barków, chwyt szerszy.",
    steps: ["Ustaw sztangę na tylnych aktonach barków.", "Zejdź z większym pochyleniem tułowia.", "Wypchnij biodra i podłoże jednocześnie."],
    mistakes: ["Nadmierne pochylenie zamieniające ruch w good morning"],
    regression: "przysiad-high-bar", progression: null, substitutions: ["przysiad-high-bar"], protocol: "4 × 5" },
  { slug: "przysiad-przedni", name: "Przysiad przedni", en: "Front Squat", pattern: "squat",
    primary: ["quadriceps"], secondary: ["gluteusMaximus", "rectusAbdominis"], equipment: ["Sztanga", "Stojaki"], level: "Zaawansowany",
    start: "Sztanga na przedniej części barków, łokcie wysoko.",
    steps: ["Utrzymaj łokcie wysoko przez cały ruch.", "Zejdź z pionowym tułowiem.", "Wstań bez opuszczania łokci."],
    mistakes: ["Opuszczanie łokci i pochylanie tułowia"], precautions: ["Wymaga ruchomości nadgarstków i odcinka piersiowego."],
    regression: "przysiad-goblet", progression: null, substitutions: ["przysiad-goblet", "hack-squat"], protocol: "4 × 5" },
  { slug: "przysiad-goblet", name: "Przysiad goblet", en: "Goblet Squat", pattern: "squat",
    primary: ["quadriceps"], secondary: ["gluteusMaximus", "rectusAbdominis"], equipment: ["Hantel", "Kettlebell"], level: "Podstawowy", goals: ["Technika", "Sprawność"],
    start: "Ciężar trzymany przy klatce, stopy na szerokość barków.",
    steps: ["Trzymaj ciężar blisko klatki.", "Zejdź, prowadząc kolana nad stopami.", "Wstań całą stopą."],
    mistakes: ["Zapadanie kolan", "Odrywanie pięt"], regression: "przysiad-do-skrzyni", progression: "przysiad-przedni",
    substitutions: ["przysiad-do-skrzyni"], protocol: "3 × 10–12" },
  { slug: "przysiad-safety-bar", name: "Przysiad z safety barem", en: "Safety Bar Squat", pattern: "squat",
    primary: ["quadriceps", "gluteusMaximus"], secondary: ["erectorSpinae"], equipment: ["Safety squat bar", "Stojaki"],
    start: "Gryf z poduszkami na barkach, dłonie na uchwytach.",
    steps: ["Napnij tułów, gryf spycha go do przodu.", "Zejdź, aktywnie utrzymując klatkę wysoko.", "Wstań całą stopą."],
    mistakes: ["Poddanie się pochyleniu wymuszanemu przez gryf"],
    precautions: ["Dobry wybór przy ograniczonej ruchomości barku."], regression: "przysiad-goblet", progression: null,
    substitutions: ["przysiad-high-bar"], protocol: "4 × 6" },
  { slug: "zercher-squat", name: "Zercher squat", en: "Zercher Squat", pattern: "squat",
    primary: ["quadriceps"], secondary: ["gluteusMaximus", "erectorSpinae", "rectusAbdominis"], equipment: ["Sztanga", "Klatka treningowa"], level: "Zaawansowany",
    start: "Sztanga w zgięciach łokci, tułów wyprostowany.",
    steps: ["Ustaw sztangę w zgięciach łokci.", "Zejdź z pionowym tułowiem.", "Wstań, utrzymując klatkę wysoko."],
    mistakes: ["Zaokrąglanie pleców pod ciężarem"], precautions: ["Użyj podkładki, gryf uciska zgięcia łokci."],
    regression: "przysiad-goblet", progression: null, substitutions: ["przysiad-przedni"], protocol: "3 × 6" },
  { slug: "przysiad-do-skrzyni", name: "Przysiad do skrzyni", en: "Box Squat", pattern: "squat",
    primary: ["gluteusMaximus", "quadriceps"], secondary: ["hamstrings"], equipment: ["Sztanga", "Skrzynia plyometryczna"], level: "Podstawowy", goals: ["Technika"],
    start: "Skrzynia za plecami na wybranej wysokości.",
    steps: ["Cofnij biodra do skrzyni.", "Usiądź lekko, nie rozluźniając tułowia.", "Wstań wypychając podłoże."],
    mistakes: ["Opadanie na skrzynię bez kontroli"], regression: null, progression: "przysiad-high-bar",
    substitutions: ["przysiad-goblet"], protocol: "4 × 6" },
  { slug: "przysiad-z-pauza", name: "Przysiad z pauzą", en: "Pause Squat", pattern: "squat",
    primary: ["quadriceps"], secondary: ["gluteusMaximus"], equipment: ["Sztanga", "Stojaki"], level: "Zaawansowany", goals: ["Siła", "Technika"],
    start: "Jak w przysiadzie klasycznym.",
    steps: ["Zejdź do dolnej pozycji.", "Zatrzymaj się na dwie do trzech sekund bez utraty napięcia.", "Wstań bez odbicia."],
    mistakes: ["Rozluźnienie w pauzie"], regression: "przysiad-high-bar", progression: null, substitutions: ["pin-squat"],
    parameters: ["serie", "powtorzenia", "ciezar", "tempo", "rpe", "przerwa"], protocol: "4 × 3" },
  { slug: "pin-squat", name: "Przysiad z pinów", en: "Pin Squat", pattern: "squat",
    primary: ["quadriceps"], secondary: ["gluteusMaximus"], equipment: ["Sztanga", "Klatka treningowa"], level: "Zaawansowany", goals: ["Siła"],
    start: "Piny ustawione na wysokości dolnej pozycji.",
    steps: ["Zejdź i odłóż sztangę na piny.", "Zresetuj napięcie.", "Wstań z martwego punktu bez odbicia."],
    mistakes: ["Odbijanie sztangi od pinów"], regression: "przysiad-z-pauza", progression: null, substitutions: ["przysiad-z-pauza"], protocol: "5 × 2" },
  { slug: "hack-squat", name: "Hack squat", en: "Hack Squat", pattern: "squat",
    primary: ["quadriceps"], secondary: ["gluteusMaximus"], equipment: ["Hack squat"], level: "Podstawowy",
    start: "Plecy przy platformie, stopy na środku podnóżka.",
    steps: ["Odblokuj maszynę.", "Zejdź do kąta prostego w kolanie.", "Wypchnij platformę bez blokowania kolan."],
    mistakes: ["Odrywanie bioder od oparcia na dole"], regression: "wypychanie-na-suwnicy", progression: "przysiad-high-bar",
    substitutions: ["pendulum-squat", "wypychanie-na-suwnicy"], protocol: "3 × 10" },
  { slug: "pendulum-squat", name: "Pendulum squat", en: "Pendulum Squat", pattern: "squat",
    primary: ["quadriceps"], secondary: ["gluteusMaximus"], equipment: ["Pendulum squat"],
    start: "Plecy przy oparciu, stopy na platformie.",
    steps: ["Zejdź po łuku wyznaczonym przez maszynę.", "Zatrzymaj w dolnej pozycji.", "Wypchnij platformę."],
    mistakes: ["Zbyt wąskie ustawienie stóp"], regression: "hack-squat", progression: null, substitutions: ["hack-squat"], protocol: "3 × 10" },
  { slug: "belt-squat", name: "Belt squat", en: "Belt Squat", pattern: "squat",
    primary: ["quadriceps", "gluteusMaximus"], secondary: [], equipment: ["Belt squat"],
    start: "Pas biodrowy z obciążeniem, stopy na platformie.",
    steps: ["Zejdź do pełnej głębokości.", "Wstań, wypychając podłoże.", "Utrzymuj wyprostowany tułów."],
    mistakes: ["Zbyt luźno zapięty pas"], cues: ["Obciążenie omija kręgosłup — dobre przy przeciążeniu grzbietu"],
    regression: "wypychanie-na-suwnicy", progression: null, substitutions: ["hack-squat"], protocol: "3 × 12" },
  { slug: "przysiad-smith", name: "Przysiad na Smithie", en: "Smith Machine Squat", pattern: "squat",
    primary: ["quadriceps"], secondary: ["gluteusMaximus"], equipment: ["Smith machine"], level: "Podstawowy",
    start: "Gryf na barkach, stopy nieco przed linią bioder.",
    steps: ["Odblokuj gryf.", "Zejdź po prowadnicy do kąta prostego.", "Wstań i zablokuj gryf po serii."],
    mistakes: ["Ustawienie stóp pod biodrami zamiast przed nimi"], regression: "wypychanie-na-suwnicy", progression: "przysiad-high-bar",
    substitutions: ["hack-squat"], protocol: "3 × 10" },
  { slug: "wypychanie-na-suwnicy", name: "Wypychanie na suwnicy", en: "Leg Press", pattern: "squat",
    primary: ["quadriceps"], secondary: ["gluteusMaximus", "hamstrings"], equipment: ["Leg press"], level: "Podstawowy",
    start: "Plecy i miednica przy oparciu, stopy na szerokość bioder.",
    steps: ["Zwolnij blokady.", "Zegnij kolana do zakresu, w którym lędźwie zostają na oparciu.", "Wypchnij platformę bez blokowania kolan."],
    mistakes: ["Odrywanie miednicy od oparcia", "Blokowanie kolan w wyproście"],
    precautions: ["Nie schodź głębiej, niż pozwala pozycja miednicy."],
    regression: null, progression: "hack-squat", substitutions: ["hack-squat", "belt-squat"], protocol: "3 × 12" },
  { slug: "prostowanie-nog", name: "Prostowanie nóg na maszynie", en: "Leg Extension", pattern: "isolation",
    primary: ["quadriceps"], secondary: [], compound: false, equipment: ["Leg extension"], level: "Podstawowy",
    start: "Siedzisz z wałkiem nad kostkami, plecy przy oparciu.",
    steps: ["Wyprostuj kolana do pełnego wyprostu.", "Zatrzymaj na moment.", "Opuść powoli."],
    mistakes: ["Szarpanie ciężaru", "Opadanie bez kontroli"], precautions: ["Przy dolegliwościach rzepkowo-udowych ogranicz zakres."],
    regression: null, progression: "sissy-squat", substitutions: ["sissy-squat"], protocol: "3 × 12–15" },
  { slug: "sissy-squat", name: "Sissy squat", en: "Sissy Squat", pattern: "squat",
    primary: ["quadriceps"], secondary: [], equipment: ["Masa ciała"], level: "Zaawansowany",
    start: "Stoisz, trzymając się podparcia, pięty uniesione.",
    steps: ["Odchyl tułów do tyłu, zginając kolana.", "Zejdź tak nisko, jak pozwala kontrola.", "Wróć napinając czworogłowe."],
    mistakes: ["Zbyt duży zakres na starcie"], precautions: ["Mocno obciąża staw kolanowy — nie dla początkujących."],
    regression: "prostowanie-nog", progression: null, substitutions: ["prostowanie-nog"], parameters: ["serie", "powtorzenia", "tempo", "przerwa"], protocol: "3 × 10" },
  { slug: "przysiad-bulgarski", name: "Przysiad bułgarski", en: "Bulgarian Split Squat", pattern: "lunge",
    primary: ["quadriceps", "gluteusMaximus"], secondary: ["hamstrings"], equipment: ["Hantle", "Ławka płaska"], laterality: "jednostronne",
    start: "Tylna stopa na ławce, przednia w wykroku, tułów wyprostowany.",
    steps: ["Ustaw stabilny wykrok.", "Zejdź pionowo w dół.", "Wróć naciskając przednią stopą."],
    mistakes: ["Zbyt krótki wykrok obciążający kolano", "Utrata równowagi"],
    regression: "split-squat", progression: null, substitutions: ["split-squat", "wykrok-w-tyl"],
    parameters: ["serie", "powtorzenia", "ciezar", "strona", "tempo", "przerwa"], protocol: "3 × 10 na stronę" },
  { slug: "split-squat", name: "Przysiad w wykroku", en: "Split Squat", pattern: "lunge",
    primary: ["quadriceps", "gluteusMaximus"], secondary: [], equipment: ["Hantle", "Masa ciała"], level: "Podstawowy", laterality: "jednostronne",
    start: "Stopy w wykroku, obie na podłożu.",
    steps: ["Zejdź pionowo, aż tylne kolano zbliży się do podłogi.", "Wróć naciskając przednią stopą."],
    mistakes: ["Przenoszenie ciężaru na tylną nogę"], regression: null, progression: "przysiad-bulgarski",
    substitutions: ["wykrok-w-tyl"], protocol: "3 × 12 na stronę" },
  { slug: "wykrok-w-tyl", name: "Wykrok w tył", en: "Reverse Lunge", pattern: "lunge",
    primary: ["quadriceps", "gluteusMaximus"], secondary: ["hamstrings"], equipment: ["Hantle", "Masa ciała"], level: "Podstawowy", laterality: "naprzemienne",
    start: "Stoisz w rozkroku na szerokość bioder.",
    steps: ["Cofnij stopę i obniż biodra pionowo.", "Dotknij kolanem podłoża lub zatrzymaj tuż nad nim.", "Wróć naciskając przednią stopą."],
    mistakes: ["Zbyt krótki krok", "Uciekanie kolana do środka"],
    regression: "split-squat", progression: "wykrok-chodzony", substitutions: ["wykrok-w-przod"], protocol: "3 × 10 na stronę" },
  { slug: "wykrok-w-przod", name: "Wykrok w przód", en: "Forward Lunge", pattern: "lunge",
    primary: ["quadriceps", "gluteusMaximus"], secondary: [], equipment: ["Hantle", "Masa ciała"], level: "Podstawowy", laterality: "naprzemienne",
    start: "Stoisz w rozkroku, ciężar przy tułowiu.",
    steps: ["Zrób krok w przód.", "Obniż biodra pionowo.", "Odepchnij się przednią nogą i wróć."],
    mistakes: ["Wysuwanie kolana daleko przed palce"], regression: "split-squat", progression: "wykrok-chodzony",
    substitutions: ["wykrok-w-tyl"], protocol: "3 × 10 na stronę" },
  { slug: "wykrok-chodzony", name: "Wykrok chodzony", en: "Walking Lunge", pattern: "lunge",
    primary: ["quadriceps", "gluteusMaximus"], secondary: ["hamstrings"], equipment: ["Hantle"], laterality: "naprzemienne",
    start: "Stoisz z hantlami przy udach.",
    steps: ["Wykonaj wykrok w przód.", "Wstań i od razu przejdź w wykrok drugą nogą.", "Utrzymuj wyprostowany tułów."],
    mistakes: ["Zbyt szybkie tempo kosztem kontroli"], regression: "wykrok-w-przod", progression: null,
    substitutions: ["wykrok-w-przod"], parameters: ["serie", "powtorzenia", "ciezar", "dystans", "tempo", "przerwa"], protocol: "3 × 20 kroków" },
  { slug: "wejscie-na-podest", name: "Wejście na podest", en: "Step-up", pattern: "lunge",
    primary: ["quadriceps", "gluteusMaximus"], secondary: ["calves"], equipment: ["Skrzynia plyometryczna", "Hantle"], level: "Podstawowy", laterality: "jednostronne",
    start: "Stopa na podeście o wysokości do kolana.",
    steps: ["Postaw całą stopę na podeście.", "Wstań bez odbijania się dolną nogą.", "Zejdź kontrolowanie."],
    mistakes: ["Odpychanie się dolną nogą"], regression: null, progression: "przysiad-bulgarski",
    substitutions: ["wykrok-w-tyl"], protocol: "3 × 10 na stronę" },
  { slug: "cyclist-squat", name: "Przysiad z uniesionymi piętami", en: "Cyclist Squat", pattern: "squat",
    primary: ["quadriceps"], secondary: [], equipment: ["Sztanga", "Talerze"],
    start: "Pięty na podwyższeniu, stopy blisko siebie.",
    steps: ["Ustaw pięty na talerzach.", "Zejdź głęboko z pionowym tułowiem.", "Wstań, naciskając śródstopiem."],
    mistakes: ["Zbyt wysokie podwyższenie"], regression: "przysiad-goblet", progression: null, substitutions: ["hack-squat"], protocol: "3 × 10" },
  { slug: "spanish-squat", name: "Spanish squat", en: "Spanish Squat", pattern: "squat",
    primary: ["quadriceps"], secondary: [], equipment: ["Guma oporowa"], level: "Podstawowy", goals: ["Technika", "Sprawność"],
    start: "Guma zaczepiona za kolanami o stabilny punkt, ciężar odchylony do tyłu.",
    steps: ["Zejdź, utrzymując pionowe golenie.", "Zatrzymaj w dolnej pozycji.", "Wróć napinając czworogłowe."],
    mistakes: ["Wysuwanie kolan przed palce"], cues: ["Guma odciąża przód kolana"], regression: null, progression: null,
    substitutions: ["prostowanie-nog"], parameters: ["serie", "powtorzenia", "czas", "tempo", "przerwa"], protocol: "3 × 12" },
];

const hamstringDrafts: Draft[] = [
  { slug: "rumunski-martwy-ciag", name: "Rumuński martwy ciąg", en: "Romanian Deadlift", pattern: "hinge",
    primary: ["hamstrings"], secondary: ["gluteusMaximus", "erectorSpinae"], equipment: ["Sztanga", "Hantle"], goals: ["Masa mięśniowa", "Siła"],
    aliases: ["rdl", "martwy rumuński"],
    start: "Stoisz ze sztangą przy udach, kolana lekko ugięte.",
    steps: ["Cofaj biodra, prowadząc sztangę blisko ud i goleni.", "Zejdź do pierwszego wyraźnego napięcia dwugłowych.", "Wróć wyprostem bioder."],
    mistakes: ["Zamiana zawiasu w przysiad", "Zaokrąglanie pleców", "Oddalanie sztangi od nóg"],
    cues: ["Odsuń biodra do ściany za tobą"], regression: "hip-hinge-z-kijem", progression: "stiff-leg-deadlift",
    substitutions: ["stiff-leg-deadlift", "good-morning"], protocol: "4 × 8" },
  { slug: "stiff-leg-deadlift", name: "Martwy ciąg na prostych nogach", en: "Stiff-Leg Deadlift", pattern: "hinge",
    primary: ["hamstrings"], secondary: ["gluteusMaximus"], equipment: ["Sztanga"],
    start: "Kolana niemal wyprostowane, sztanga przy udach.",
    steps: ["Cofaj biodra przy niemal prostych kolanach.", "Zejdź do granicy napięcia.", "Wróć wyprostem bioder."],
    mistakes: ["Zaokrąglanie pleców przy wymuszaniu zakresu"], precautions: ["Wymaga dobrej ruchomości dwugłowych."],
    regression: "rumunski-martwy-ciag", progression: null, substitutions: ["rumunski-martwy-ciag"], protocol: "3 × 10" },
  { slug: "rdl-jednonoz", name: "Martwy ciąg na jednej nodze", en: "Single-Leg Romanian Deadlift", pattern: "hinge",
    primary: ["hamstrings", "gluteusMaximus"], secondary: ["erectorSpinae"], equipment: ["Hantel", "Kettlebell"], laterality: "jednostronne",
    start: "Ciężar w dłoni po stronie przeciwnej do nogi podporowej.",
    steps: ["Przenieś ciężar ciała na jedną nogę.", "Cofaj biodro, utrzymując miednicę równolegle do podłoża.", "Wróć wyprostem biodra."],
    mistakes: ["Rotowanie miednicy"], regression: "rumunski-martwy-ciag", progression: null, substitutions: ["rumunski-martwy-ciag"],
    parameters: ["serie", "powtorzenia", "ciezar", "strona", "tempo", "przerwa"], protocol: "3 × 10 na stronę" },
  { slug: "good-morning", name: "Good morning", en: "Good Morning", pattern: "hinge",
    primary: ["hamstrings"], secondary: ["gluteusMaximus", "erectorSpinae"], equipment: ["Sztanga", "Stojaki"], level: "Zaawansowany",
    start: "Sztanga na barkach, kolana lekko ugięte.",
    steps: ["Napnij tułów.", "Cofaj biodra, pochylając tułów.", "Wróć wyprostem bioder."],
    mistakes: ["Zbyt duży ciężar i utrata neutralnych pleców"], precautions: ["Zaczynaj od bardzo małego obciążenia."],
    regression: "rumunski-martwy-ciag", progression: null, substitutions: ["rumunski-martwy-ciag"], protocol: "3 × 8" },
  { slug: "uginanie-nog-siedzac", name: "Uginanie nóg siedząc", en: "Seated Leg Curl", pattern: "isolation",
    primary: ["hamstrings"], secondary: ["calves"], compound: false, equipment: ["Leg curl siedząc"], level: "Podstawowy",
    start: "Siedzisz z wałkiem nad ścięgnem Achillesa, uda zablokowane.",
    steps: ["Ugnij kolana do pełnego zakresu.", "Zatrzymaj w skurczu.", "Wróć powoli."],
    mistakes: ["Odrywanie bioder od siedziska"], regression: null, progression: "nordic-curl",
    substitutions: ["uginanie-nog-lezac"], protocol: "3 × 12" },
  { slug: "uginanie-nog-lezac", name: "Uginanie nóg leżąc", en: "Lying Leg Curl", pattern: "isolation",
    primary: ["hamstrings"], secondary: ["calves"], compound: false, equipment: ["Leg curl leżąc"], level: "Podstawowy",
    start: "Leżysz na brzuchu, wałek nad ścięgnem Achillesa.",
    steps: ["Ugnij kolana do skurczu.", "Nie odrywaj bioder od leżanki.", "Wróć powoli."],
    mistakes: ["Odrywanie bioder"], regression: null, progression: "nordic-curl", substitutions: ["uginanie-nog-siedzac"], protocol: "3 × 12" },
  { slug: "nordic-curl", name: "Nordic curl", en: "Nordic Hamstring Curl", pattern: "isolation",
    primary: ["hamstrings"], secondary: [], compound: false, equipment: ["Masa ciała"], level: "Zaawansowany", goals: ["Siła", "Sprawność"],
    start: "Klęk z zablokowanymi stopami, tułów wyprostowany.",
    steps: ["Opadaj do przodu tak wolno, jak potrafisz.", "Zamortyzuj upadek dłońmi.", "Odepchnij się i wróć do klęku."],
    mistakes: ["Zginanie w biodrach zamiast prostowanie kolan"], precautions: ["Bardzo wymagające ekscentrycznie — wprowadzaj stopniowo."],
    regression: "uginanie-nog-lezac", progression: null, substitutions: ["glute-ham-raise"],
    parameters: ["serie", "powtorzenia", "tempo", "przerwa"], protocol: "3 × 5" },
  { slug: "glute-ham-raise", name: "Glute-ham raise", en: "Glute-Ham Raise", pattern: "isolation",
    primary: ["hamstrings", "gluteusMaximus"], secondary: ["erectorSpinae"], compound: false, equipment: ["Maszyna plate-loaded"], level: "Zaawansowany",
    start: "Stopy zablokowane, uda na podparciu, tułów wyprostowany.",
    steps: ["Opuść tułów w kontrolowany sposób.", "Wróć, napinając dwugłowe i pośladki."],
    mistakes: ["Zginanie w biodrach"], regression: "nordic-curl", progression: null, substitutions: ["nordic-curl"], protocol: "3 × 8" },
  { slug: "uginanie-nog-wyciag", name: "Uginanie nóg na wyciągu", en: "Cable Leg Curl", pattern: "isolation",
    primary: ["hamstrings"], secondary: [], compound: false, equipment: ["Wyciąg dolny"], laterality: "jednostronne", level: "Podstawowy",
    start: "Opaska na kostce, stoisz przodem do wyciągu.",
    steps: ["Ugnij kolano, nie ruszając udem.", "Zatrzymaj w skurczu.", "Wróć powoli."],
    mistakes: ["Cofanie uda zamiast zginania kolana"], regression: null, progression: null, substitutions: ["uginanie-nog-lezac"], protocol: "3 × 15 na stronę" },
  { slug: "kettlebell-swing", name: "Swing z kettlebell", en: "Kettlebell Swing", pattern: "hinge",
    primary: ["gluteusMaximus", "hamstrings"], secondary: ["erectorSpinae", "forearms"], equipment: ["Kettlebell"], goals: ["Sprawność", "Wytrzymałość"],
    start: "Kettlebell przed sobą, stopy na szerokość barków.",
    steps: ["Zahaczaj kettlebell między nogami zawiasem biodrowym.", "Wypchnij biodra dynamicznie do przodu.", "Pozwól ciężarowi wznieść się do wysokości klatki bez unoszenia go ramionami."],
    breathing: "Wydech przy wyproście bioder, wdech przy zahaczeniu.",
    mistakes: ["Unoszenie kettlebell ramionami", "Zamiana zawiasu w przysiad"],
    regression: "pull-through", progression: null, substitutions: ["pull-through"],
    parameters: ["serie", "powtorzenia", "ciezar", "czas", "przerwa"], protocol: "5 × 15" },
  { slug: "pull-through", name: "Pull-through na wyciągu", en: "Cable Pull-Through", pattern: "hinge",
    primary: ["gluteusMaximus"], secondary: ["hamstrings"], equipment: ["Wyciąg dolny"], level: "Podstawowy", goals: ["Technika"],
    start: "Stoisz tyłem do wyciągu, linka między nogami.",
    steps: ["Cofaj biodra, pozwalając linie przejść między nogami.", "Wyprostuj biodra, ściskając pośladki.", "Nie odchylaj tułowia na końcu."],
    mistakes: ["Przeprost lędźwi na końcu ruchu"], regression: null, progression: "kettlebell-swing", substitutions: ["hip-thrust"], protocol: "3 × 15" },
  { slug: "hip-hinge-z-kijem", name: "Nauka zawiasu biodrowego z kijem", en: "Dowel Hip Hinge", pattern: "hinge",
    primary: ["hamstrings"], secondary: ["erectorSpinae"], equipment: ["Kij"], level: "Podstawowy", goals: ["Technika"],
    start: "Kij przy plecach, dotyka głowy, łopatek i kości krzyżowej.",
    steps: ["Cofaj biodra, utrzymując trzy punkty kontaktu z kijem.", "Zejdź do granicy, w której kontakt zostaje zachowany.", "Wróć wyprostem bioder."],
    mistakes: ["Utrata kontaktu kija z plecami"], regression: null, progression: "rumunski-martwy-ciag",
    substitutions: ["rumunski-martwy-ciag"], parameters: ["serie", "powtorzenia", "tempo", "przerwa"], protocol: "3 × 10" },
];

const gluteDrafts: Draft[] = [
  { slug: "hip-thrust", name: "Hip thrust ze sztangą", en: "Barbell Hip Thrust", pattern: "hinge",
    primary: ["gluteusMaximus"], secondary: ["hamstrings", "rectusAbdominis"], equipment: ["Sztanga", "Ławka płaska"], goals: ["Masa mięśniowa", "Siła"],
    start: "Łopatki oparte o ławkę, sztanga na biodrach, stopy pod kolanami.",
    steps: ["Dociśnij żebra i podwiń miednicę.", "Wypchnij biodra do pełnego wyprostu.", "Zatrzymaj na moment i opuść kontrolowanie."],
    mistakes: ["Przeprost lędźwi zamiast wyprostu bioder", "Zbyt daleko ustawione stopy"],
    cues: ["Broda schowana, żebra w dół — ruch ma wyjść z bioder"],
    regression: "glute-bridge", progression: null, substitutions: ["hip-thrust-maszyna", "glute-bridge"], protocol: "4 × 10" },
  { slug: "hip-thrust-maszyna", name: "Hip thrust na maszynie", en: "Machine Hip Thrust", pattern: "hinge",
    primary: ["gluteusMaximus"], secondary: ["hamstrings"], equipment: ["Maszyna hip thrust"], level: "Podstawowy",
    start: "Plecy przy oparciu, wałek na biodrach.",
    steps: ["Wypchnij biodra do wyprostu.", "Zatrzymaj w skurczu.", "Wróć powoli."],
    mistakes: ["Praca lędźwiami"], regression: null, progression: "hip-thrust", substitutions: ["hip-thrust"], protocol: "3 × 12" },
  { slug: "hip-thrust-smith", name: "Hip thrust na Smithie", en: "Smith Machine Hip Thrust", pattern: "hinge",
    primary: ["gluteusMaximus"], secondary: ["hamstrings"], equipment: ["Smith machine", "Ławka płaska"],
    start: "Łopatki na ławce, gryf na biodrach na prowadnicy.",
    steps: ["Odblokuj gryf.", "Wypchnij biodra do wyprostu.", "Opuść kontrolowanie i zablokuj po serii."],
    mistakes: ["Złe ustawienie ławki względem prowadnicy"], regression: "hip-thrust-maszyna", progression: null,
    substitutions: ["hip-thrust"], protocol: "3 × 12" },
  { slug: "glute-bridge", name: "Mostek biodrowy", en: "Glute Bridge", pattern: "hinge",
    primary: ["gluteusMaximus"], secondary: ["hamstrings"], equipment: ["Masa ciała"], level: "Podstawowy", goals: ["Technika", "Sprawność"],
    start: "Leżysz na plecach, kolana ugięte, stopy blisko pośladków.",
    steps: ["Dociśnij pięty.", "Unieś biodra do linii kolano–biodro–bark.", "Zatrzymaj i opuść powoli."],
    mistakes: ["Unoszenie bioder ruchem z lędźwi"], regression: null, progression: "hip-thrust",
    substitutions: ["frog-pump"], parameters: ["serie", "powtorzenia", "tempo", "czas", "przerwa"], protocol: "3 × 15" },
  { slug: "frog-pump", name: "Frog pump", en: "Frog Pump", pattern: "hinge",
    primary: ["gluteusMaximus"], secondary: [], equipment: ["Masa ciała"], level: "Podstawowy",
    start: "Leżysz na plecach, podeszwy stóp złączone, kolana na boki.",
    steps: ["Unieś biodra, ściskając pośladki.", "Zatrzymaj w skurczu.", "Opuść powoli."],
    mistakes: ["Praca lędźwiami"], regression: null, progression: "glute-bridge", substitutions: ["glute-bridge"], protocol: "3 × 20" },
  { slug: "kickback-wyciag", name: "Kopnięcie w tył na wyciągu", en: "Cable Kickback", pattern: "isolation",
    primary: ["gluteusMaximus"], secondary: ["hamstrings"], compound: false, equipment: ["Wyciąg dolny"], level: "Podstawowy", laterality: "jednostronne",
    start: "Opaska na kostce, stoisz przodem do wyciągu.",
    steps: ["Utrzymaj tułów nieruchomo.", "Wyprostuj biodro do tyłu.", "Wróć powoli bez przeprostu lędźwi."],
    mistakes: ["Wyginanie pleców zamiast wyprostu biodra"], regression: null, progression: null,
    substitutions: ["glute-kickback-maszyna"], protocol: "3 × 15 na stronę" },
  { slug: "glute-kickback-maszyna", name: "Glute kickback na maszynie", en: "Glute Kickback Machine", pattern: "isolation",
    primary: ["gluteusMaximus"], secondary: [], compound: false, equipment: ["Glute kickback"], level: "Podstawowy", laterality: "jednostronne",
    start: "Klatka przy oparciu, stopa na podnóżku.",
    steps: ["Wypchnij podnóżek do wyprostu biodra.", "Zatrzymaj w skurczu.", "Wróć powoli."],
    mistakes: ["Przeprost lędźwi"], regression: null, progression: null, substitutions: ["kickback-wyciag"], protocol: "3 × 15 na stronę" },
  { slug: "reverse-hyperextension", name: "Reverse hyperextension", en: "Reverse Hyperextension", pattern: "hinge",
    primary: ["gluteusMaximus"], secondary: ["hamstrings", "erectorSpinae"], equipment: ["Maszyna plate-loaded"],
    start: "Leżysz biodrami na podparciu, nogi zwisają.",
    steps: ["Unieś nogi do linii tułowia.", "Zatrzymaj w skurczu.", "Opuść powoli bez rozpędu."],
    mistakes: ["Wymachiwanie nogami"], regression: "glute-bridge", progression: null, substitutions: ["back-extension-45"], protocol: "3 × 12" },
  { slug: "curtsy-lunge", name: "Wykrok skrzyżny", en: "Curtsy Lunge", pattern: "lunge",
    primary: ["gluteusMaximus"], secondary: ["quadriceps", "adductors"], equipment: ["Hantle", "Masa ciała"], laterality: "naprzemienne",
    start: "Stoisz w rozkroku, ciężar przy tułowiu.",
    steps: ["Cofnij nogę skośnie za drugą.", "Obniż biodra.", "Wróć naciskając przednią stopą."],
    mistakes: ["Rotowanie miednicy"], regression: "wykrok-w-tyl", progression: null, substitutions: ["wykrok-w-tyl"], protocol: "3 × 12 na stronę" },
  { slug: "przysiad-sumo", name: "Przysiad sumo", en: "Sumo Squat", pattern: "squat",
    primary: ["gluteusMaximus", "adductors"], secondary: ["quadriceps"], equipment: ["Hantel", "Kettlebell"], level: "Podstawowy",
    start: "Stopy szeroko, palce na zewnątrz, ciężar między nogami.",
    steps: ["Zejdź, prowadząc kolana nad stopami.", "Zatrzymaj na dole.", "Wstań, ściskając pośladki."],
    mistakes: ["Zapadanie kolan do środka"], regression: "przysiad-goblet", progression: null, substitutions: ["przysiad-goblet"], protocol: "3 × 12" },
  { slug: "abduction-maszyna", name: "Odwodzenie na maszynie", en: "Hip Abduction Machine", pattern: "isolation",
    primary: ["abductors"], secondary: ["gluteusMaximus"], compound: false, equipment: ["Maszyna odwodzicieli"], level: "Podstawowy",
    start: "Siedzisz prosto, uda przy oporach.",
    steps: ["Odwiedź uda przeciw oporowi.", "Zatrzymaj w skurczu.", "Wróć powoli."],
    mistakes: ["Odchylanie tułowia dla większego zakresu"], regression: null, progression: null,
    substitutions: ["odwodzenie-wyciag", "lateral-band-walk"], protocol: "3 × 15" },
  { slug: "odwodzenie-wyciag", name: "Odwodzenie nogi na wyciągu", en: "Cable Hip Abduction", pattern: "isolation",
    primary: ["abductors"], secondary: ["gluteusMaximus"], compound: false, equipment: ["Wyciąg dolny"], laterality: "jednostronne", level: "Podstawowy",
    start: "Opaska na kostce, stoisz bokiem do wyciągu.",
    steps: ["Odwiedź nogę na bok.", "Zatrzymaj w skurczu.", "Wróć powoli."],
    mistakes: ["Odchylanie tułowia"], regression: null, progression: null, substitutions: ["abduction-maszyna"], protocol: "3 × 15 na stronę" },
  { slug: "lateral-band-walk", name: "Chód bokiem z gumą", en: "Lateral Band Walk", pattern: "locomotion",
    primary: ["abductors"], secondary: ["gluteusMaximus"], equipment: ["Miniband"], level: "Podstawowy", goals: ["Sprawność", "Technika"],
    start: "Guma nad kolanami lub przy kostkach, półprzysiad.",
    steps: ["Utrzymaj półprzysiad.", "Rób kroki w bok, nie łącząc stóp.", "Zachowaj napięcie gumy przez cały czas."],
    mistakes: ["Prostowanie nóg w trakcie chodu"], regression: null, progression: "monster-walk",
    substitutions: ["abduction-maszyna"], parameters: ["serie", "powtorzenia", "dystans", "czas", "przerwa"], protocol: "3 × 15 kroków" },
  { slug: "monster-walk", name: "Monster walk", en: "Monster Walk", pattern: "locomotion",
    primary: ["abductors", "gluteusMaximus"], secondary: [], equipment: ["Miniband"], level: "Podstawowy",
    start: "Guma przy kostkach, półprzysiad.",
    steps: ["Idź do przodu skośnymi krokami.", "Utrzymaj napięcie gumy.", "Wróć tyłem."],
    mistakes: ["Prostowanie tułowia i nóg"], regression: "lateral-band-walk", progression: null, substitutions: ["lateral-band-walk"],
    parameters: ["serie", "dystans", "czas", "przerwa"], protocol: "3 × 20 kroków" },
  { slug: "quadruped-hip-extension", name: "Wyprost biodra w klęku podpartym", en: "Quadruped Hip Extension", pattern: "isolation",
    primary: ["gluteusMaximus"], secondary: [], compound: false, equipment: ["Mata"], level: "Podstawowy", laterality: "jednostronne",
    start: "Klęk podparty, plecy neutralne.",
    steps: ["Unieś nogę do linii tułowia, zginając kolano.", "Nie rotuj miednicy.", "Wróć powoli."],
    mistakes: ["Przeprost lędźwi i rotacja miednicy"], regression: null, progression: "glute-kickback-maszyna",
    substitutions: ["kickback-wyciag"], parameters: ["serie", "powtorzenia", "tempo", "strona", "przerwa"], protocol: "3 × 15 na stronę" },
];

const adductorDrafts: Draft[] = [
  { slug: "adductor-maszyna", name: "Przywodzenie na maszynie", en: "Hip Adduction Machine", pattern: "isolation",
    primary: ["adductors"], secondary: [], compound: false, equipment: ["Maszyna przywodzicieli"], level: "Podstawowy",
    start: "Siedzisz prosto, uda na oporach rozłożonych na boki.",
    steps: ["Zbliż uda do siebie.", "Zatrzymaj w skurczu.", "Wróć powoli do rozciągnięcia."],
    mistakes: ["Zbyt duży zakres na starcie"], precautions: ["Przy przebytym naciągnięciu przywodzicieli wchodź w zakres stopniowo."],
    regression: null, progression: "copenhagen-plank", substitutions: ["przywodzenie-wyciag"], protocol: "3 × 15" },
  { slug: "przywodzenie-wyciag", name: "Przywodzenie na wyciągu", en: "Cable Hip Adduction", pattern: "isolation",
    primary: ["adductors"], secondary: [], compound: false, equipment: ["Wyciąg dolny"], laterality: "jednostronne", level: "Podstawowy",
    start: "Opaska na kostce, stoisz bokiem do wyciągu, noga odwiedziona.",
    steps: ["Przyciągnij nogę do linii środkowej ciała.", "Zatrzymaj w skurczu.", "Wróć powoli."],
    mistakes: ["Rotowanie tułowia"], regression: null, progression: null, substitutions: ["adductor-maszyna"], protocol: "3 × 15 na stronę" },
  { slug: "copenhagen-plank", name: "Copenhagen plank", en: "Copenhagen Plank", pattern: "anti-rotation",
    primary: ["adductors"], secondary: ["obliques"], equipment: ["Ławka płaska"], level: "Zaawansowany", laterality: "jednostronne", goals: ["Sprawność", "Technika"],
    start: "Podpór bokiem, górna noga oparta o ławkę.",
    steps: ["Unieś biodra do linii ciała.", "Utrzymaj pozycję zadany czas.", "Zejdź kontrolowanie."],
    mistakes: ["Opadanie bioder"], precautions: ["Wymagające dla przywodzicieli — zacznij od wersji z ugiętym kolanem."],
    regression: "adductor-maszyna", progression: null, substitutions: ["adductor-maszyna"],
    parameters: ["serie", "czas", "strona", "przerwa"], protocol: "3 × 20 s na stronę" },
  { slug: "cossack-squat", name: "Cossack squat", en: "Cossack Squat", pattern: "lunge",
    primary: ["adductors", "quadriceps"], secondary: ["gluteusMaximus"], equipment: ["Masa ciała", "Kettlebell"], laterality: "naprzemienne", goals: ["Mobilność", "Sprawność"],
    start: "Bardzo szeroki rozkrok, stopy skierowane do przodu.",
    steps: ["Przenieś ciężar nad jedną nogę, uginając ją.", "Drugą nogę utrzymuj wyprostowaną.", "Przejdź na drugą stronę bez wstawania."],
    mistakes: ["Odrywanie pięty nogi podporowej"], regression: "wykrok-boczny", progression: null,
    substitutions: ["wykrok-boczny"], parameters: ["serie", "powtorzenia", "ciezar", "strona", "tempo", "przerwa"], protocol: "3 × 8 na stronę" },
  { slug: "wykrok-boczny", name: "Wykrok boczny", en: "Lateral Lunge", pattern: "lunge",
    primary: ["adductors", "gluteusMaximus"], secondary: ["quadriceps"], equipment: ["Masa ciała", "Hantle"], level: "Podstawowy", laterality: "naprzemienne",
    start: "Stoisz w rozkroku na szerokość bioder.",
    steps: ["Zrób krok w bok i przenieś biodra nad tę nogę.", "Drugą nogę utrzymuj prostą.", "Odepchnij się i wróć."],
    mistakes: ["Skręcanie kolana", "Odrywanie pięty"], regression: null, progression: "cossack-squat",
    substitutions: ["cossack-squat"], protocol: "3 × 10 na stronę" },
];

const calfDrafts: Draft[] = [
  { slug: "wspiecia-stojac", name: "Wspięcia na palce stojąc", en: "Standing Calf Raise", pattern: "isolation",
    primary: ["calves"], secondary: [], compound: false, equipment: ["Maszyna do łydek"], level: "Podstawowy",
    start: "Śródstopie na krawędzi platformy, kolana wyprostowane.",
    steps: ["Opuść pięty poniżej platformy.", "Wznieś się na palce do pełnego zakresu.", "Zatrzymaj na moment w górze."],
    mistakes: ["Sprężynowanie bez zatrzymania", "Skracanie zakresu"], regression: null, progression: "wspiecia-jednonoz",
    substitutions: ["wspiecia-na-suwnicy"], protocol: "4 × 12–15" },
  { slug: "wspiecia-siedzac", name: "Wspięcia na palce siedząc", en: "Seated Calf Raise", pattern: "isolation",
    primary: ["calves"], secondary: [], compound: false, equipment: ["Maszyna do łydek"], level: "Podstawowy",
    start: "Kolana pod wałkiem, śródstopie na platformie.",
    steps: ["Opuść pięty.", "Wznieś się na palce.", "Kontroluj powrót."],
    mistakes: ["Zbyt szybkie tempo"], cues: ["Zgięte kolano akcentuje mięsień płaszczkowaty"],
    regression: null, progression: null, substitutions: ["wspiecia-stojac"], protocol: "4 × 15" },
  { slug: "donkey-calf-raise", name: "Donkey calf raise", en: "Donkey Calf Raise", pattern: "isolation",
    primary: ["calves"], secondary: [], compound: false, equipment: ["Maszyna do łydek"],
    start: "Tułów pochylony, ręce oparte, śródstopie na platformie.",
    steps: ["Opuść pięty w pełnym rozciągnięciu.", "Wznieś się na palce.", "Wróć powoli."],
    mistakes: ["Uginanie kolan"], regression: "wspiecia-stojac", progression: null, substitutions: ["wspiecia-stojac"], protocol: "3 × 15" },
  { slug: "wspiecia-na-suwnicy", name: "Wspięcia na suwnicy", en: "Leg Press Calf Raise", pattern: "isolation",
    primary: ["calves"], secondary: [], compound: false, equipment: ["Leg press"], level: "Podstawowy",
    start: "Śródstopie na dolnej krawędzi platformy, kolana lekko ugięte.",
    steps: ["Wypchnij platformę palcami.", "Zatrzymaj w górze.", "Wróć do rozciągnięcia."],
    mistakes: ["Zginanie kolan w trakcie ruchu"], precautions: ["Nie zwalniaj blokad przy tym ćwiczeniu."],
    regression: null, progression: null, substitutions: ["wspiecia-stojac"], protocol: "4 × 15" },
  { slug: "wspiecia-smith", name: "Wspięcia na Smithie", en: "Smith Machine Calf Raise", pattern: "isolation",
    primary: ["calves"], secondary: [], compound: false, equipment: ["Smith machine", "Step"], level: "Podstawowy",
    start: "Gryf na barkach, śródstopie na stopniu.",
    steps: ["Opuść pięty poniżej stopnia.", "Wznieś się na palce.", "Wróć powoli."],
    mistakes: ["Brak stabilnego stopnia"], regression: null, progression: null, substitutions: ["wspiecia-stojac"], protocol: "4 × 15" },
  { slug: "wspiecia-jednonoz", name: "Wspięcia jednonóż", en: "Single-Leg Calf Raise", pattern: "isolation",
    primary: ["calves"], secondary: [], compound: false, equipment: ["Masa ciała", "Step"], laterality: "jednostronne",
    start: "Stoisz na jednej nodze na stopniu, druga uniesiona.",
    steps: ["Opuść piętę poniżej stopnia.", "Wznieś się na palce.", "Powtórz na drugą stronę."],
    mistakes: ["Podpieranie się ręką zamiast pracy stopą"], regression: "wspiecia-stojac", progression: null,
    substitutions: ["wspiecia-stojac"], protocol: "3 × 15 na stronę" },
  { slug: "tibialis-raise", name: "Unoszenie stopy", en: "Tibialis Raise", pattern: "isolation",
    primary: ["calves"], secondary: [], compound: false, equipment: ["Masa ciała", "Guma oporowa"], level: "Podstawowy", goals: ["Sprawność", "Technika"],
    start: "Plecy przy ścianie, stopy wysunięte do przodu.",
    steps: ["Unieś palce stóp maksymalnie w górę.", "Zatrzymaj na moment.", "Opuść powoli."],
    mistakes: ["Zbyt szybkie tempo"], cues: ["Równoważy pracę łydek i wspiera stabilność kolana"],
    regression: null, progression: null, substitutions: ["pogo-jump"], parameters: ["serie", "powtorzenia", "tempo", "przerwa"], protocol: "3 × 20" },
  { slug: "pogo-jump", name: "Podskoki na palcach", en: "Pogo Jump", pattern: "jump",
    primary: ["calves"], secondary: ["quadriceps"], equipment: ["Masa ciała"], goals: ["Sprawność", "Wytrzymałość"],
    start: "Stoisz w lekkim napięciu, kolana prawie wyprostowane.",
    steps: ["Odbijaj się wyłącznie ze stawu skokowego.", "Utrzymuj krótki kontakt z podłożem.", "Zachowaj sztywne kolana."],
    mistakes: ["Głębokie uginanie kolan"], precautions: ["Wymaga zdrowych ścięgien Achillesa."],
    regression: "wspiecia-stojac", progression: null, substitutions: ["wspiecia-jednonoz"],
    parameters: ["serie", "powtorzenia", "czas", "przerwa"], protocol: "4 × 20" },
];

export const quadExercises = buildCategory("Czworogłowe", quadDrafts);
export const hamstringExercises = buildCategory("Dwugłowe", hamstringDrafts);
export const gluteExercises = buildCategory("Pośladki", gluteDrafts);
export const adductorExercises = buildCategory("Przywodziciele", adductorDrafts);
export const calfExercises = buildCategory("Łydki", calfDrafts);
