import { buildCategory, type Draft } from "@/lib/exercises/catalog/helpers";

const drafts: Draft[] = [
  { slug: "overhead-press", name: "Wyciskanie żołnierskie", en: "Overhead Press", pattern: "vertical-push",
    primary: ["anteriorDeltoid", "lateralDeltoid"], secondary: ["triceps", "rectusAbdominis"], equipment: ["Sztanga", "Stojaki"], goals: ["Siła", "Masa mięśniowa"],
    aliases: ["ohp", "military press"],
    start: "Sztanga na przedniej części barków, stopy na szerokość bioder, żebra ściągnięte.",
    steps: ["Napnij pośladki i brzuch.", "Cofnij głowę i wypchnij sztangę pionowo w górę.", "Domknij ruch nad środkiem stóp, chowając głowę pod gryf.", "Opuść kontrolowanie na barki."],
    mistakes: ["Odchylanie tułowia i przeprost lędźwi", "Prowadzenie sztangi łukiem przed twarzą"],
    cues: ["Ciężar ma wylądować nad środkiem stopy, nie przed nią"],
    precautions: ["Przy ograniczonej ruchomości barku lub odcinka piersiowego zacznij od wyciskania hantli."],
    regression: "wyciskanie-hantli-siedzac", progression: "push-press", substitutions: ["wyciskanie-hantli-siedzac", "maszyna-shoulder-press"], protocol: "4 × 6–8" },
  { slug: "push-press", name: "Push press", en: "Push Press", pattern: "vertical-push",
    primary: ["anteriorDeltoid"], secondary: ["triceps", "quadriceps"], equipment: ["Sztanga", "Stojaki"], level: "Zaawansowany", goals: ["Siła"],
    start: "Sztanga na barkach, stopy na szerokość bioder.",
    steps: ["Wykonaj krótkie ugięcie kolan.", "Wypchnij nogami i przenieś impet na sztangę.", "Domknij ramiona nad głową.", "Opuść na barki i zresetuj pozycję."],
    mistakes: ["Zbyt głębokie ugięcie zamieniające ruch w przysiad", "Wypychanie bioder do przodu"],
    regression: "overhead-press", progression: null, substitutions: ["overhead-press"], protocol: "5 × 3" },
  { slug: "wyciskanie-hantli-siedzac", name: "Wyciskanie hantli siedząc", en: "Seated Dumbbell Press", pattern: "vertical-push",
    primary: ["anteriorDeltoid", "lateralDeltoid"], secondary: ["triceps"], equipment: ["Hantle", "Ławka regulowana"], level: "Podstawowy",
    start: "Oparcie ustawione pionowo, hantle na wysokości uszu.",
    steps: ["Wyciśnij hantle nad głowę bez zderzania.", "Zatrzymaj tuż przed pełnym wyprostem.", "Opuść do wysokości uszu."],
    mistakes: ["Zbyt szerokie ustawienie łokci", "Odrywanie pleców od oparcia"],
    regression: "maszyna-shoulder-press", progression: "overhead-press", substitutions: ["arnold-press", "maszyna-shoulder-press"], protocol: "3 × 10" },
  { slug: "arnold-press", name: "Arnold press", en: "Arnold Press", pattern: "vertical-push",
    primary: ["anteriorDeltoid", "lateralDeltoid"], secondary: ["triceps"], equipment: ["Hantle", "Ławka regulowana"],
    start: "Hantle przed klatką, dłonie zwrócone do siebie.",
    steps: ["Rozpocznij rotację przedramion w trakcie wyciskania.", "Zakończ z dłońmi zwróconymi do przodu nad głową.", "Wróć tą samą drogą."],
    mistakes: ["Zbyt szybka rotacja kosztem kontroli"],
    regression: "wyciskanie-hantli-siedzac", progression: null, substitutions: ["wyciskanie-hantli-siedzac"], protocol: "3 × 10" },
  { slug: "maszyna-shoulder-press", name: "Wyciskanie barków na maszynie", en: "Machine Shoulder Press", pattern: "vertical-push",
    primary: ["anteriorDeltoid"], secondary: ["triceps"], equipment: ["Shoulder press"], level: "Podstawowy",
    start: "Siedzisko ustawione tak, aby uchwyty były na wysokości barków.",
    steps: ["Wyciśnij uchwyty nad głowę.", "Nie blokuj łokci w górze.", "Wróć do wysokości barków."],
    mistakes: ["Zbyt niskie siedzisko"], regression: null, progression: "wyciskanie-hantli-siedzac", substitutions: ["wyciskanie-hantli-siedzac"], protocol: "3 × 12" },
  { slug: "landmine-press-barki", name: "Wyciskanie landmine na barki", en: "Landmine Shoulder Press", pattern: "vertical-push",
    primary: ["anteriorDeltoid"], secondary: ["triceps", "rectusAbdominis"], equipment: ["Landmine", "Sztanga"], laterality: "jednostronne",
    start: "Klęk jednonóż, koniec gryfu przy barku.",
    steps: ["Napnij brzuch i pośladki.", "Wypchnij gryf po skosie w górę.", "Wróć kontrolowanie."],
    mistakes: ["Rotowanie tułowia"], precautions: ["Skos landmine bywa lepiej tolerowany niż wyciskanie pionowe przy ograniczonej ruchomości barku."],
    regression: "maszyna-shoulder-press", progression: null, substitutions: ["wyciskanie-hantli-siedzac"], protocol: "3 × 10 na stronę" },
  { slug: "wznosy-bokiem-hantle", name: "Unoszenie hantli bokiem", en: "Dumbbell Lateral Raise", pattern: "isolation",
    primary: ["lateralDeltoid"], secondary: ["trapezius"], compound: false, equipment: ["Hantle"], level: "Podstawowy", goals: ["Masa mięśniowa"],
    start: "Stoisz z hantlami przy udach, łokcie lekko ugięte.",
    steps: ["Unieś ramiona łukiem na boki do wysokości barków.", "Zatrzymaj na moment.", "Opuść powoli, kontrolując ruch."],
    mistakes: ["Unoszenie barków do uszu", "Zamach tułowiem", "Zbyt duży ciężar"],
    cues: ["Prowadź ruch łokciem, nie dłonią"],
    regression: "wznosy-bokiem-maszyna", progression: "wznosy-bokiem-wyciag", substitutions: ["wznosy-bokiem-wyciag", "wznosy-bokiem-maszyna"],
    parameters: ["serie", "powtorzenia", "ciezar", "tempo", "przerwa"], protocol: "3 × 12–15" },
  { slug: "wznosy-bokiem-wyciag", name: "Unoszenie linki bokiem", en: "Cable Lateral Raise", pattern: "isolation",
    primary: ["lateralDeltoid"], secondary: [], compound: false, equipment: ["Brama kablowa"], laterality: "jednostronne",
    start: "Stoisz bokiem do dolnego wyciągu, uchwyt w dalszej dłoni.",
    steps: ["Prowadź ramię łukiem do wysokości barku.", "Utrzymaj napięcie także w dolnej fazie.", "Opuść powoli."],
    mistakes: ["Zamach tułowiem"], regression: "wznosy-bokiem-hantle", progression: null, substitutions: ["wznosy-bokiem-hantle"], protocol: "3 × 15 na stronę" },
  { slug: "wznosy-bokiem-maszyna", name: "Unoszenie bokiem na maszynie", en: "Lateral Raise Machine", pattern: "isolation",
    primary: ["lateralDeltoid"], secondary: [], compound: false, equipment: ["Maszyna stosowa"], level: "Podstawowy",
    start: "Siedzisz z ramionami przy wałkach, łokcie lekko ugięte.",
    steps: ["Unieś ramiona do wysokości barków.", "Zatrzymaj w górze.", "Opuść powoli."],
    mistakes: ["Unoszenie barków"], regression: null, progression: "wznosy-bokiem-hantle", substitutions: ["wznosy-bokiem-hantle"], protocol: "3 × 15" },
  { slug: "wznosy-bokiem-w-pochyleniu", name: "Unoszenie bokiem w pochyleniu", en: "Leaning Lateral Raise", pattern: "isolation",
    primary: ["lateralDeltoid"], secondary: [], compound: false, equipment: ["Hantle"], laterality: "jednostronne",
    start: "Trzymasz się stojaka jedną ręką, tułów odchylony, hantel w wolnej dłoni.",
    steps: ["Odchyl tułów, żeby wydłużyć zakres.", "Unieś hantel do wysokości barku.", "Opuść powoli."],
    mistakes: ["Zbyt duży ciężar przy wydłużonym zakresie"],
    regression: "wznosy-bokiem-hantle", progression: null, substitutions: ["wznosy-bokiem-wyciag"], protocol: "3 × 12 na stronę" },
  { slug: "wznosy-przodem", name: "Unoszenie ramion przodem", en: "Front Raise", pattern: "isolation",
    primary: ["anteriorDeltoid"], secondary: ["pectoralisMajor"], compound: false, equipment: ["Hantle", "Talerze"], level: "Podstawowy",
    start: "Stoisz z ciężarem przed udami.", steps: ["Unieś ramiona przed siebie do wysokości barków.", "Zatrzymaj na moment.", "Opuść powoli."],
    mistakes: ["Odchylanie tułowia i zamach biodrami"], regression: null, progression: null, substitutions: ["landmine-press-barki"], protocol: "3 × 12" },
  { slug: "odwodzenie-w-opadzie", name: "Odwodzenie w opadzie", en: "Bent-over Reverse Fly", pattern: "isolation",
    primary: ["posteriorDeltoid"], secondary: ["trapezius"], compound: false, equipment: ["Hantle"], level: "Podstawowy", goals: ["Masa mięśniowa", "Sprawność"],
    start: "Tułów w opadzie, plecy proste, hantle pod klatką.",
    steps: ["Rozwiedź ramiona na boki przy lekko ugiętych łokciach.", "Zatrzymaj na moment.", "Opuść powoli."],
    mistakes: ["Ściąganie łopatek zamiast pracy tylnego aktonu", "Zbyt duży ciężar"],
    regression: "reverse-pec-deck", progression: null, substitutions: ["reverse-pec-deck", "face-pull"], protocol: "3 × 15" },
  { slug: "reverse-pec-deck", name: "Reverse pec deck", en: "Reverse Pec Deck", pattern: "isolation",
    primary: ["posteriorDeltoid"], secondary: ["trapezius"], compound: false, equipment: ["Reverse pec deck"], level: "Podstawowy",
    start: "Siedzisz klatką do oparcia, ramiona przed sobą.",
    steps: ["Rozwiedź ramiona na boki.", "Zatrzymaj w skurczu.", "Wróć powoli."],
    mistakes: ["Odrywanie klatki od oparcia"], regression: null, progression: "odwodzenie-w-opadzie", substitutions: ["odwodzenie-w-opadzie"], protocol: "3 × 15" },
  { slug: "rear-delt-cable-fly", name: "Odwodzenie na bramie", en: "Rear Delt Cable Fly", pattern: "isolation",
    primary: ["posteriorDeltoid"], secondary: [], compound: false, equipment: ["Brama kablowa"],
    start: "Stoisz między wyciągami, linki skrzyżowane na wysokości barków.",
    steps: ["Rozwiedź ramiona na boki i lekko do tyłu.", "Zatrzymaj w skurczu.", "Wróć powoli."],
    mistakes: ["Praca tułowiem"], regression: "reverse-pec-deck", progression: null, substitutions: ["face-pull"], protocol: "3 × 15" },
  { slug: "podciaganie-sztangi-wzdluz-tulowia", name: "Podciąganie sztangi wzdłuż tułowia", en: "Upright Row", pattern: "vertical-pull",
    primary: ["lateralDeltoid", "trapezius"], secondary: ["biceps"], equipment: ["Sztanga", "Sztanga EZ"],
    start: "Stoisz ze sztangą przed udami, chwyt na szerokość barków.",
    steps: ["Prowadź sztangę blisko tułowia.", "Unieś łokcie na boki do wysokości klatki.", "Opuść kontrolowanie."],
    mistakes: ["Ciągnięcie zbyt wysoko, co drażni bark"], precautions: ["Przy konflikcie podbarkowym pomiń to ćwiczenie."],
    regression: "wznosy-bokiem-hantle", progression: null, substitutions: ["wznosy-bokiem-hantle"], protocol: "3 × 12" },
  { slug: "cuban-press", name: "Cuban press", en: "Cuban Press", pattern: "isolation",
    primary: ["posteriorDeltoid"], secondary: ["lateralDeltoid", "trapezius"], compound: false, equipment: ["Hantle", "Sztanga EZ"], goals: ["Technika", "Sprawność"],
    start: "Stoisz z ciężarem, łokcie uniesione do wysokości barków, przedramiona w dół.",
    steps: ["Rotuj przedramiona w górę do pozycji nad łokciami.", "Wyciśnij ciężar nad głowę.", "Wróć tą samą drogą."],
    mistakes: ["Zbyt duży ciężar uniemożliwiający rotację"], regression: "rotacje-zewnetrzne-barku", progression: null,
    substitutions: ["rotacje-zewnetrzne-barku"], protocol: "3 × 12" },
  { slug: "y-raise", name: "Y-raise", en: "Y-Raise", pattern: "isolation",
    primary: ["trapezius"], secondary: ["posteriorDeltoid"], compound: false, equipment: ["Hantle", "Ławka regulowana"], level: "Podstawowy", goals: ["Sprawność", "Technika"],
    start: "Klatka oparta o ławkę na 30 stopni, ramiona zwisają.",
    steps: ["Unieś ramiona po skosie, tworząc literę Y.", "Zatrzymaj w górze.", "Opuść powoli."],
    mistakes: ["Unoszenie barków do uszu"], regression: null, progression: null, substitutions: ["odwodzenie-w-opadzie"], protocol: "3 × 15" },
  { slug: "rotacje-zewnetrzne-barku", name: "Rotacja zewnętrzna barku", en: "External Rotation", pattern: "isolation",
    primary: ["posteriorDeltoid"], secondary: [], compound: false, equipment: ["Guma oporowa", "Brama kablowa"], level: "Podstawowy", laterality: "jednostronne", goals: ["Technika", "Sprawność"],
    start: "Łokieć przy tułowiu zgięty do kąta prostego, opór z boku.",
    steps: ["Utrzymaj łokieć przy żebrach.", "Odwróć przedramię na zewnątrz.", "Wróć powoli."],
    mistakes: ["Odrywanie łokcia od tułowia", "Zbyt duży opór"],
    regression: null, progression: "cuban-press", substitutions: ["face-pull"], parameters: ["serie", "powtorzenia", "ciezar", "strona", "tempo", "przerwa"], protocol: "3 × 15 na stronę" },
];

export const shoulderExercises = buildCategory("Barki", drafts);
